FOREST: Forest::SphericalHarmonics< dim > Class Template Reference
Forest::SphericalHarmonics< dim > Class Template Reference
ForestAngle
Spherical harmonics generation for anisotropic scattering.
#include </home/lns/Codes/forest-public/mylib/include/angle/spherical_harmonics.h>
Public Member Functions
template<>
double Y_lm (const std::vector< int > &lm, const std::vector< double > &omega)
template<>
double Y_lm (const std::vector< int > &lm, const std::vector< double > &omega)
template<>
double Y_lm (const std::vector< int > &lm, const std::vector< double > &omega)
Static Public Member Functions
static double Y_lm (const std::vector< int > &lm, const std::vector< double > &omega)
Calculate \(Y^m_l(\Omega)\) given \(l,m\) and \(\Omega\) .
Static Private Member Functions
static double Y_lm (int l, int m, double xi, double varphi)
Calculate \(Y^m_l \) given \(\xi\) and \(\varphi\) .
static double get_Y_lm (int l, int m, double mu, double eta, double xi)
Calculate \(Y^m_l \) given \(\mathbf{\Omega}\).
Detailed Description
template<int dim>
class Forest::SphericalHarmonics< dim >
Spherical harmonics generation for anisotropic scattering.
Note
Use this class with two arguments: index and direction, where depending on the dimension the indices will be numbers or vectors
In 2-d and 3-d problems, an expansion of the angular flux in spherical harmonics is required to treat anisotropic scattering. In 1-d problems, the angular flux is expanded in Legendre polynomials, which can be considered to be a subset of the spherical harmonics.
We follow the presentation of Hebert.
Spherical Harmonics in 1D (Legendre polynomials).
A function of a directional cosine \(\xi\), \(f(\xi) \), can be represented as in \(L\)-th order Legendre expansion:
\[ f(\xi) \approx \sum^L_{l=0} \frac{2l+1}{2}P_l(\xi)f_l \, , \]
where the Legendre coefficients are defined
\[ f_l = \int^{1}_{-1} d\xi P_l(\xi) f(\xi) \, . \]
In the standard 1-d formulation, in which the azimuthal dependence is removed by integration, the zeroth Legendre moment angular flux \(\psi(z,\xi) \) is
\[ \phi_0(z) = \int^{1}_{-1} d\xi \psi(z,\xi) \, , \]
which we recognize as the scalar flux. The scattering source is defined in 1D as
\[ Q(z,\xi) = \int^{2\pi}_{0} d\phi' \int^{1}_{-1}d\xi' \Sigma_s(z,\mu_0)\psi(z,\xi') \\ \]
and can likewise be expanded (skipping several important steps! see e.g. the 22106 notes) as
\[ Q(z,\xi) \approx \sum^{L}_{l=0} \frac{2l+1}{2}\Sigma_{sl}(z)P_l(\xi)\phi_l(z) \, , \]
where the Legendre moments \(\Sigma_{sl} \) are provided in a cross-section library. Note, for consistency with the multidimensional coordinates, we place 1D problems along the \(z\)-axis. For 1D problems using an \(L\)-th order expansion (for scattering), there are \(L+1\) flux moments per node (and possibly more than one node per mesh).
Spherical Harmonics in 2D/3D .
For 2D and 3D problems, the azimuthal dependence requires use of the spherical harmonics for expansions.
The spherical harmonics \(Y^m_l(\Omega) = Y^m_l(\xi,\varphi)\) (in the source, denoted \(Y_{lm}\)) are defined
\[ Y^m_l(\xi,\varphi) = \sqrt{ (2-\delta_{m,0}) \frac{(l-|m|)!}{(l+|m|)!} } P^{|m|}_l (\xi) \mathcal{T}_m (\varphi) \ . \]
where the associated Legendre polynomials are defined in terms of Legendre polynomials as
\[ P^m_l(\xi) = (1-\xi^2)^{m/2} \frac{d^m}{d\xi^m} P_l(\xi) \, , \,\,\,\,\, m \geq 0 \, , \]
and the trigonometric functions are
\[ \mathcal{T}_m (\varphi) \left\{ \begin{array}{l l} \cos(m\varphi) & \quad \text{if $m \geq 0$ }\\ \sin(|m|\varphi) & \quad \text{otherwise} \, . \\ \end{array} \right. \]
The associated Legendre polynomials are as given use the so-called Ferrer definition, omitting the typically standard factor of \((-1)^m \) . Hebert notes this representation is helpful since
\[ \mathbf{\Omega} = \begin{pmatrix} \mu \\ \eta \\ \xi \end{pmatrix} = \begin{pmatrix} \sin(\theta)\cos(\varphi) \\ \sin(\theta)\sin(\varphi) \\ \cos(\theta) \end{pmatrix} = \begin{pmatrix} Y^{1}_{1}(\xi,\varphi) \\ Y^{-1}_{1}(\xi,\varphi) \\ Y^{0}_{1}(\xi,\varphi) \end{pmatrix} \, . \]
The spherical harmonics through \(L=3\) in terms of the directional cosines are
\[ Y^{0}_{0} = 1 \, , \]
\[ Y^{-1}_{1}=\eta \, , \quad Y^{0}_{1}=\xi \, , \quad Y^{1}_{1}=\mu \]
\[ Y^{-2}_{2} = \sqrt{3}\mu\eta \, , \quad Y^{-1}_{2}=\sqrt{3}\xi\eta \, , \quad Y^{0}_{2}=\frac{1}{2}(3\xi^2-1) \, , \quad Y^{1}_{2}=\sqrt{3}\xi\mu \, , \quad Y^{2}_{2}=\frac{\sqrt{3}}{2}(\mu^2-\eta^2) \, . \]
\[ Y^{-3}_{3} = \sqrt{\frac{5}{8}}\eta(3\mu^2-\eta^2) \, , \quad Y^{-2}_{3} = \sqrt{15}\xi\mu\eta \, , \quad Y^{-1}_{3} = \sqrt{\frac{3}{8}}\eta(5\xi^2-1) \, , \quad Y^{0}_{3} = \frac{1}{2}(5\xi^3-3\xi) \, , \quad \]
\[ Y^{1}_{3} = \sqrt{\frac{3}{8}}\mu(5\xi^2-1) \, , \quad Y^{2}_{3} = \sqrt{\frac{15}{4}}\xi(\mu^2-\eta^2) \, , \quad Y^{3}_{3} = \sqrt{\frac{5}{8}}\mu(\mu^2-3\eta^2) \, . \]
The trigonometric functions, associated Legendre polynomials, and spherical harmonics satisfy the following orthogonality conditions:
\[ \int^{\pi}_{-\pi} d\varphi \mathcal{T}_n (\varphi) \mathcal{T}_{n'}(\varphi) = \pi(1+\delta_{n,0})\delta_{n,n'} \, , \]
\[ \int^{1}_{-1} d\mu P^m_l (\mu) P^{m'}_{l'} = \frac{2(l+m)!}{(2l+1)(l-m)!}\delta_{l,l'} \, , \]
and
\[ \int_{4\pi} d^2\Omega Y^m_l(\mathbf{\Omega})Y^m_{l'}(\mathbf{\Omega}) = \int^{2\pi}_{0} d\phi' \int^{1}_{-1}d\mu' Y^m_l(\theta,\varphi) Y^{m'}_{l'}(\theta,\varphi) = \frac{4\pi}{2l+1} \delta_{l,l'}\delta_{m,m'} \, . \]
Then, angular flux is expanded following
\[ \psi(\mathbf{r},\mathbf{\Omega}) \approx \sum^{L}_{l=0} \frac{2l+1}{4\pi} \sum^{l}_{m=-l} Y^m_l (\mathbf{\Omega}) \phi^m_l(\mathbf{r}) \, , \]
where
\[ \phi^m_l(\mathbf{r}) = \int_{4\pi} d^2\Omega Y^m_l(\mathbf{\Omega}) \psi(\mathbf{r},\mathbf{\Omega}) \, . \]
The additional \(2\pi\) in the expansion comes from the isotropy in the azimuthal angle, multiplied away in 1D (a 1D angular flux is really in units of 1/rad, not 1/steradian).
Again, we note that the zeroth order moment is the angular flux. For an \(L\)-th order expansion, there are \((L+1)^2\) moments.
Note
For 2-D, the moments \(\phi^0_{l>0}\) vanish identically. This is because a 2D problem is defined such that there is no variation in the polar (\(z\)) direction. The moments \(\phi^0_{l>0}\) represent net changes in the \(z\) direction, and so should be eliminated for efficiency. For 2D problems, the number of moments is therefore \((L+1)^2-L \) . This is handled in MomentsToDirections.
It should be noted that the for \(m=0 \), the spherical harmonics as defined reduce to the Legendre polynomials in \(\xi\). Hence, this class can be used for 1D expansions.
Currently, only the spherical harmonics through \(L=3 \) are implemented, though adding capability for arbitrary orders should be straightforward if external libraries are used.
Note
Legendre expansions are typically referred to in terms of the "order", which we have denoted via L. In many mathematics texts, the term "degree" is used instead. Here, both "Legendre order" and "spherical harmonic degree" will refer to the l subscript, while the m subscript represents the "spherical harmonic order".
Refs
Alain Hebert, Applied Reactor Physics, Presses Internationales Polytechnique, Montreal, 2009.
Definition at line 201 of file spherical_harmonics.h.
Member Function Documentation
template<int dim> double Forest::SphericalHarmonics< dim >::Y_lm (const std::vector< int > & lm, const std::vector< double > & omega) static
Calculate \(Y^m_l(\Omega)\) given \(l,m\) and \(\Omega\) .
Parameters
lm Legendre order (or spherical harmonic degree)
omega Direction for evaluation.
Returns
\(Y_l^m(\Omega) \)
Note
This is the only public interface for calculating the spherical harmonics on a particular point.
Todo:
use the macros to enable or disable boost.
Definition at line 28 of file spherical_harmonics.cc.
Referenced by Forest::ExtractBV< dim >::calculate_moments_ass(), Forest::ExtractBV< dim >::calculate_moments_pin(), Forest::MomentsToDirections< dim >::vmult_add(), and Forest::DirectionsToMoments< dim >::vmult_add().
   {
     Assert(false, dealii::ExcMessage("Dimension dim not implemented."));
     return 0.;
   }
template<int dim> double Forest::SphericalHarmonics< dim >::Y_lm (int l, int m, double xi, double varphi) static private
Calculate \(Y^m_l \) given \(\xi\) and \(\varphi\) .
Note
I do not want this function to be called, so it is private.
Parameters
l Legendre order (or spherical harmonic degree)
m Spherical harmonic order
xi direction cosine w/r to z axis
varphi azimuthal angle (as defined from x axis)
Returns
\(Y^m_l(\Omega) \)
Definition at line 138 of file spherical_harmonics.cc.
   {
     Assert(dim == 3, dealii::ExcMessage("Wrong dimension."));
     //Require(xi >= -1.0);
     //Require(xi <= 1.0);
     //Require(varphi >= 0.0);
     //Require(varphi <= Forest::two_pi);
     double sintheta = std::sqrt (1.0 - xi * xi);
     double mu = sintheta * std::cos (varphi);
     double eta = sintheta * std::sin (varphi);
     return get_Y_lm (l, m, mu, eta, xi);
   }
template<int dim> double Forest::SphericalHarmonics< dim >::get_Y_lm (int l, int m, double mu, double eta, double xi) static private
Calculate \(Y^m_l \) given \(\mathbf{\Omega}\).
This private function could be used to interface with external libraries, leaving the rest of the interfaces and their implementations unchanged.
Parameters
l Legendre order (or spherical harmonic degree)
m Spherical harmonic order
mu direction cosine w/r to x axis
eta direction cosine w/r to y axis
xi direction cosine w/r to z axis
Returns
\(Y^m_l(\Omega) \)
Todo:
add proper flags to be used with boost when available
Definition at line 157 of file spherical_harmonics.cc.
   {
     //Require(l >= 0);
     //Require(m <= l);
     //Require(m >= -l);
     //Require(mu >= -1.0);
     //Require(mu <= 1.0);
     //Require(eta >= -1.0);
     //Require(eta <= 1.0);
     //Require(xi >= -1.0);
     //Require(xi <= 1.0);
     /* If the point is not unit norm, it should be pure z coordinate. */
     double unity = mu * mu + eta * eta + xi * xi;
     if (not (std::fabs (1.0 - unity) < 1.0e-5))
       Assert((std::fabs(mu) < 1.e-6) and (std::fabs(eta) < 1.e-6),
           dealii::ExcMessage("If 3d vector is not unit norm, should be 1d."));
     // if (not (std::fabs (1.0 - unity) < 1.0e-5))
     //   Require( (std::fabs(mu) < 1.e-6) && (std::fabs(eta) < 1.e-6) );
     if (true)
     {
       //double phi = std::acos (mu / std::sqrt (1.0 - xi * xi));
       double phi = std::atan2 (eta, mu);
       double theta = std::acos (xi);
       // Normalization so that phi_00 = phi, phi_1m = current components, etc.
       // This leads to a match with definitions given by Hebert.
       double del = (m == 0) ? 1.0 : 2.0;
       double norm = std::pow (-1.0, m)
           * std::sqrt (del * Forest::four_pi / (2. * l + 1.));
       if (m >= 0)
         return norm * boost::math::spherical_harmonic_r (l, m, theta, phi);
       else
         return norm * boost::math::spherical_harmonic_i (l, -m, theta, phi);
     }
     if (l == 0)
       return 1.0;
     else if (l == 1)
     {
       if (m == -1)
         return eta;
       else if (m == 0)
         return xi;
       else if (m == 1)
         return mu;
     }
     else if (l == 2)
     {
       if (m == -2)
         return 1.732050807568877 * mu * eta;
       else if (m == -1)
         return 1.732050807568877 * xi * eta;
       else if (m == 0)
         return 1.5 * xi * xi - 0.5;
       else if (m == 1)
         return 1.732050807568877 * xi * mu;
       else if (m == 2)
         return 0.8660254037844385 * (mu * mu - eta * eta);
     }
     else if (l == 3)
     {
       if (m == -3)
         return 0.7905694150420948 * eta * (3 * mu * mu - eta * eta);
       else if (m == -2)
         return 3.872983346207417 * xi * mu * eta;
       else if (m == -1)
         return 0.6123724356957945 * eta * (5.0 * xi * xi - 1.0);
       else if (m == 0)
         return 2.5 * xi * xi * xi - 1.5 * xi;
       else if (m == 1)
         return 0.6123724356957945 * mu * (5.0 * xi * xi - 1.0);
       else if (m == 2)
         return 1.936491673103708 * xi * (mu * mu - eta * eta);
       else if (m == 3)
         return 0.7905694150420948 * mu * (mu * mu - 3.0 * eta * eta);
     }
     else
     {
 /*#ifdef FOREST_ENABLE_BOOST
       //double phi = std::acos (mu / std::sqrt (1.0 - xi * xi));
       double phi = std::atan2 (eta, mu);
       double theta = std::acos (xi);
       // Normalization so that phi_00 = phi, phi_1m = current components, etc.
       // This leads to a match with definitions given by Hebert.
       double del = (m == 0) ? 1.0 : 2.0;
       double norm = std::pow (-1.0, m) *
           std::sqrt (del * Forest::four_pi / (2.*l+1.));
       if (m >= 0)
       return norm * boost::math::spherical_harmonic_r (l, m, theta, phi);
       else
       return norm * boost::math::spherical_harmonic_i (l, -m, theta, phi);
 #else
       // Degree not implemented.
       //Assert_msg(false, 'Maximum Legendre order is 3. For higher orders, enable Boost.');
       return 0;
 #endif*/
       Assert(false, dealii::ExcMessage("Index not implemented without BOOST."));
     }
     //std::cout << "FOREST_ENABLE_BOOST = " << FOREST_ENABLE_BOOST << std::endl;
     return 0;
   }
template<> double Forest::SphericalHarmonics< 1 >::Y_lm (const std::vector< int > & lm, const std::vector< double > & omega)
Definition at line 37 of file spherical_harmonics.cc.
   {
     /* Check the input. */
     Assert(lm.size() == 2, dealii::ExcMessage("Wrong index size."));
     Assert(omega.size() == 3, dealii::ExcMessage("Wrong Omega dimension."));
     /* Indices for spherical harmonics. */
     const int l = lm[0];
     const int m = 0;
     /* Direction. */
     const double mu = 0.;
     const double eta = 0.;
     const double xi = omega[0];
     /* Evaluation the Spherical harmonic in the required direction. */
     return get_Y_lm (l, m, mu, eta, xi);
   }
template<> double Forest::SphericalHarmonics< 2 >::Y_lm (const std::vector< int > & lm, const std::vector< double > & omega)
Definition at line 56 of file spherical_harmonics.cc.
   {
     /* Check the input. */
     Assert(lm.size() == 2, dealii::ExcMessage("Wrong index size."));
     Assert(omega.size() == 3, dealii::ExcMessage("Wrong Omega dimension."));
     /* Indices for spherical harmonics. */
     const int l = lm[0];
     const int m = lm[1];
     /* Direction. */
     const double mu = omega[0];
     const double eta = omega[1];
     const double xi = std::sqrt(1.0 - mu*mu - eta*eta);
     /* Evaluation the Spherical harmonic in the required direction. */
     return get_Y_lm (l, m, mu, eta, xi);
   }
template<> double Forest::SphericalHarmonics< 3 >::Y_lm (const std::vector< int > & lm, const std::vector< double > & omega)
Definition at line 75 of file spherical_harmonics.cc.
   {
     /* Check the input. */
     Assert(lm.size() == 2, dealii::ExcMessage("Wrong index size."));
     Assert(omega.size() == 3, dealii::ExcMessage("Wrong Omega dimension."));
     /* Indices for spherical harmonics. */
     const int l = lm[0];
     const int m = lm[1];
     /* Direction. */
     const double mu = omega[0];
     const double eta = omega[1];
     const double xi = omega[2];
     /* Evaluation the Spherical harmonic in the required direction. */
     return get_Y_lm (l, m, mu, eta, xi);
   }
The documentation for this class was generated from the following files:
/home/lns/Codes/forest-public/mylib/include/angle/spherical_harmonics.h
/home/lns/Codes/forest-public/mylib/src/angle/spherical_harmonics.cc