FOREST: Forest::InputSettings Class Reference
Forest::InputSettings Class Reference
Container for the settings of the problem.
#include </home/lns/Codes/forest-public/mylib/include/input/input_settings.h>
Public Member Functions
InputSettings ()
InputSettings (const std::string &path_plus_file_plus_ext_)
Initialize the classes member and read the settings.xml file.
void load_xml (const std::string &path, const std::string &filename_no_ext)
Once the property tree is created, extract all the information.
void save_xml (const std::string &path, const std::string &filename_no_ext)
This performs the inverse operation of the load function, printing the information in a file.
void set_files (std::string path, std::string problem_name)
void set_problem (std::string path, std::string problem_name)
std::string get_path_plus_file () const
const std::string & get_path_plus_file_plus_ext () const
const std::string & get_file_geom () const
const std::string & get_file_mat () const
const std::string & get_file_out () const
const std::string & get_file_mesheps () const
const std::string & get_file_meshvtk () const
const std::string & get_file_vtk () const
const std::string & get_file_bcs () const
std::string get_log () const
bool use_transport () const
bool use_dsa () const
std::vector< unsigned int > get_sn_order () const
std::string get_quad_name () const
bool get_matrix_free () const
bool use_power_iteration () const
unsigned int get_n_eigenvalues () const
unsigned int get_n_column_vectors () const
bool use_fission_density () const
std::string get_eig_solver () const
double get_eig_tol () const
unsigned int get_eig_max_it () const
std::string get_mg_solver () const
double get_mg_tol () const
unsigned int get_mg_max_it () const
std::string get_inner_solver () const
double get_inner_tol () const
unsigned int get_inner_max_it () const
unsigned int get_n_ref () const
unsigned int get_fe_degree () const
bool get_homogenize_flag () const
bool get_print_mesh_flag () const
bool get_print_vtk_flag () const
bool get_print_vtk_mat_flag () const
bool get_print_vtk_power_flag () const
bool get_print_vtk_flux_flag () const
bool get_print_ass_bcs_flag () const
bool get_bcs_from_file () const
void set_input_files (const std::string &path, const std::string &filename_no_ext)
void set_problem (const std::string type=std::string("transport"), bool product_quadrature=false, std::string quad="LevelSymType2", std::vector< unsigned int > order={2})
void set_algebra (bool matrix_free, const bool use_fission_density, const std::string eig_solver, const double eig_tol, const unsigned int eig_max_it, const std::string mg_solver, const double mg_tol, const unsigned int mg_max_it, const std::string inner_solver, const double inner_tol, const unsigned int inner_max_it)
void set_fe_settings (unsigned int degree, unsigned int n_ref)
void set_output (const std::vector< bool > &options)
Public Attributes
std::string settings_ext = ".settings.xml"
Extension used.
std::string path_plus_file_plus_ext
Full path input file.
std::string path
Path for the problem.
std::string problem_name
Problem name provided.
InputFiles files
Settings for the files.
InputProblem problem
Settings for the problem to be solved.
InputAlgebra algebra
Settings for the algebra.
InputFESettings fe_settings
Settings for finite elements.
InputOutput output
Settings for the output.
Detailed Description
Container for the settings of the problem.
Definition at line 248 of file input_settings.h.
Constructor & Destructor Documentation
Forest::InputSettings::InputSettings ()
Definition at line 467 of file input_settings.cc.
         : settings_ext(".settings.xml"),
           files (),
         problem (),
         algebra (),
         fe_settings (),
         output ()
   {
   }
Forest::InputSettings::InputSettings (const std::string & path_plus_file_plus_ext_)
Initialize the classes member and read the settings.xml file.
All the work is done inside the load and save functions before.
Parameters
path_plus_file_plus_ext_
Definition at line 477 of file input_settings.cc.
       : settings_ext(std::string(".settings.xml")),
         path_plus_file_plus_ext (path_plus_file_plus_ext_),
         path (Forest::get_path (path_plus_file_plus_ext)),
         problem_name (Forest::get_file_plus_ext (path_plus_file_plus_ext)),
         files (),
         problem (),
         algebra (),
         fe_settings (),
         output ()
   {
     this->load_xml (path, problem_name);
     // this->save (path, problem_name);
   }
Member Function Documentation
void Forest::InputSettings::load_xml (const std::string & path, const std::string & filename_no_ext)
Once the property tree is created, extract all the information.
Parameters
path
filename_no_ext
Definition at line 493 of file input_settings.cc.
Referenced by InputSettings().
   {
     // Create empty property tree object
     using boost::property_tree::ptree;
     ptree pt;
     // Load XML file and put its contents in property tree.
     // No namespace qualification is needed, because of Koenig
     // lookup on the second argument. If reading fails, exception
     // is thrown.
     read_xml (path_ + problem_name_ + settings_ext, pt,
         boost::property_tree::xml_parser::trim_whitespace);
     files.read_xml (pt, path_, problem_name_);
     //coarsening_bcs.read_xml (pt, path_, problem_name_);
     output.read_xml (pt, path_, problem_name_);
     problem.read_xml (pt, path_, problem_name_);
     algebra.read_xml (pt, path_, problem_name_);
     fe_settings.read_xml (pt, path_, problem_name_);
   }
void Forest::InputSettings::save_xml (const std::string & path, const std::string & filename_no_ext)
This performs the inverse operation of the load function, printing the information in a file.
Parameters
path
filename_no_ext
Definition at line 517 of file input_settings.cc.
   {
     // Create empty property tree object
     using boost::property_tree::ptree;
     ptree pt;
     pt.add ("settings", "");
     pt.add ("settings.<xmlcomment>",
         " \n \
       Here we define the different materials associated to the \n \
       material id specified when defining the geometry");
     // the rest
     files.write (pt);
     files.write (pt);
     output.write (pt);
     problem.write (pt);
     algebra.write (pt);
     fe_settings.write (pt);
     // Write property tree to XML file (\t is a tabulator)
     write_xml (path_ + "out_" + problem_name_ + settings_ext, pt,
         std::locale (), xml_writer_settings('\t', 1));
   }
void Forest::InputSettings::set_files (std::string path, std::string problem_name) inline
Definition at line 299 of file input_settings.h.
Referenced by Forest::Input::set_input_files().
     {
       files.set (path, problem_name);
     }
void Forest::InputSettings::set_problem (std::string path, std::string problem_name) inline
Definition at line 306 of file input_settings.h.
Referenced by Forest::Input::set_problem().
     {
       files.set (path, problem_name);
     }
std::string Forest::InputSettings::get_path_plus_file () const inline
Definition at line 313 of file input_settings.h.
Referenced by Forest::HomData< dim >::HomData().
     {
       return path + problem_name;
     }
const std::string& Forest::InputSettings::get_path_plus_file_plus_ext () const inline
Definition at line 319 of file input_settings.h.
     {
       return path_plus_file_plus_ext;
     }
const std::string& Forest::InputSettings::get_file_geom () const inline
Definition at line 325 of file input_settings.h.
     {
       return files.geom;
     }
const std::string& Forest::InputSettings::get_file_mat () const inline
Definition at line 331 of file input_settings.h.
     {
       return files.mat;
     }
const std::string& Forest::InputSettings::get_file_out () const inline
Definition at line 337 of file input_settings.h.
Referenced by Forest::PostProcessing< dim >::PostProcessing().
     {
       return files.out;
     }
const std::string& Forest::InputSettings::get_file_mesheps () const inline
Definition at line 343 of file input_settings.h.
Referenced by Forest::ProbGeom< dim >::ProbGeom().
     {
       return files.mesheps;
     }
const std::string& Forest::InputSettings::get_file_meshvtk () const inline
Definition at line 349 of file input_settings.h.
Referenced by Forest::ProbGeom< dim >::ProbGeom().
     {
       return files.meshvtk;
     }
const std::string& Forest::InputSettings::get_file_vtk () const inline
Definition at line 355 of file input_settings.h.
Referenced by Forest::PostProcessing< dim >::print_vtk().
     {
       return files.vtk;
     }
const std::string& Forest::InputSettings::get_file_bcs () const inline
Definition at line 361 of file input_settings.h.
     {
       return files.bcs;
     }
std::string Forest::InputSettings::get_log () const inline
Definition at line 367 of file input_settings.h.
     {
       return path + files.log;
     }
bool Forest::InputSettings::use_transport () const inline
Returns
Definition at line 403 of file input_settings.h.
     {
       return problem.m_use_transport;
     }
bool Forest::InputSettings::use_dsa () const inline
Definition at line 409 of file input_settings.h.
     {
       return problem.m_use_dsa;
     }
std::vector<unsigned int> Forest::InputSettings::get_sn_order () const inline
Definition at line 415 of file input_settings.h.
     {
       return problem.m_order;
     }
std::string Forest::InputSettings::get_quad_name () const inline
Definition at line 421 of file input_settings.h.
     {
       return problem.m_quad_name;
     }
bool Forest::InputSettings::get_matrix_free () const inline
Definition at line 427 of file input_settings.h.
     {
       return algebra.m_matrix_free;
     }
bool Forest::InputSettings::use_power_iteration () const inline
Definition at line 433 of file input_settings.h.
     {
       return algebra.m_use_power_iteration;
     }
unsigned int Forest::InputSettings::get_n_eigenvalues () const inline
Definition at line 439 of file input_settings.h.
     {
       return algebra.m_n_eigenvalues;
     }
unsigned int Forest::InputSettings::get_n_column_vectors () const inline
Definition at line 445 of file input_settings.h.
     {
       return algebra.m_n_cv;
     }
bool Forest::InputSettings::use_fission_density () const inline
Definition at line 451 of file input_settings.h.
Referenced by Forest::EigenProbFactory< dim >::New().
     {
       return algebra.m_use_fission_density;
     }
std::string Forest::InputSettings::get_eig_solver () const inline
Definition at line 457 of file input_settings.h.
     {
       return algebra.m_eig_solver;
     }
double Forest::InputSettings::get_eig_tol () const inline
Definition at line 463 of file input_settings.h.
     {
       return algebra.m_eig_tol;
     }
unsigned int Forest::InputSettings::get_eig_max_it () const inline
Definition at line 469 of file input_settings.h.
     {
       return algebra.m_eig_max_it;
     }
std::string Forest::InputSettings::get_mg_solver () const inline
Definition at line 475 of file input_settings.h.
     {
       return algebra.m_mg_solver;
     }
double Forest::InputSettings::get_mg_tol () const inline
Definition at line 481 of file input_settings.h.
     {
       return algebra.m_mg_tol;
     }
unsigned int Forest::InputSettings::get_mg_max_it () const inline
Definition at line 487 of file input_settings.h.
     {
       return algebra.m_mg_max_it;
     }
std::string Forest::InputSettings::get_inner_solver () const inline
Definition at line 493 of file input_settings.h.
     {
       return algebra.m_inner_solver;
     }
double Forest::InputSettings::get_inner_tol () const inline
Definition at line 499 of file input_settings.h.
     {
       return algebra.m_inner_tol;
     }
unsigned int Forest::InputSettings::get_inner_max_it () const inline
Definition at line 505 of file input_settings.h.
     {
       return algebra.m_inner_max_it;
     }
unsigned int Forest::InputSettings::get_n_ref () const inline
Definition at line 511 of file input_settings.h.
Referenced by Forest::ProbGeom< dim >::ProbGeom().
     {
       return fe_settings.m_n_ref;
     }
unsigned int Forest::InputSettings::get_fe_degree () const inline
Definition at line 517 of file input_settings.h.
Referenced by Forest::Homogenization< dim >::cell_weights().
     {
       return fe_settings.m_degree;
     }
bool Forest::InputSettings::get_homogenize_flag () const inline
Definition at line 523 of file input_settings.h.
     {
       return output.homogenize;
     }
bool Forest::InputSettings::get_print_mesh_flag () const inline
Definition at line 529 of file input_settings.h.
Referenced by Forest::ProbGeom< dim >::ProbGeom().
     {
       return output.print_mesh;
     }
bool Forest::InputSettings::get_print_vtk_flag () const inline
Definition at line 535 of file input_settings.h.
     {
       return (output.vtk_mat or output.vtk_power or output.vtk_flux);
     }
bool Forest::InputSettings::get_print_vtk_mat_flag () const inline
Definition at line 541 of file input_settings.h.
     {
       return output.vtk_mat;
     }
bool Forest::InputSettings::get_print_vtk_power_flag () const inline
Definition at line 547 of file input_settings.h.
     {
       return output.vtk_power;
     }
bool Forest::InputSettings::get_print_vtk_flux_flag () const inline
Definition at line 553 of file input_settings.h.
     {
       return output.vtk_flux;
     }
bool Forest::InputSettings::get_print_ass_bcs_flag () const inline
Definition at line 559 of file input_settings.h.
     {
       return output.ass_bcs;
     }
bool Forest::InputSettings::get_bcs_from_file () const inline
Definition at line 565 of file input_settings.h.
     {
       return files.bcs_from_file;
     }
void Forest::InputSettings::set_input_files (const std::string & path, const std::string & filename_no_ext) inline
Definition at line 571 of file input_settings.h.
     {
       files.set (path, filename_no_ext);
     }
void Forest::InputSettings::set_problem (const std::string type = std::string ("transport"), bool product_quadrature = false, std::string quad = "LevelSymType2", std::vector< unsigned int > order = { 2 }) inline
Definition at line 578 of file input_settings.h.
                  { 2 })
     {
       problem.set (type, product_quadrature, quad, order);
     }
void Forest::InputSettings::set_algebra (bool matrix_free, const bool use_fission_density, const std::string eig_solver, const double eig_tol, const unsigned int eig_max_it, const std::string mg_solver, const double mg_tol, const unsigned int mg_max_it, const std::string inner_solver, const double inner_tol, const unsigned int inner_max_it) inline
Definition at line 588 of file input_settings.h.
Referenced by Forest::Input::set_algebra().
     {
       algebra.set (matrix_free, use_fission_density,
           eig_solver, eig_tol, eig_max_it,
           mg_solver, mg_tol, mg_max_it,
           inner_solver, inner_tol, inner_max_it);
     }
void Forest::InputSettings::set_fe_settings (unsigned int degree, unsigned int n_ref) inline
Definition at line 607 of file input_settings.h.
Referenced by Forest::Input::set_fe_settings().
     {
       fe_settings.set (degree, n_ref);
     }
void Forest::InputSettings::set_output (const std::vector< bool > & options) inline
Definition at line 614 of file input_settings.h.
Referenced by Forest::Input::set_output().
     {
       output.set (options);
     }
Member Data Documentation
std::string Forest::InputSettings::settings_ext = ".settings.xml"
Extension used.
Definition at line 284 of file input_settings.h.
Referenced by load_xml(), and save_xml().
std::string Forest::InputSettings::path_plus_file_plus_ext
Full path input file.
Definition at line 285 of file input_settings.h.
std::string Forest::InputSettings::path
Path for the problem.
Definition at line 286 of file input_settings.h.
Referenced by InputSettings().
std::string Forest::InputSettings::problem_name
Problem name provided.
Definition at line 287 of file input_settings.h.
Referenced by InputSettings().
InputFiles Forest::InputSettings::files
Settings for the files.
Definition at line 289 of file input_settings.h.
Referenced by load_xml(), and save_xml().
InputProblem Forest::InputSettings::problem
Settings for the problem to be solved.
Definition at line 291 of file input_settings.h.
Referenced by load_xml(), and save_xml().
InputAlgebra Forest::InputSettings::algebra
Settings for the algebra.
Definition at line 292 of file input_settings.h.
Referenced by load_xml(), and save_xml().
InputFESettings Forest::InputSettings::fe_settings
Settings for finite elements.
Definition at line 293 of file input_settings.h.
Referenced by load_xml(), and save_xml().
InputOutput Forest::InputSettings::output
Settings for the output.
Definition at line 294 of file input_settings.h.
Referenced by load_xml(), and save_xml().
The documentation for this class was generated from the following files:
/home/lns/Codes/forest-public/mylib/include/input/input_settings.h
/home/lns/Codes/forest-public/mylib/src/input/input_settings.cc