FOREST: Forest::CmdOption Class Reference
Forest::CmdOption Class Reference
ForestUtils
We use this class to parse the command line arguments.
#include </home/lns/Codes/forest-public/mylib/include/utils/cmdoption.h>
Public Member Functions
CmdOption ()
Empty constructor.
bool exists (char **begin, char **end, const std::string &option)
Check if option exists in the command line arguments.
char * get (char **begin, char **end, const std::string &option)
Get the option from the command line, and return it.
Detailed Description
We use this class to parse the command line arguments.
The usage is as follows:
int main (int argc, char **argv)
{
  parse_args.exists (argv, argv + argc, "-f")
  Forest::CmdOption parse_args;
  assert(parse_args.exists (argv, argv + argc, "-f"));
  std::string input_file = parse_args.get (argv, argv + argc, "-f");
  return 0;
}
Note
Actually, the main point is specifying the input file, and getting the path. Information about the function can be found here: stackoverflow
Also boost can be very useful, especially when parsing parameter files.
Definition at line 39 of file cmdoption.h.
Constructor & Destructor Documentation
Forest::CmdOption::CmdOption () inline
Empty constructor.
Definition at line 45 of file cmdoption.h.
     {
     }
Member Function Documentation
bool Forest::CmdOption::exists (char ** begin, char ** end, const std::string & option)
Check if option exists in the command line arguments.
Parameters
begin
end
option
Returns
true if the option exists and false otherwise.
Definition at line 17 of file cmdoption.cc.
Referenced by CmdOption(), and Forest::start_forest().
   {
     return std::find (begin, end, option) != end;
   }
char * Forest::CmdOption::get (char ** begin, char ** end, const std::string & option)
Get the option from the command line, and return it.
Parameters
begin
end
option
Returns
The argument associated to the option specified
Definition at line 25 of file cmdoption.cc.
Referenced by Forest::start_forest().
   {
     char ** itr = std::find (begin, end, option);
     if (itr != end && ++itr != end)
     {
       return *itr;
     }
     return 0;
   }
The documentation for this class was generated from the following files:
/home/lns/Codes/forest-public/mylib/include/utils/cmdoption.h
/home/lns/Codes/forest-public/mylib/src/utils/cmdoption.cc