FOREST: Forest::RealCore< dim > Class Template Reference
Forest::RealCore< dim > Class Template Reference
this name is provisional. Something better can be better.
#include </home/lns/Codes/forest-public/mylib/include/geometry/real_core.h>
Public Member Functions
RealCore (const Input &input_data_, const double correction_factor=1.0)
Constructor using the input data.
void build_data ()
void build_mesh (Triangulation< dim, dim > &tria)
void set_correction_factor (const unsigned int correction_factor)
unsigned int get_n_assemblies () const
unsigned int get_n_pins () const
std::vector< unsigned int > get_pins_to_assembly () const
std::vector< unsigned int > get_pins_per_assembly () const
unsigned int get_n_pins_in_assembly (const unsigned int ass_no) const
Public Attributes
unsigned int m_empty_assembly = static_cast<unsigned int> (-1)
const Input & m_input_data
Forest::Core m_core
Point< dim > m_origin
std::vector< double > m_size
size is a vector with the size (sum?? of all the pin sizes) of the assembly
std::vector< RealAssembly< dim > > m_real_assemblies
std::vector< RealPin< dim > > m_real_pins
bool m_ready_to_build_mesh
double m_correction_factor
unsigned int m_n_assemblies
unsigned int m_n_pins
std::vector< unsigned int > pins_to_assembly
std::vector< unsigned int > pins_per_assembly
Private Member Functions
void build_assemblies ()
void build_additional_data ()
Detailed Description
template<int dim>
class Forest::RealCore< dim >
this name is provisional. Something better can be better.
Definition at line 23 of file real_core.h.
Constructor & Destructor Documentation
template<int dim> Forest::RealCore< dim >::RealCore (const Input & input_data_, const double correction_factor = 1.0)
Constructor using the input data.
Parameters
input_data_
correction_factor
Definition at line 19 of file real_core.cc.
       : m_input_data (input_data),
         m_core (input_data.mp_geom.m_core),
         m_origin (Point<dim> ()),
         m_ready_to_build_mesh (false),
         m_correction_factor (correction_factor),
         m_n_assemblies (0),
         m_n_pins (0)
   {
     this->build_data ();
   }
Member Function Documentation
template<int dim> void Forest::RealCore< dim >::build_data ()
Definition at line 34 of file real_core.cc.
Referenced by Forest::RealCore< dim >::RealCore().
   {
     this->build_assemblies ();
     this->build_additional_data ();
   }
template<int dim> void Forest::RealCore< dim >::build_mesh (Triangulation< dim, dim > & tria)
Parameters
tria
Definition at line 139 of file real_core.cc.
Referenced by Forest::ProbGeom< dim >::ProbGeom().
   {
     Assert(m_n_assemblies == m_real_assemblies.size (),
         ExcMessage("Wrong number of real assemblies."));
     std::vector<Triangulation<dim, dim> > m_tria_latt (m_n_assemblies);
     for (unsigned int i = 0; i < m_real_assemblies.size (); ++i)
     {
       m_real_assemblies[i].build_mesh (m_real_pins, m_tria_latt[i]);
     }
     GridGenerator::merge_triangulations (m_tria_latt, tria);
   }
template<int dim> void Forest::RealCore< dim >::set_correction_factor (const unsigned int correction_factor) inline
Todo:
Study if we needed.
If not remove it
Parameters
correction_factor
Definition at line 55 of file real_core.h.
     {
       m_correction_factor = correction_factor;
     }
template<int dim> unsigned int Forest::RealCore< dim >::get_n_assemblies () const inline
Returns
Definition at line 65 of file real_core.h.
Referenced by Forest::ProbGeom< dim >::ProbGeom().
     {
       return m_n_assemblies;
     }
template<int dim> unsigned int Forest::RealCore< dim >::get_n_pins () const inline
Returns
Definition at line 75 of file real_core.h.
Referenced by Forest::RealCore< dim >::build_additional_data(), and Forest::ProbGeom< dim >::ProbGeom().
     {
       return m_n_pins;
     }
template<int dim> std::vector<unsigned int> Forest::RealCore< dim >::get_pins_to_assembly () const inline
Returns
Definition at line 85 of file real_core.h.
Referenced by Forest::ProbGeom< dim >::ProbGeom().
     {
       return pins_to_assembly;
     }
template<int dim> std::vector<unsigned int> Forest::RealCore< dim >::get_pins_per_assembly () const inline
Returns
Definition at line 95 of file real_core.h.
Referenced by Forest::ProbGeom< dim >::ProbGeom().
     {
       return pins_per_assembly;
     }
template<int dim> unsigned int Forest::RealCore< dim >::get_n_pins_in_assembly (const unsigned int ass_no) const inline
Parameters
ass_no
Returns
Definition at line 106 of file real_core.h.
     {
       return pins_per_assembly[ass_no];
     }
template<int dim> void Forest::RealCore< dim >::build_assemblies () private
Definition at line 42 of file real_core.cc.
Referenced by Forest::RealCore< dim >::build_data().
   {
     // some cleaning to play safe
     m_real_pins.clear ();
     // prepare vector with the y component of the origin
     std::vector<double> z_origin (m_core.m_n_nodes[2]);
     z_origin[0] = 0.0;
     for (unsigned int k = 1; k < m_core.m_n_nodes[2]; ++k)
     {
       z_origin[k] = z_origin[k - 1] + m_core.m_length[2][k - 1];
     }
     // prepare vector with the y component of the origin
     std::vector<double> y_origin (m_core.m_n_nodes[1]);
     y_origin[0] = 0.0;
     for (unsigned int j = 1; j < m_core.m_n_nodes[1]; ++j)
     {
       y_origin[j] = y_origin[j - 1] + m_core.m_length[1][j - 1];
     }
     // prepare vector with the x component of the origin
     std::vector<double> x_origin (m_core.m_n_nodes[0]);
     x_origin[0] = 0.0;
     for (unsigned int i = 1; i < m_core.m_n_nodes[0]; ++i)
     {
       x_origin[i] = x_origin[i - 1] + m_core.m_length[0][i - 1];
     }
     // fill the vector of assemblies with the data of each assembly
     for (unsigned int j = 0; j < m_core.m_n_nodes[1]; ++j)
     {
       for (unsigned int i = 0; i < m_core.m_n_nodes[0]; ++i)
       {
         if (m_core.m_indices[0][j][i] != m_empty_assembly)
         {
           RealAssembly<dim> real_assembly;
           unsigned int ind = m_core.m_indices[0][j][i];
           unsigned int comp_ind = m_core.m_components[ind];
           const Lattice & lattice = m_input_data.mp_geom.m_lattices.at(comp_ind);
           Point<dim> latt_origin (
               new_point<dim> (x_origin[i], y_origin[j], 0.0));
           real_assembly.init (lattice, latt_origin, m_correction_factor);
           // this is to plot the information of the particular assembly
           //real_assembly.info ();
           const std::map<unsigned int, Pin> & pins = m_input_data.mp_geom.m_pins;
           real_assembly.build_data (pins, m_real_pins);
           m_real_assemblies.push_back (real_assembly);
           /*
            unsigned int non_empty_pins = data_pins.size ();
            std::vector<unsigned int> pins_this_latt (non_empty_pins,
            map_latt_index);
            pins_to_assembly.insert (pins_to_assembly.end (),
            pins_this_latt.begin (), pins_this_latt.end ());
            */
         } //if
       }
     }
     m_ready_to_build_mesh = true;
   }
template<int dim> void Forest::RealCore< dim >::build_additional_data () private
Definition at line 111 of file real_core.cc.
Referenced by Forest::RealCore< dim >::build_data().
   {
     m_n_assemblies = m_real_assemblies.size ();
     m_n_pins = 0;
     for (unsigned int i = 0; i < m_real_assemblies.size (); i++)
     {
       m_n_pins += m_real_assemblies[i].get_n_pins ();
     }
     pins_per_assembly.clear ();
     for (unsigned int i = 0; i < m_real_assemblies.size (); i++)
     {
       pins_per_assembly.push_back (m_real_assemblies[i].get_n_pins ());
     }
     pins_to_assembly.clear ();
     for (unsigned int i = 0; i < m_real_assemblies.size (); i++)
     {
       for (unsigned int j = 0; j < m_real_assemblies[i].get_n_pins (); j++)
       {
         pins_to_assembly.push_back (i);
       }
     }
   }
Member Data Documentation
template<int dim> unsigned int Forest::RealCore< dim >::m_empty_assembly = static_cast<unsigned int> (-1)
Definition at line 27 of file real_core.h.
Referenced by Forest::RealCore< dim >::build_assemblies().
template<int dim> const Input& Forest::RealCore< dim >::m_input_data
Todo:
I should change this to private
Definition at line 126 of file real_core.h.
Referenced by Forest::RealCore< dim >::build_assemblies().
template<int dim> Forest::Core Forest::RealCore< dim >::m_core
Definition at line 128 of file real_core.h.
Referenced by Forest::RealCore< dim >::build_assemblies().
template<int dim> Point<dim> Forest::RealCore< dim >::m_origin
Definition at line 130 of file real_core.h.
template<int dim> std::vector<double> Forest::RealCore< dim >::m_size
size is a vector with the size (sum?? of all the pin sizes) of the assembly
Definition at line 136 of file real_core.h.
template<int dim> std::vector<RealAssembly<dim> > Forest::RealCore< dim >::m_real_assemblies
Definition at line 138 of file real_core.h.
Referenced by Forest::RealCore< dim >::build_additional_data(), Forest::RealCore< dim >::build_assemblies(), and Forest::RealCore< dim >::build_mesh().
template<int dim> std::vector<RealPin<dim> > Forest::RealCore< dim >::m_real_pins
Definition at line 139 of file real_core.h.
Referenced by Forest::RealCore< dim >::build_assemblies(), Forest::RealCore< dim >::build_mesh(), and Forest::ProbGeom< dim >::ProbGeom().
template<int dim> bool Forest::RealCore< dim >::m_ready_to_build_mesh
Definition at line 141 of file real_core.h.
Referenced by Forest::RealCore< dim >::build_assemblies().
template<int dim> double Forest::RealCore< dim >::m_correction_factor
Definition at line 142 of file real_core.h.
Referenced by Forest::RealCore< dim >::build_assemblies().
template<int dim> unsigned int Forest::RealCore< dim >::m_n_assemblies
Definition at line 144 of file real_core.h.
Referenced by Forest::RealCore< dim >::build_additional_data(), and Forest::RealCore< dim >::build_mesh().
template<int dim> unsigned int Forest::RealCore< dim >::m_n_pins
Definition at line 145 of file real_core.h.
Referenced by Forest::RealCore< dim >::build_additional_data().
template<int dim> std::vector<unsigned int> Forest::RealCore< dim >::pins_to_assembly
Definition at line 147 of file real_core.h.
Referenced by Forest::RealCore< dim >::build_additional_data().
template<int dim> std::vector<unsigned int> Forest::RealCore< dim >::pins_per_assembly
Definition at line 148 of file real_core.h.
Referenced by Forest::RealCore< dim >::build_additional_data().
The documentation for this class was generated from the following files:
/home/lns/Codes/forest-public/mylib/include/geometry/real_core.h
/home/lns/Codes/forest-public/mylib/src/geometry/real_core.cc