FOREST: Forest::FissionSource< dim > Class Template Reference
Forest::FissionSource< dim > Class Template Reference abstract
ForestNeutronics
Fission Source operator, base class.
#include </home/lns/Codes/forest-public/mylib/include/algebra/eq_diffusion.h>
Public Member Functions
virtual ~FissionSource ()
Virtual destructor for this class.
virtual bool is_matrix_free ()=0
True when the operator is matrix free, false otherwise.
virtual void vmult (SnVector &source, const SnVector &phi)=0
Apply the fission operator to phi and store the result in source.
virtual void vmult_add (SnVector &source, const SnVector &phi)=0
Apply the fission operator to phi and add the result to source.
virtual double memory_consumption () const =0
The memory required by the elements of the class.
Detailed Description
template<int dim>
class Forest::FissionSource< dim >
Fission Source operator, base class.
Defines the isotropic fission operator to be applied to a flux vector
\begin{align*} Q(\mathbf{r},E,t) = \frac{\chi(E)}{4\pi}\int_{0}^{\infty}\nu(E^\prime)\Sigma_{f}(\mathbf{r},E^{\prime},t) \Phi(\mathbf{r},E^{\prime},t) dE^{\prime} \end{align*}
We prepare different functions to use the fission source operator in a matrix-free fashion, allowing to work with a single energy group
\begin{align*} Q_{g}(\mathbf{r},t) = \frac{\chi_{g}}{4\pi}\sum_{h \in G}\nu_{h}\Sigma_{f,h}(\mathbf{r},t) \Phi_{h}(\mathbf{r},t) \end{align*}
Remarks
This class builds the matrix if requested, but also allows matrix-free application of the fission source operator, both through the same call to vmult or vmult_add
Todo:
update the documentation
Definition at line 23 of file eq_diffusion.h.
Constructor & Destructor Documentation
template<int dim> virtual Forest::FissionSource< dim >::~FissionSource () inline virtual
Virtual destructor for this class.
Definition at line 49 of file fission_source.h.
     {
     };
Member Function Documentation
template<int dim> virtual bool Forest::FissionSource< dim >::is_matrix_free () pure virtual
True when the operator is matrix free, false otherwise.
Implemented in Forest::FissionSourceMatrixBuilt< dim >, and Forest::FissionSourceMatrixFree< dim >.
Referenced by Forest::FissionSource< dim >::~FissionSource().
template<int dim> virtual void Forest::FissionSource< dim >::vmult (SnVector & source, const SnVector & phi) pure virtual
Apply the fission operator to phi and store the result in source.
Parameters
source
phi
Implemented in Forest::FissionSourceMatrixBuilt< dim >, and Forest::FissionSourceMatrixFree< dim >.
Referenced by Forest::FissionSource< dim >::~FissionSource().
template<int dim> virtual void Forest::FissionSource< dim >::vmult_add (SnVector & source, const SnVector & phi) pure virtual
Apply the fission operator to phi and add the result to source.
Parameters
source
phi
Implemented in Forest::FissionSourceMatrixBuilt< dim >, and Forest::FissionSourceMatrixFree< dim >.
Referenced by Forest::FissionSource< dim >::~FissionSource().
template<int dim> virtual double Forest::FissionSource< dim >::memory_consumption () const pure virtual
The memory required by the elements of the class.
Returns
Memory consumption of object
Implemented in Forest::FissionSourceMatrixBuilt< dim >, and Forest::FissionSourceMatrixFree< dim >.
Referenced by Forest::FissionSource< dim >::~FissionSource().
The documentation for this class was generated from the following files:
/home/lns/Codes/forest-public/mylib/include/algebra/eq_diffusion.h
/home/lns/Codes/forest-public/mylib/include/neutronics/fission_source.h