FOREST: Forest::FissionSpectrum< dim > Class Template Reference
Forest::FissionSpectrum< dim > Class Template Reference abstract
ForestNeutronics
Fission Spectrum operator \(\chi \).
#include </home/lns/Codes/forest-public/mylib/include/algebra/eq_diffusion.h>
Public Member Functions
virtual ~FissionSpectrum ()
Virtual destructor.
virtual bool is_matrix_free ()=0
True when the operator is matrix free, false otherwise.
virtual void vmult (SnVector &source, const SnVector &phi)=0
Apply the fission operator to phi and store the result in source.
virtual void vmult_add (SnVector &source, const SnVector &phi)=0
Apply the fission operator to phi and add the result to source.
virtual double memory_consumption () const =0
The memory required by the elements of the class.
Detailed Description
template<int dim>
class Forest::FissionSpectrum< dim >
Fission Spectrum operator \(\chi \).
Remarks
This class builds the matrix if requested, but also allows matrix-free application of the fission source operator, both through the same call to vmult or vmult_add
Todo:
update the documentation
Definition at line 24 of file eq_diffusion.h.
Constructor & Destructor Documentation
template<int dim> virtual Forest::FissionSpectrum< dim >::~FissionSpectrum () inline virtual
Virtual destructor.
Definition at line 33 of file fission_spectrum.h.
     {
     }
Member Function Documentation
template<int dim> virtual bool Forest::FissionSpectrum< dim >::is_matrix_free () pure virtual
True when the operator is matrix free, false otherwise.
Implemented in Forest::FissionSpectrumMatrixBuilt< dim >, and Forest::FissionSpectrumMatrixFree< dim >.
Referenced by Forest::FissionSpectrum< dim >::~FissionSpectrum().
template<int dim> virtual void Forest::FissionSpectrum< dim >::vmult (SnVector & source, const SnVector & phi) pure virtual
Apply the fission operator to phi and store the result in source.
Parameters
source
phi
Implemented in Forest::FissionSpectrumMatrixBuilt< dim >, and Forest::FissionSpectrumMatrixFree< dim >.
Referenced by Forest::FissionSpectrum< dim >::~FissionSpectrum().
template<int dim> virtual void Forest::FissionSpectrum< dim >::vmult_add (SnVector & source, const SnVector & phi) pure virtual
Apply the fission operator to phi and add the result to source.
Parameters
source
phi
Implemented in Forest::FissionSpectrumMatrixBuilt< dim >, and Forest::FissionSpectrumMatrixFree< dim >.
Referenced by Forest::FissionSpectrum< dim >::~FissionSpectrum().
template<int dim> virtual double Forest::FissionSpectrum< dim >::memory_consumption () const pure virtual
The memory required by the elements of the class.
Returns
Memory consumption of object
Implemented in Forest::FissionSpectrumMatrixBuilt< dim >, and Forest::FissionSpectrumMatrixFree< dim >.
Referenced by Forest::FissionSpectrum< dim >::~FissionSpectrum().
The documentation for this class was generated from the following files:
/home/lns/Codes/forest-public/mylib/include/algebra/eq_diffusion.h
/home/lns/Codes/forest-public/mylib/include/neutronics/fission_spectrum.h