FOREST: Forest::SnVector Class Reference
Forest::SnVector Class Reference
ForestAlgebra
A vector class used in Forest.
#include </home/lns/Codes/forest-public/mylib/include/algebra/sn_vector.h>
Public Types
typedef ForestVector< double > BaseClass
typedef double value_type
Public Member Functions
SnVector ()
Empty constructor.
SnVector (const unsigned int n_groups, const unsigned int n_ord, const unsigned int n_elem)
Standard constructor.
SnVector (const unsigned int n_groups, const std::vector< unsigned int > &block_sizes)
Standard constructor.
void reinit (const unsigned int n_groups, const unsigned int n_ord, const unsigned int n_elem, const bool leave_elements_uninitialized=false)
Reinitialize the vector.
unsigned int get_n_groups () const
Number of groups defining the first dimension.
const std::vector< unsigned int > & get_block_sizes () const
Number of groups defining the first dimension.
void reinit (const unsigned int n_multi_blocks, const std::vector< unsigned int > &block_sizes, const bool leave_elements_uninitialized=false)
Reinitialize the vector.
void reinit (const ForestVector< double > &v, bool leave_elements_uninitialized=false)
resize the vector.
double operator* (const ForestVector< double > &v) const
Scalar product of this vector times vector v.
void add (const ForestVector< double > &x)
Addition of vectors.
void add (const doublea, const ForestVector< double > &x)
Addition of scaled vector.
void sadd (const doublea, const doubleb, const ForestVector< double > &x)
Scaling and simple addition.
void equ (const doublea, const ForestVector< double > &x)
Assignment.
ForestVector< double > & operator*= (const doublea)
Scale the elements of the vector by a fixed value.
void swap (ForestVector< double > &v)
Swap the content of this vector with the content of vector v.
double l2_norm () const
Return the l2 norm of the vector.
double add_and_dot (const doublea, const ForestVector< double > &V, const ForestVector< double > &W)
Performs a combined operation of a vector addition and a subsequent inner product, returning the value of the inner product.
std::size_t memory_consumption () const
memory_consumption.
unsigned int size0 () const
Number of groups defining the first dimension.
const std::vector< unsigned int > & size1 () const
Number of directions defining the second dimension.
Protected Attributes
bool m_initialized
False when called with empty constructor, true otherwise.
unsigned int m_n_multi_blocks
Number of multi-blocks in the current Vector.
std::vector< unsigned int > m_block_sizes
Number of dofs each energy group.
std::vector< BlockVector< double > > m_data
data
Detailed Description
A vector class used in Forest.
This vector is used to hide some complexity. This vector considers all the energy groups, and inside each energy group it contains the scalar flux and the boundary conditions for each direction. Then, we have to use it in different scenarios.
First, we have to use it in a Krylov method as any other vector, so the scaling functions, norms, and so on are defined for the whole vector in a standard way way.
Then we have to perform other operation only over the part corresponding to the scalar flux, not to the boundary values. For this, we have added the following constants:
n_lmom: number of Legendre moments to define the flux
n_bv: number of angles for which there is an contribution from reflective boundary conditions.
Definition at line 43 of file sn_vector.h.
Member Typedef Documentation
typedef ForestVector<double> Forest::SnVector::BaseClass
Definition at line 46 of file sn_vector.h.
typedef double Forest::SnVector::value_type
Definition at line 218 of file sn_vector.h.
Constructor & Destructor Documentation
Forest::SnVector::SnVector ()
Empty constructor.
This is necessary when we want to create the object without specifying the dimensions. This should be initialize later.
Definition at line 16 of file sn_vector.cc.
       : ForestVector<double> ()
   {
   }
Forest::SnVector::SnVector (const unsigned int n_groups, const unsigned int n_ord, const unsigned int n_elem)
Standard constructor.
Creates the object and allocate the necessary space.
Parameters
n_groups
n_ord
n_elem
Definition at line 21 of file sn_vector.cc.
       : ForestVector<double> (n_groups,
           std::vector<unsigned int> (n_ord, n_elem))
   {
   }
Forest::SnVector::SnVector (const unsigned int n_groups, const std::vector< unsigned int > & block_sizes)
Standard constructor.
Creates the object and allocate the necessary space.
Definition at line 29 of file sn_vector.cc.
       : ForestVector<double> (n_groups, block_sizes)
   {
   }
Member Function Documentation
void Forest::SnVector::reinit (const unsigned int n_groups, const unsigned int n_ord, const unsigned int n_elem, const bool leave_elements_uninitialized = false)
Reinitialize the vector.
Resize to have the structure provided by the arguments Note that the second argument must have a default value equal to false
Parameters
n_groups
n_ord
n_elem
leave_elements_uninitialized = false
Definition at line 36 of file sn_vector.cc.
Referenced by Forest::EigenProb< dim >::get_psi(), Forest::EigenFissionDensity< dim >::set_solution_sizes(), Forest::EigenStandard< dim >::set_solution_sizes(), and Forest::SolverEq< dim >::SolverEq().
   {
     std::vector<unsigned int> block_sizes (n_ord, n_elem);
     BaseClass::reinit (n_groups, block_sizes, leave_elements_uninitialized);
   }
unsigned int Forest::SnVector::get_n_groups () const inline
Number of groups defining the first dimension.
Definition at line 204 of file sn_vector.h.
     {
       return BaseClass::size0();
     }
const std::vector<unsigned int>& Forest::SnVector::get_block_sizes () const inline
Number of groups defining the first dimension.
Definition at line 212 of file sn_vector.h.
     {
       return BaseClass::size1();
     }
void Forest::ForestVector< double >::reinit (const unsigned int n_multi_blocks, const std::vector< unsigned int > & block_sizes, const bool leave_elements_uninitialized = false) inherited
Reinitialize the vector.
Resize to have the structure provided by the arguments Note that the second argument must have a default value equal to false
Parameters
n_multi_blocks
block_sizes
leave_elements_uninitialized = false
Referenced by reinit().
void Forest::ForestVector< double >::reinit (const ForestVector< double > & v, bool leave_elements_uninitialized = false) inherited
resize the vector.
resize to have the same structure as the one provided and/or clear vector. note that the second argument must have a default value equal to false
Parameters
v
leave_elements_uninitialized = false
double Forest::ForestVector< double >::operator* (const ForestVector< double > & v) const inherited
Scalar product of this vector times vector v.
Parameters
v
Return values
res = <this,v>
void Forest::ForestVector< double >::add (const ForestVector< double > & x) inherited
Addition of vectors.
Add the vector x to the current vector.
this += x
Parameters
x
void Forest::ForestVector< double >::add (const double a, const ForestVector< double > & x) inherited
Addition of scaled vector.
Add the vector a x to the current vector.
this += a*x
Parameters
a
x
void Forest::ForestVector< double >::sadd (const double a, const double b, const ForestVector< double > & x) inherited
Scaling and simple addition.
Add the vector b x to the current vector scaled by a.
this = a*this + b*x
Parameters
a
b
x
void Forest::ForestVector< double >::equ (const double a, const ForestVector< double > & x) inherited
Assignment.
Assignment of a scaled vector.
this = a*x
Parameters
a
x
ForestVector<double >& Forest::ForestVector< double >::operator*= (const double a) inherited
Scale the elements of the vector by a fixed value.
Scaling this vector with the scalar value a.
this *= a
Parameters
a
void Forest::ForestVector< double >::swap (ForestVector< double > & v) inherited
Swap the content of this vector with the content of vector v.
It only swaps the pointers to the data of the two vectors.
tmp = this; this = v; v = tmp;
Note
They must have the same number of groups, directions and elements.
Parameters
v
double Forest::ForestVector< double >::l2_norm () const inherited
Return the l2 norm of the vector.
Return values
res = <this,this>^{1/2}
double Forest::ForestVector< double >::add_and_dot (const double a, const ForestVector< double > & V, const ForestVector< double > & W) inherited
Performs a combined operation of a vector addition and a subsequent inner product, returning the value of the inner product.
std::size_t Forest::ForestVector< double >::memory_consumption () const inherited
memory_consumption.
unsigned int Forest::ForestVector< double >::size0 () const inherited
Number of groups defining the first dimension.
const std::vector<unsigned int>& Forest::ForestVector< double >::size1 () const inherited
Number of directions defining the second dimension.
Member Data Documentation
bool Forest::ForestVector< double >::m_initialized protected inherited
False when called with empty constructor, true otherwise.
Definition at line 50 of file forest_vector.h.
unsigned int Forest::ForestVector< double >::m_n_multi_blocks protected inherited
Number of multi-blocks in the current Vector.
Definition at line 53 of file forest_vector.h.
std::vector<unsigned int> Forest::ForestVector< double >::m_block_sizes protected inherited
Number of dofs each energy group.
Definition at line 56 of file forest_vector.h.
std::vector<BlockVector<double > > Forest::ForestVector< double >::m_data protected inherited
data
Definition at line 59 of file forest_vector.h.
The documentation for this class was generated from the following files:
/home/lns/Codes/forest-public/mylib/include/algebra/sn_vector.h
/home/lns/Codes/forest-public/mylib/src/algebra/sn_vector.cc