FOREST: Forest::StatsTimer Class Reference
Forest::StatsTimer Class Reference
ForestUtils
StatsTimer.
#include </home/lns/Codes/forest-public/mylib/include/utils/forest_utils_timer.h>
Public Member Functions
void add (const std::string &flag, double value)
add
void add (const char *flag, double value)
add
void add_final (double value)
add_final
void print_detailed ()
print_detailed
double get_total () const
get_total
Static Public Member Functions
static StatsTimer & instance ()
Instance.
Private Member Functions
StatsTimer ()
Singleton constructor.
StatsTimer (StatsTimer const &)
Don't Implement copy constructor for singleton.
void operator= (StatsTimer const &)
Don't implement assignment operator for singleton.
Private Attributes
double total_time
double final_time
std::map< double, std::string > detailed
Detailed Description
StatsTimer.
Note
Don't forget to declare copy constructor and assignment operator but don't implement them. You want to make sure they are inaccessible otherwise you may accidentally get copies of your singleton appearing.
Definition at line 17 of file forest_utils_timer.h.
Constructor & Destructor Documentation
Forest::StatsTimer::StatsTimer () inline private
Singleton constructor.
Definition at line 51 of file forest_utils_timer.h.
         : total_time (0),
           final_time (0)
     {
     }
Forest::StatsTimer::StatsTimer (StatsTimer const &) private
Don't Implement copy constructor for singleton.
Member Function Documentation
static StatsTimer& Forest::StatsTimer::instance () inline static
Instance.
Definition at line 23 of file forest_utils_timer.h.
Referenced by Forest::EqSolverWG< dim >::EqSolverWG(), Forest::finish_forest(), Forest::PostProcessing< dim >::PostProcessing(), Forest::EigenSolver< dim >::power_iteration(), Forest::ProbGeom< dim >::ProbGeom(), Forest::EigenSolver< dim >::slepc(), Forest::SolverEq< dim >::SolverEq(), and Forest::State< dim >::State().
     {
       static StatsTimer _instance;
       return _instance;
     }
void Forest::StatsTimer::add (const std::string & flag, double value)
add
Definition at line 30 of file forest_utils_timer.cc.
Referenced by Forest::EqSolverWG< dim >::EqSolverWG(), instance(), Forest::PostProcessing< dim >::PostProcessing(), Forest::EigenSolver< dim >::power_iteration(), Forest::ProbGeom< dim >::ProbGeom(), Forest::EigenSolver< dim >::slepc(), Forest::SolverEq< dim >::SolverEq(), and Forest::State< dim >::State().
   {
     detailed.insert (std::pair<double, std::string> (value, flag));
     total_time += value;
   }
void Forest::StatsTimer::add (const char * flag, double value)
add
Definition at line 37 of file forest_utils_timer.cc.
   {
     detailed.insert (
         std::pair<double, std::string> (value, std::string (flag)));
     total_time += value;
   }
void Forest::StatsTimer::add_final (double value)
add_final
Definition at line 24 of file forest_utils_timer.cc.
Referenced by instance().
   {
     final_time = value;
   }
void Forest::StatsTimer::print_detailed ()
print_detailed
Definition at line 45 of file forest_utils_timer.cc.
Referenced by Forest::finish_forest(), and instance().
   {
     log_print_line ();
     log_print_title ("Timing statistics (Wall time)");
     log_print_line (' ');
     std::map<double, std::string>::reverse_iterator it;
     for (it = detailed.rbegin (); it != detailed.rend (); ++it)
     {
       log_print_time (it->second, it->first);
     }
     log_print_line (' ');
     log_print_time ("Total time calculated:", total_time);
     if (final_time != 0)
     {
       log_print_line (' ');
       log_print_time ("Final time provided:", final_time);
     }
   }
double Forest::StatsTimer::get_total () const
get_total
Definition at line 65 of file forest_utils_timer.cc.
Referenced by instance().
   {
     return total_time;
   }
void Forest::StatsTimer::operator= (StatsTimer const &) private
Don't implement assignment operator for singleton.
Referenced by StatsTimer().
Member Data Documentation
double Forest::StatsTimer::total_time private
Definition at line 65 of file forest_utils_timer.h.
Referenced by add(), get_total(), and print_detailed().
double Forest::StatsTimer::final_time private
Definition at line 66 of file forest_utils_timer.h.
Referenced by add_final(), and print_detailed().
std::map<double, std::string> Forest::StatsTimer::detailed private
Definition at line 67 of file forest_utils_timer.h.
Referenced by add(), and print_detailed().
The documentation for this class was generated from the following files:
/home/lns/Codes/forest-public/mylib/include/utils/forest_utils_timer.h
/home/lns/Codes/forest-public/mylib/src/utils/forest_utils_timer.cc