FOREST: Forest::MomentIndexer< dim > Class Template Reference
Forest::MomentIndexer< dim > Class Template Reference
ForestAngle
Indexes spherical harmonics moments.
#include </home/lns/Codes/forest-public/mylib/include/angle/moment_indexer.h>
Public Member Functions
MomentIndexer (unsigned int angular_order)
Constructor.
const std::vector< int > & get_m_index (unsigned int l) const
Return vector of values of m for a given l.
unsigned int get_angular_order () const
Return angular order.
unsigned int get_number_of_moments () const
Return number of moments.
int get_l (unsigned int i) const
Returns l value.
int get_m (unsigned int i) const
Return m value.
unsigned int get_index (unsigned int l, int m) const
Returns moment index.
void display () const
Print the indices.
Private Member Functions
void construct ()
template<>
void construct ()
template<>
void construct ()
template<>
void construct ()
Private Attributes
unsigned int m_angular_order
Legendre order of the flux.
unsigned int m_number_of_moments
Number of moments.
std::vector< std::vector< int > > m_m_index
Vector of proper \(m\) values for a given \(l\).
std::vector< int > m_l_vec
Vector of l values.
std::vector< int > m_m_vec
Vector of m values.
Detailed Description
template<int dim>
class Forest::MomentIndexer< dim >
Indexes spherical harmonics moments.
The one group (or within-group) scattering source in 3-d is defined
\[ Q(\mathbf{r},\mathbf{\Omega}) = \sum^L_{l=0} \frac{2l+1}{4\pi} \sum^l_{m=-l} \Sigma_{sl}(\mathbf{r}) \phi^m_l(\mathbf{r}) . \]
and for the representation of the angular flux in Spherical Harmonics
\[ \Psi(\mathbf{r},\mathbf{\Omega}) = \sum^L_{l=0} \sum^l_{m=-l} Y_{l}^{m}(\mathbf{r}) \Phi^m_l(\mathbf{r}) . \]
Such sums over \(l\) and \(m\) are commonplace, in generating sources and also in simply accessing moments sequentially. This class builds a vector of \((l,m)\) pairs that can be used in a single loop over all flux moments \(\Phi^m_l\),
\[ \Psi(\mathbf{r},\mathbf{\Omega}) \equiv \sum^M_{i=0} Y_{i}(\mathbf{r}) \Phi_{i}(\mathbf{r}) \]
where the sumation is actually done using the re-indexing \(i = \text{ind}(m,l) \) and the convention
\begin{align} & Y_{i}(\mathbf{r}) := Y_{l}^{m}(\mathbf{r}) \\ & \Phi_{i}(\mathbf{r}) := \Phi_{l}^{m}(\mathbf{r}) . \end{align}
For 3-d, the moments are ordered as
\[ [(0,0)] \, , \, \, \, [(1,-1),\, (1,0)\, (1,1)] \, , \, \, \, [(2,-2),\,(2,-1)\, \ldots \]
For an angular order of \(L\), there are \((L+1)^2\) moments.
For 2-d, several moments can be eliminated by symmetry. Only those moments for which \(l+m\) is even are retained (see Hebert). Thus, the moments are ordered as
\[ [(0,0)] \, , \, \, \, [(1,-1),\, (1,1)] \, , \, \, \, [(2,-2),\,(2,0)\, \ldots \]
For an angular order of \(L\), there are \((L+1)(L+2)/2\) moments.
For 1-d, \(m=0\), so that the moments are ordered by \(l\) alone, from 0 to the given order. Hence, there are \(L+1\) moments.
Definition at line 73 of file moment_indexer.h.
Constructor & Destructor Documentation
template<int dim> Forest::MomentIndexer< dim >::MomentIndexer (unsigned int angular_order)
Constructor.
Parameters
angular_order Spherical harmonics order of the flux.
Definition at line 19 of file moment_indexer.cc.
       : m_angular_order (angular_order),
         m_number_of_moments(0)
   {
     this->construct ();
     // Fill the l and m vectors
     m_l_vec.resize (m_number_of_moments, 0);
     m_m_vec.resize (m_number_of_moments, 0);
     unsigned int j = 0;
     for (unsigned int l = 0; l <= m_angular_order; ++l)
     {
       for (unsigned int i = 0; i < m_m_index[l].size (); ++i, ++j)
       {
         m_l_vec[j] = l;
         m_m_vec[j] = m_m_index[l][i];
       }
     }
   }
Member Function Documentation
template<int dim> const std::vector<int>& Forest::MomentIndexer< dim >::get_m_index (unsigned int l) const
Return vector of values of m for a given l.
Parameters
l Angular degree.
Returns
m values
template<int dim> unsigned int Forest::MomentIndexer< dim >::get_angular_order () const inline
Return angular order.
Returns
Definition at line 97 of file moment_indexer.h.
     {
       return m_angular_order;
     }
template<int dim> unsigned int Forest::MomentIndexer< dim >::get_number_of_moments () const inline
Return number of moments.
Definition at line 104 of file moment_indexer.h.
Referenced by Forest::ExtractBV< dim >::calculate_moments_ass(), and Forest::ExtractBV< dim >::calculate_moments_pin().
     {
       return m_number_of_moments;
     }
template<int dim> int Forest::MomentIndexer< dim >::get_l (unsigned int i) const inline
Returns l value.
Parameters
i Cardinal moment index.
Returns
l value.
Definition at line 115 of file moment_indexer.h.
Referenced by Forest::ExtractBV< dim >::calculate_moments_ass(), Forest::ExtractBV< dim >::calculate_moments_pin(), and Forest::MomentIndexer< dim >::display().
     {
       return m_l_vec[i];
     }
template<int dim> int Forest::MomentIndexer< dim >::get_m (unsigned int i) const inline
Return m value.
Parameters
i Cardinal moment index.
Returns
m value.
Definition at line 126 of file moment_indexer.h.
Referenced by Forest::ExtractBV< dim >::calculate_moments_ass(), Forest::ExtractBV< dim >::calculate_moments_pin(), and Forest::MomentIndexer< dim >::display().
     {
       return m_m_vec[i];
     }
template<int dim> unsigned int Forest::MomentIndexer< dim >::get_index (unsigned int l, int m) const inline
Returns moment index.
Parameters
l l value.
m m value.
Returns
Cardinal moment index.
Definition at line 138 of file moment_indexer.h.
     {
       return m_m_index[l][m];
     }
template<int dim> void Forest::MomentIndexer< dim >::display () const
Print the indices.
Definition at line 41 of file moment_indexer.cc.
Referenced by Forest::MomentIndexer< dim >::get_index().
   {
     std::cout << " MOMENTS INDEXER: " << std::endl;
     for (unsigned int i = 0; i < m_number_of_moments; ++i)
     {
       const int l = this->get_l(i);
       const int m = this->get_m(i);
       std::cout << " " << i << " " << l << " " << m << std::endl;
     }
   }
template<int dim> void Forest::MomentIndexer< dim >::construct () private
Definition at line 54 of file moment_indexer.cc.
Referenced by Forest::MomentIndexer< dim >::MomentIndexer().
   {
     Assert(false, dealii::ExcMessage("Wrong dimension provided."));
   }
template<> void Forest::MomentIndexer< 1 >::construct () private
Definition at line 61 of file moment_indexer.cc.
   {
     m_number_of_moments = m_angular_order + 1;
     m_m_index.resize (m_angular_order + 1);
     for (unsigned int l = 0; l <= m_angular_order; ++l)
     {
       m_m_index[l].resize (1, 0); /* m is always zero in 1D */
     }
   }
template<> void Forest::MomentIndexer< 2 >::construct () private
Definition at line 73 of file moment_indexer.cc.
   {
     m_number_of_moments = (m_angular_order + 1) * (m_angular_order + 2) / 2;
     m_m_index.resize (m_angular_order + 1);
     for (int l = 0; l <= (int) m_angular_order; ++l)
     {
       for (int m = -l; m <= l; m++)
       {
         if ((m + l) % 2 == 0)
         {
           m_m_index[l].push_back (m);
         }
       }
     }
   }
template<> void Forest::MomentIndexer< 3 >::construct () private
Definition at line 91 of file moment_indexer.cc.
   {
     m_number_of_moments = (m_angular_order + 1) * (m_angular_order + 1);
     m_m_index.resize (m_angular_order + 1);
     for (int l = 0; l <= (int) m_angular_order; ++l)
     {
       for (int m = -l; m <= l; ++m)
       {
         m_m_index[l].push_back (m);
       }
     }
   }
Member Data Documentation
template<int dim> unsigned int Forest::MomentIndexer< dim >::m_angular_order private
Legendre order of the flux.
Definition at line 150 of file moment_indexer.h.
Referenced by Forest::MomentIndexer< dim >::construct(), Forest::MomentIndexer< dim >::get_angular_order(), and Forest::MomentIndexer< dim >::MomentIndexer().
template<int dim> unsigned int Forest::MomentIndexer< dim >::m_number_of_moments private
Number of moments.
Definition at line 152 of file moment_indexer.h.
Referenced by Forest::MomentIndexer< dim >::construct(), Forest::MomentIndexer< dim >::display(), Forest::MomentIndexer< dim >::get_number_of_moments(), and Forest::MomentIndexer< dim >::MomentIndexer().
template<int dim> std::vector<std::vector<int> > Forest::MomentIndexer< dim >::m_m_index private
Vector of proper \(m\) values for a given \(l\).
Definition at line 154 of file moment_indexer.h.
Referenced by Forest::MomentIndexer< dim >::construct(), Forest::MomentIndexer< dim >::get_index(), and Forest::MomentIndexer< dim >::MomentIndexer().
template<int dim> std::vector<int> Forest::MomentIndexer< dim >::m_l_vec private
Vector of l values.
Definition at line 156 of file moment_indexer.h.
Referenced by Forest::MomentIndexer< dim >::get_l(), and Forest::MomentIndexer< dim >::MomentIndexer().
template<int dim> std::vector<int> Forest::MomentIndexer< dim >::m_m_vec private
Vector of m values.
Definition at line 158 of file moment_indexer.h.
Referenced by Forest::MomentIndexer< dim >::get_m(), and Forest::MomentIndexer< dim >::MomentIndexer().
The documentation for this class was generated from the following files:
/home/lns/Codes/forest-public/mylib/include/angle/moment_indexer.h
/home/lns/Codes/forest-public/mylib/src/angle/moment_indexer.cc