FOREST: Forest::StatsMemory Class Reference
Forest::StatsMemory Class Reference
ForestUtils
StatsMemory.
#include </home/lns/Codes/forest-public/mylib/include/utils/forest_utils_memory.h>
Public Member Functions
void add (const std::string &flag, double value)
add
void add (const char *flag, double value)
add
void print_detailed ()
print_detailed
double get_total () const
get_total
Static Public Member Functions
static StatsMemory & instance ()
instance
Private Member Functions
StatsMemory ()
Singleton constructor.
StatsMemory (StatsMemory const &)
Don't Implement copy constructor for singleton.
void operator= (StatsMemory const &)
Don't implement assignment operator for singleton.
Private Attributes
double total_memory
std::multimap< double, std::string > detailed
Detailed Description
StatsMemory.
Definition at line 12 of file forest_utils_memory.h.
Constructor & Destructor Documentation
Forest::StatsMemory::StatsMemory () inline private
Singleton constructor.
Definition at line 42 of file forest_utils_memory.h.
         : total_memory (0)
     {
     }
Forest::StatsMemory::StatsMemory (StatsMemory const &) private
Don't Implement copy constructor for singleton.
Member Function Documentation
static StatsMemory& Forest::StatsMemory::instance () inline static
instance
Definition at line 18 of file forest_utils_memory.h.
Referenced by Forest::EigenSolver< dim >::EigenSolver(), Forest::EqDiffusion< dim >::EqDiffusion(), Forest::EqSolverWG< dim >::EqSolverWG(), Forest::EqTransport< dim >::EqTransport(), Forest::ProbGeom< dim >::ProbGeom(), Forest::SolverEq< dim >::SolverEq(), and Forest::State< dim >::State().
     {
       static StatsMemory _instance;
       return _instance;
     }
void Forest::StatsMemory::add (const std::string & flag, double value)
add
Definition at line 23 of file forest_utils_memory.cc.
Referenced by Forest::EigenSolver< dim >::EigenSolver(), Forest::EqDiffusion< dim >::EqDiffusion(), Forest::EqSolverWG< dim >::EqSolverWG(), Forest::EqTransport< dim >::EqTransport(), instance(), Forest::ProbGeom< dim >::ProbGeom(), Forest::SolverEq< dim >::SolverEq(), and Forest::State< dim >::State().
   {
     detailed.insert (std::pair<double, std::string> (value, flag));
     total_memory += value;
   }
void Forest::StatsMemory::add (const char * flag, double value)
add
Definition at line 30 of file forest_utils_memory.cc.
   {
     detailed.insert (
         std::pair<double, std::string> (value, std::string (flag)));
     total_memory += value;
   }
void Forest::StatsMemory::print_detailed ()
print_detailed
Definition at line 38 of file forest_utils_memory.cc.
Referenced by Forest::EigenSolver< dim >::EigenSolver(), and instance().
   {
     log_print_line ();
     log_print_title ("Memory statistics");
     log_print_line (' ');
     std::map<double, std::string>::reverse_iterator it;
     for (it = detailed.rbegin (); it != detailed.rend (); ++it)
     {
       log_print_mem (it->second, it->first);
     }
     log_print_line (' ');
     log_print_mem ("Total memory:", total_memory);
   }
double Forest::StatsMemory::get_total () const
get_total
Definition at line 53 of file forest_utils_memory.cc.
Referenced by instance().
   {
     return total_memory;
   }
void Forest::StatsMemory::operator= (StatsMemory const &) private
Don't implement assignment operator for singleton.
Referenced by StatsMemory().
Member Data Documentation
double Forest::StatsMemory::total_memory private
Definition at line 55 of file forest_utils_memory.h.
Referenced by add(), get_total(), and print_detailed().
std::multimap<double, std::string> Forest::StatsMemory::detailed private
Definition at line 56 of file forest_utils_memory.h.
Referenced by add(), and print_detailed().
The documentation for this class was generated from the following files:
/home/lns/Codes/forest-public/mylib/include/utils/forest_utils_memory.h
/home/lns/Codes/forest-public/mylib/src/utils/forest_utils_memory.cc