FOREST: Forest::DiffOpMatrixFree< dim > Class Template Reference
Forest::DiffOpMatrixFree< dim > Class Template Reference
ForestNeutronics
Diffusion operator and sweep, matrix-free version.
#include </home/lns/Codes/forest-public/mylib/include/neutronics/diff_op_matrix_free.h>
Public Member Functions
DiffOpMatrixFree (State< dim > &state)
Constructor.
virtual ~DiffOpMatrixFree ()
Destructor.
virtual void vmult (BlockVector< double > &phi, const BlockVector< double > &source, const unsigned int g)
Apply the diffusion operator for one group - BlockVector version.
virtual void prec (BlockVector< double > &phi, const BlockVector< double > &source, const unsigned int g) const
Preconditioner ?
virtual unsigned int get_n_groups () const
Access function.
virtual double memory_consumption () const
Access function.
void vmult (SnVector &phi, const SnVector &source)
Apply the diffusion operator - SnVector version.
void vmult (SnVector &phi, const BlockVector< double > &source, const unsigned int g)
Apply the diffusion operator for one group - SnVector version.
Private Member Functions
void setup_system ()
void assemble_system ()
void setup_prec ()
void assemble_prec ()
void vmult_matrix_free_g_h (BlockVector< double > &phi, const BlockVector< double > &source, const unsigned int g)
Private Attributes
const State< dim > & mp_state
const FiniteElement< dim, dim > & mp_fe
const MappingQ1< dim > & mp_mapping
const DoFHandler< dim, dim > & mp_dof_handler
std::vector< std::shared_ptr< MatrixFreeIntegrator< dim > > > matfree_integrator
Detailed Description
template<int dim>
class Forest::DiffOpMatrixFree< dim >
Diffusion operator and sweep, matrix-free version.
Defines the diffusion operator
\begin{align*} & - \nabla \frac{1}{3\Sigma_{T,g}(\mathbf{r})} \nabla \Phi_g(\mathbf{r}) + \Sigma_{T,g}(\mathbf{r}) \Phi_g(\mathbf{r}) \nonumber \ \ & = \frac{1}{4\pi} \sum_{h=0}^{G-1} \Sigma_{s0,h\to g}(\mathbf{r}) \Phi_{h}(\mathbf{r}) + \frac{1}{\lambda}\chi_g(\mathbf{r})\frac{1}{4\pi}\sum_{h=0}^{G-1} \nu\Sigma_{f,h}(\mathbf{r}) \Phi_h(\mathbf{r}) \end{align*}
or using the diffusion coefficient and the absorption cross section
\begin{align*} & - \nabla D_{g}(\mathbf{r}) \nabla \Phi_g(\mathbf{r}) + \Sigma_{a,g}(\mathbf{r}) \Phi_g(\mathbf{r}) \nonumber \ \ & = \frac{1}{4\pi} \sum_{h=0,h\neq g}^{G-1} \Sigma_{s0,h\to g}(\mathbf{r}) \Phi_{h}(\mathbf{r}) + \frac{1}{\lambda}\chi_g(\mathbf{r})\frac{1}{4\pi}\sum_{h=0}^{G-1} \nu\Sigma_{f,h}(\mathbf{r}) \Phi_h(\mathbf{r}) \end{align*}
Todo:
Correct the documentation
Todo:
Add details about the matrix-free implementation
Definition at line 43 of file diff_op_matrix_free.h.
Constructor & Destructor Documentation
template<int dim> Forest::DiffOpMatrixFree< dim >::DiffOpMatrixFree (State< dim > & state)
Constructor.
Parameters
state
Definition at line 43 of file diff_op_matrix_free.cc.
       : mp_state (state),
         mp_fe (state.get_fe ()),
         mp_mapping (state.get_mapping ()),
         mp_dof_handler (mp_state.get_dof_handler ())
   {
     this->setup_system ();
     this->assemble_system ();
     this->setup_prec ();
     this->assemble_prec ();
   }
template<int dim> virtual Forest::DiffOpMatrixFree< dim >::~DiffOpMatrixFree () inline virtual
Destructor.
Definition at line 55 of file diff_op_matrix_free.h.
     {
     }
Member Function Documentation
template<int dim> void Forest::DiffOpMatrixFree< dim >::vmult (BlockVector< double > & phi, const BlockVector< double > & source, const unsigned int g) virtual
Apply the diffusion operator for one group - BlockVector version.
Parameters
phi
source
g
Implements Forest::DiffOp< dim >.
Definition at line 57 of file diff_op_matrix_free.cc.
   {
     //matfree_integrator (
     //    new MatrixFreeIntegrator<dim> (mp_state, g, g));
     matfree_integrator[g]->vmult_add (phi.block (0), source.block (0));
     //this->vmult_matrix_free_g_h (phi, source, g, h);
   }
template<int dim> void Forest::DiffOpMatrixFree< dim >::prec (BlockVector< double > & dst, const BlockVector< double > & src, const unsigned int g) const virtual
Preconditioner ?
Implements Forest::DiffOp< dim >.
Definition at line 69 of file diff_op_matrix_free.cc.
   {
     phi = source;
     //const unsigned int n_m = 1;
     //for (unsigned int i = 0; i < mp_dof_handler.n_dofs (); ++i)
     //  phi.block (0)[i] = source.block (0)[i] * m_prec_matrix[g].block (0)[i];
   }
template<int dim> unsigned int Forest::DiffOpMatrixFree< dim >::get_n_groups () const virtual
Access function.
Implements Forest::DiffOp< dim >.
Definition at line 127 of file diff_op_matrix_free.cc.
   {
     return mp_state.get_n_groups ();
   }
template<int dim> double Forest::DiffOpMatrixFree< dim >::memory_consumption () const virtual
Access function.
Implements Forest::DiffOp< dim >.
Definition at line 134 of file diff_op_matrix_free.cc.
   {
     //const unsigned int n_groups = mp_state.get_n_groups ();
     double memory_consumption = 0;
     return memory_consumption;
   }
template<int dim> void Forest::DiffOpMatrixFree< dim >::setup_system () private
Definition at line 93 of file diff_op_matrix_free.cc.
Referenced by Forest::DiffOpMatrixFree< dim >::DiffOpMatrixFree().
   {
     const unsigned int n_g = mp_state.get_n_groups ();
     for (unsigned int g = 0; g < n_g; ++g)
     {
       matfree_integrator.push_back (
         std::shared_ptr<MatrixFreeIntegrator<dim> > (
           new MatrixFreeIntegrator<dim> (mp_state, g, g)));
     }
   }
template<int dim> void Forest::DiffOpMatrixFree< dim >::assemble_system () private
Definition at line 106 of file diff_op_matrix_free.cc.
Referenced by Forest::DiffOpMatrixFree< dim >::DiffOpMatrixFree().
   {
     // do nothing
   }
template<int dim> void Forest::DiffOpMatrixFree< dim >::setup_prec () private
Definition at line 113 of file diff_op_matrix_free.cc.
Referenced by Forest::DiffOpMatrixFree< dim >::DiffOpMatrixFree().
   {
     // do nothing
   }
template<int dim> void Forest::DiffOpMatrixFree< dim >::assemble_prec () private
Definition at line 120 of file diff_op_matrix_free.cc.
Referenced by Forest::DiffOpMatrixFree< dim >::DiffOpMatrixFree().
   {
     // do nothing
   }
template<int dim> void Forest::DiffOpMatrixFree< dim >::vmult_matrix_free_g_h (BlockVector< double > & phi, const BlockVector< double > & source, const unsigned int g) private
Definition at line 81 of file diff_op_matrix_free.cc.
   {
     matfree_integrator[g]->vmult_add (dst.block (0), src.block (0));
     //deallog << "m_Diff_matrix[g][h].vmult_add (dst, src);" << std::endl;
     //m_Diff_matrix[g].vmult_add (dst, src);
   }
template<int dim> void Forest::DiffOp< dim >::vmult (SnVector & phi, const SnVector & source) inherited
Apply the diffusion operator - SnVector version.
Parameters
phi
source
Definition at line 18 of file diff_op.cc.
   {
     for (unsigned int g = 0; g < get_n_groups (); ++g)
     {
       vmult (phi.m_data[g], source.m_data[g], g);
     }
   }
template<int dim> void Forest::DiffOp< dim >::vmult (SnVector & phi, const BlockVector< double > & source, const unsigned int g) inherited
Apply the diffusion operator for one group - SnVector version.
Parameters
phi
source
g
Definition at line 29 of file diff_op.cc.
   {
     vmult (phi.m_data[g], source, g);
   }
Member Data Documentation
template<int dim> const State<dim>& Forest::DiffOpMatrixFree< dim >::mp_state private
Definition at line 98 of file diff_op_matrix_free.h.
Referenced by Forest::DiffOpMatrixFree< dim >::get_n_groups(), and Forest::DiffOpMatrixFree< dim >::setup_system().
template<int dim> const FiniteElement<dim, dim>& Forest::DiffOpMatrixFree< dim >::mp_fe private
Definition at line 99 of file diff_op_matrix_free.h.
template<int dim> const MappingQ1<dim>& Forest::DiffOpMatrixFree< dim >::mp_mapping private
Definition at line 100 of file diff_op_matrix_free.h.
template<int dim> const DoFHandler<dim, dim>& Forest::DiffOpMatrixFree< dim >::mp_dof_handler private
Definition at line 101 of file diff_op_matrix_free.h.
template<int dim> std::vector<std::shared_ptr<MatrixFreeIntegrator<dim> > > Forest::DiffOpMatrixFree< dim >::matfree_integrator private
Definition at line 103 of file diff_op_matrix_free.h.
Referenced by Forest::DiffOpMatrixFree< dim >::setup_system(), Forest::DiffOpMatrixFree< dim >::vmult(), and Forest::DiffOpMatrixFree< dim >::vmult_matrix_free_g_h().
The documentation for this class was generated from the following files:
/home/lns/Codes/forest-public/mylib/include/neutronics/diff_op_matrix_free.h
/home/lns/Codes/forest-public/mylib/src/neutronics/diff_op_matrix_free.cc