FOREST: Forest::QuadratureLevelSymType2< dim > Class Template Reference
Forest::QuadratureLevelSymType2< dim > Class Template Reference
ForestAngle
QuadratureLevelSymType2.
#include </home/lns/Codes/forest-public/mylib/include/angle/quadrature_levelsymmetric_type2.h>
Public Member Functions
QuadratureLevelSymType2 (unsigned int order_)
unsigned int get_n_angles () const
unsigned int get_n_octants () const
unsigned int get_n_angles_per_octant () const
unsigned int get_a_order () const
unsigned int get_p_order () const
unsigned int get_order () const
unsigned int get_n_leg_moments () const
const std::vector< std::vector< double > > & get_q () const
Return quadrature points \(q(:) \).
const std::vector< double > & get_q (unsigned int a) const
Return quadrature point \(q \).
double get_q (unsigned int a, unsigned int d) const
Return quadrature point \(q(d) \).
const std::vector< double > & get_w () const
Return the weights.
double get_w (unsigned int i) const
Return the weight.
unsigned int get_out_ind (unsigned int face_, unsigned int in_angle_ind_) const
Returns the index of the outgoing direction associated with the incoming direction in_angle_ind at the face face.
double get_octant_sign (unsigned int o, unsigned int coordinate) const
unsigned int get_index (unsigned int o, unsigned int a) const
Return cardinal angle index.
bool valid_index (unsigned int o, unsigned int a) const
Are the indices valid?
void disp () const
Displaying the ordinates and the weights in one dimension.
void check_ordinates () const
template<>
void check_ordinates () const
double memory_consumption () const
Static Public Member Functions
static unsigned int get_n_angles_per_octant (unsigned int a_order_)
Public Attributes
std::vector< std::vector< unsigned int > > out2in
Protected Member Functions
void set_n_octants ()
void set_n_angles ()
void set_octant_sign ()
Assigning the signs for each octant.
void set_all_angles (double angular_weight)
void set_bc_map ()
j_ord = bc_map(f, i_ord), with
void set_in_from_out ()
j_ord = bc_map(f, i_ord), with
void set_a_order (unsigned int a_order_)
void set_p_order (unsigned int p_order_)
void set_order (unsigned int order_)
void set_n_leg_moments (unsigned int order_)
Protected Attributes
unsigned int a_order
unsigned int p_order
unsigned int order
unsigned int n_angles_per_octant
std::string name
unsigned int n_octants
unsigned int n_angles
unsigned int n_leg_moments
std::vector< std::vector< double > > octant_sign
std::vector< std::vector< double > > xx
std::vector< double > ww
std::vector< std::vector< unsigned int > > in2out
Private Member Functions
void set_number_angles ()
void set_ordinates ()
void set_ind_quad (std::vector< double > &cosines, std::vector< double > &tmp_w, unsigned int n)
Hardcoding several values for the discrete ordinates generation.
void get_weight_dist (std::vector< unsigned int > &w_dist) const
S_2 weight distribution {1};.
double get_dimension_weight () const
template<>
void set_ordinates ()
Private Attributes
unsigned int n_cosines
Detailed Description
template<int dim>
class Forest::QuadratureLevelSymType2< dim >
QuadratureLevelSymType2.
Definition at line 25 of file quadrature_levelsymmetric_type2.h.
Constructor & Destructor Documentation
template<int dim> Forest::QuadratureLevelSymType2< dim >::QuadratureLevelSymType2 (unsigned int order_)
Definition at line 19 of file quadrature_levelsymmetric_type2.cc.
       : QuadratureBase<dim> (get_n_angles_per_octant (order_), "LevelSymType2"),
         n_cosines (order_ / 2)
   {
     this->set_a_order (order_);
     this->set_p_order (order_);
     this->set_order (order_);
     this->set_n_leg_moments (order_);
     set_ordinates ();
     this->set_all_angles (get_dimension_weight ());
     this->set_bc_map ();
     this->set_in_from_out ();
   }
Member Function Documentation
template<int dim> static unsigned int Forest::QuadratureLevelSymType2< dim >::get_n_angles_per_octant (unsigned int a_order_) inline static
Definition at line 31 of file quadrature_levelsymmetric_type2.h.
     {
       if (dim == 1)
       {
         return 0;
       }
       else if (dim == 2)
       {
         return ((a_order_ / 2) * (a_order_ / 2 + 1)) / 2;
       }
       else if (dim == 3)
       {
         return ((a_order_ / 2) * (a_order_ / 2 + 1)) / 2;
       }
       else
       {
         return 0;
       }
     }
template<int dim> void Forest::QuadratureLevelSymType2< dim >::set_number_angles () private
template<int dim> void Forest::QuadratureLevelSymType2< dim >::set_ordinates () private
Definition at line 416 of file quadrature_levelsymmetric_type2.cc.
Referenced by Forest::QuadratureLevelSymType2< dim >::QuadratureLevelSymType2().
   {
     std::vector<double> x_tmp (n_cosines);
     std::vector<double> w_tmp (this->n_angles_per_octant);
     std::vector<unsigned int> w_dist (this->n_angles_per_octant);
     set_ind_quad (x_tmp, w_tmp, this->order);
     get_weight_dist (w_dist);
     unsigned int k = 0;
     for (unsigned int i = 0; i < n_cosines; ++i)
     {
       for (unsigned int j = 0; j < i + 1; ++j, ++k)
       {
         this->xx[k][0] = x_tmp[j];
         this->xx[k][1] = x_tmp[i - j];
         this->xx[k][2] = std::sqrt (
             1.0 - this->xx[k][0] * this->xx[k][0]
             - this->xx[k][1] * this->xx[k][1]);
         this->ww[k] = w_tmp[w_dist[k] - 1];
       }
     }
     w_dist.clear ();
     x_tmp.clear ();
     w_tmp.clear ();
   }
template<int dim> void Forest::QuadratureLevelSymType2< dim >::set_ind_quad (std::vector< double > & cosines, std::vector< double > & tmp_w, unsigned int n) private
Hardcoding several values for the discrete ordinates generation.
Definition at line 41 of file quadrature_levelsymmetric_type2.cc.
Referenced by Forest::QuadratureLevelSymType2< dim >::set_ordinates().
   {
     switch (order_)
     {
       case 2:
       {
         tmp_q[0] = 0.577350269189625764509149;
         tmp_w[0] = 1.000000000000000000000000;
         break;
       }
       case 4:
       {
         tmp_q[0] = 0.350021174581540677777041;
         tmp_q[1] = 0.868890300722201205229788;
         tmp_w[0] = 1.0 / 3.0;
         break;
       }
       case 6:
       {
         tmp_q[0] = 0.266635401516704720331535;
         tmp_q[1] = 0.681507726536546927403750;
         tmp_q[2] = 0.926180935517489107558380;
         tmp_w[0] = 0.176126130863383433783565;
         tmp_w[1] = 0.157207202469949899549768;
         break;
       }
       case 8:
       {
         tmp_q[0] = 0.218217890235992381266097;
         tmp_q[1] = 0.577350269189625764509149;
         tmp_q[2] = 0.786795792469443145800830;
         tmp_q[3] = 0.951189731211341853132399;
         tmp_w[0] = 0.120987654320987654320988;
         tmp_w[1] = 0.0907407407407407407407407;
         tmp_w[2] = 0.0925925925925925925925926;
         break;
       }
       case 10:
       {
         tmp_q[0] = 0.189321326478010476671494;
         tmp_q[1] = 0.508881755582618974382711;
         tmp_q[2] = 0.694318887594384317279217;
         tmp_q[3] = 0.839759962236684758403029;
         tmp_q[4] = 0.963490981110468484701598;
         tmp_w[0] = 0.0893031479843567214704325;
         tmp_w[1] = 0.0725291517123655242296233;
         tmp_w[2] = 0.0450437674364086390490892;
         tmp_w[3] = 0.0539281144878369243545650;
         break;
       }
       case 12:
       {
         tmp_q[0] = 0.167212652822713264084504;
         tmp_q[1] = 0.459547634642594690016761;
         tmp_q[2] = 0.628019096642130901034766;
         tmp_q[3] = 0.760021014833664062877138;
         tmp_q[4] = 0.872270543025721502340662;
         tmp_q[5] = 0.971637719251358378302376;
         tmp_w[0] = 0.0707625899700910439766549;
         tmp_w[1] = 0.0558811015648888075828962;
         tmp_w[2] = 0.0373376737588285824652402;
         tmp_w[3] = 0.0502819010600571181385765;
         tmp_w[4] = 0.0258512916557503911218290;
         break;
       }
       case 14:
       {
         tmp_q[0] = 0.151985861461031912404799;
         tmp_q[1] = 0.422156982304796966896263;
         tmp_q[2] = 0.577350269189625764509149;
         tmp_q[3] = 0.698892086775901338963210;
         tmp_q[4] = 0.802226255231412057244328;
         tmp_q[5] = 0.893691098874356784901111;
         tmp_q[6] = 0.976627152925770351762946;
         tmp_w[0] = 0.0579970408969969964063611;
         tmp_w[1] = 0.0489007976368104874582568;
         tmp_w[2] = 0.0227935342411872473257345;
         tmp_w[3] = 0.0394132005950078294492985;
         tmp_w[4] = 0.0380990861440121712365891;
         tmp_w[5] = 0.0258394076418900119611012;
         tmp_w[6] = 0.00826957997262252825269908;
         break;
       }
       case 16:
       {
         tmp_q[0] = 0.138956875067780344591732;
         tmp_q[1] = 0.392289261444811712294197;
         tmp_q[2] = 0.537096561300879079878296;
         tmp_q[3] = 0.650426450628771770509703;
         tmp_q[4] = 0.746750573614681064580018;
         tmp_q[5] = 0.831996556910044145168291;
         tmp_q[6] = 0.909285500943725291652116;
         tmp_q[7] = 0.980500879011739882135849;
         tmp_w[0] = 0.0489872391580385335008367;
         tmp_w[1] = 0.0413295978698440232405505;
         tmp_w[2] = 0.0203032007393652080748070;
         tmp_w[3] = 0.0265500757813498446015484;
         tmp_w[4] = 0.0379074407956004002099321;
         tmp_w[5] = 0.0135295047786756344371600;
         tmp_w[6] = 0.0326369372026850701318409;
         tmp_w[7] = 0.0103769578385399087825920;
         break;
       }
       case 18:
       {
         tmp_q[0] = 0.129344504545924818514086;
         tmp_q[1] = 0.368043816053393605686086;
         tmp_q[2] = 0.504165151725164054411848;
         tmp_q[3] = 0.610662549934881101060239;
         tmp_q[4] = 0.701166884252161909657019;
         tmp_q[5] = 0.781256199495913171286914;
         tmp_q[6] = 0.853866206691488372341858;
         tmp_q[7] = 0.920768021061018932899055;
         tmp_q[8] = 0.983127661236087115272518;
         tmp_w[0] = 0.0422646448843821748535825;
         tmp_w[1] = 0.0376127473827281471532380;
         tmp_w[2] = 0.0122691351637405931037187;
         tmp_w[3] = 0.0324188352558815048715646;
         tmp_w[4] = 0.00664438614619073823264082;
         tmp_w[5] = 0.0312093838436551370068864;
         tmp_w[6] = 0.0160127252691940275641645;
         tmp_w[7] = 0.0200484595308572875885066;
         tmp_w[8] = 0.000111409402059638628382279;
         tmp_w[9] = 0.0163797038522425240494567;
         break;
       }
       case 20:
       {
         tmp_q[0] = 0.120603343036693597409418;
         tmp_q[1] = 0.347574292315847257336779;
         tmp_q[2] = 0.476519266143665680817278;
         tmp_q[3] = 0.577350269189625764509149;
         tmp_q[4] = 0.663020403653288019308783;
         tmp_q[5] = 0.738822561910371432904974;
         tmp_q[6] = 0.807540401661143067193530;
         tmp_q[7] = 0.870852583760463975580977;
         tmp_q[8] = 0.929863938955324566667817;
         tmp_q[9] = 0.985347485558646574628509;
         tmp_w[0] = 0.0370210490604481342320295;
         tmp_w[1] = 0.0332842165376314841003910;
         tmp_w[2] = 0.0111738965965092519614021;
         tmp_w[3] = 0.0245177476959359285418987;
         tmp_w[4] = 0.0135924329650041789567081;
         tmp_w[5] = 0.0318029065936585971501960;
         tmp_w[6] = 0.00685492401402507781062634;
         tmp_w[7] = 0.0308105481755299327227893;
         tmp_w[8] = -0.000139484716502602877593527;
         tmp_w[9] = 0.00544675187330776223879437;
         tmp_w[10] = 0.00474564692642379971238396;
         tmp_w[11] = 0.0277298541009064049325246;
         break;
       }
       default:
       {
         // change this for an error flag at exit the function
         std::cout
             << "Error:\n" << "  Quadrature levelsymmetric type 2(" << order_
             << ") is not implemented for SN" << std::endl
             << "  different from 2, 4, 6, 8, 10, 12, 14, 16, 18 and 20."
             << std::endl
             << "  Thus 'abort()' is called to terminate the program execution."
             << std::endl << std::endl;
         abort ();
       }
     }
   }
template<int dim> void Forest::QuadratureLevelSymType2< dim >::get_weight_dist (std::vector< unsigned int > & w_dist) const private
S_2 weight distribution {1};.
S_4 weight distribution {1, 1,1};
S_6 weight distribution {1, 2,2, 1,2,1};
S_8 weight distribution {1, 2,2, 2,3,2, 1,2,2,1};
S_10 weight distribution {1, 2,2, 3,4,3, 2,4,4,2, 1,2,3,2,1};
S_12 weight distribution {1, 2,2, 3,4,3, 3,5,5,3, 2,4,5,4,2, 1,2,3,3,2,1};
S_14 weight distribution {1, 2,2, 3,5,3, 4,6,6,4, 3,6,7,6,3, 2,5,6,6,5,2, 1,2,3,4,3,2,1};
S_16 weight distribution {1, 2,2, 3,5,3, 4,6,6,4, 4,7,8,7,4, 3,6,8,8,6,3, 2,5,6,7,6,5,2, 1,2,3,4,4,3,2,1};
S_18 weight distribution {1, 2, 2, 3, 6, 3, 4, 7, 7, 4, 5, 8, 9, 8, 5, 4, 8, 10, 10, 8, 4, 3, 7, 9, 10, 9, 7, 3, 2, 6, 7, 8, 8, 7, 6, 2, 1, 2, 3, 4, 5, 4, 3, 2, 1};
S_20 weight distribution {1, 2, 2, 3, 6, 3, 4, 7, 7, 4, 5, 8, 10, 8, 5, 5, 9, 11, 11, 9, 5, 4, 8, 11, 12, 11, 8, 4, 3, 7, 10, 11, 11, 10, 7, 3, 2, 6, 7, 8, 9, 8, 7, 6, 2, 1, 2, 3, 4, 5, 5, 4, 3, 2, 1};
Definition at line 301 of file quadrature_levelsymmetric_type2.cc.
Referenced by Forest::QuadratureLevelSymType2< dim >::set_ordinates().
   {
     switch (this->order)
     {
       case 2:
         w_dist =
         {
           1};
         break;
         case 4:
         w_dist =
         {
           1,
           1,1};
         break;
         case 6:
         w_dist =
         {
           1,
           2,2,
           1,2,1};
         break;
         case 8:
         w_dist =
         {
           1,
           2,2,
           2,3,2,
           1,2,2,1};
         break;
         case 10:
         w_dist =
         {
           1,
           2,2,
           3,4,3,
           2,4,4,2,
           1,2,3,2,1};
         break;
         case 12:
         w_dist =
         {
           1,
           2,2,
           3,4,3,
           3,5,5,3,
           2,4,5,4,2,
           1,2,3,3,2,1};
         break;
         case 14:
         w_dist =
         {
           1,
           2,2,
           3,5,3,
           4,6,6,4,
           3,6,7,6,3,
           2,5,6,6,5,2,
           1,2,3,4,3,2,1};
         break;
         case 16:
         w_dist =
         {
           1,
           2,2,
           3,5,3,
           4,6,6,4,
           4,7,8,7,4,
           3,6,8,8,6,3,
           2,5,6,7,6,5,2,
           1,2,3,4,4,3,2,1};
         break;
         case 18:
         w_dist =
         {
           1,
           2, 2,
           3, 6, 3,
           4, 7, 7, 4,
           5, 8, 9, 8, 5,
           4, 8, 10, 10, 8, 4,
           3, 7, 9, 10, 9, 7, 3,
           2, 6, 7, 8, 8, 7, 6, 2,
           1, 2, 3, 4, 5, 4, 3, 2, 1};
         break;
         case 20:
         w_dist =
         {
           1,
           2, 2,
           3, 6, 3,
           4, 7, 7, 4,
           5, 8, 10, 8, 5,
           5, 9, 11, 11, 9, 5,
           4, 8, 11, 12, 11, 8, 4,
           3, 7, 10, 11, 11, 10, 7, 3,
           2, 6, 7, 8, 9, 8, 7, 6, 2,
           1, 2, 3, 4, 5, 5, 4, 3, 2, 1};
         break;
       }
     }
template<int dim> double Forest::QuadratureLevelSymType2< dim >::get_dimension_weight () const inline private
Definition at line 70 of file quadrature_levelsymmetric_type2.h.
Referenced by Forest::QuadratureLevelSymType2< dim >::QuadratureLevelSymType2().
     {
       return ((dim == 1) ? 0.5 : (dim == 2) ? 0.25 : 0.125);
     }
template<> void Forest::QuadratureLevelSymType2< 1 >::set_ordinates () private
Definition at line 446 of file quadrature_levelsymmetric_type2.cc.
   {
     std::cout << "exception is thrown" << std::endl;
     //Assert_msg(false, "ExcNotImplemented");
   }
template<int dim> void Forest::QuadratureBase< dim >::set_n_octants () protected inherited
Todo:
document me
Definition at line 36 of file quadrature_base.cc.
Referenced by Forest::QuadratureBase< dim >::QuadratureBase().
   {
     n_octants = std::pow (2, dim);
   }
template<int dim> void Forest::QuadratureBase< dim >::set_n_angles () protected inherited
Todo:
document me
Definition at line 43 of file quadrature_base.cc.
Referenced by Forest::QuadratureBase< dim >::QuadratureBase().
   {
     n_angles = get_n_angles_per_octant () * get_n_octants ();
   }
template<int dim> void Forest::QuadratureBase< dim >::set_octant_sign () protected inherited
Assigning the signs for each octant.
Todo:
document me
We will run over the eight octants assigning the signs
* axis   x y z
* o1   = + + +
* o2   = - + +
* o3   = - - +
* o4   = + - +
* o5   = + + -
* o6   = - + -
* o7   = - - -
* o8   = + - -
*
Definition at line 65 of file quadrature_base.cc.
Referenced by Forest::QuadratureBase< dim >::QuadratureBase().
   {
     // allocate the memory for the maximum possible
     const unsigned int max_s_dim = 3;
     const unsigned int max_octants = 8;
     octant_sign.resize (max_octants, std::vector<double> (max_s_dim));
     // first
     octant_sign[0][0] = +1.0;
     octant_sign[0][1] = +1.0;
     octant_sign[0][2] = +1.0;
     // second
     octant_sign[1][0] = -1.0;
     octant_sign[1][1] = +1.0;
     octant_sign[1][2] = +1.0;
     // third
     octant_sign[2][0] = -1.0;
     octant_sign[2][1] = -1.0;
     octant_sign[2][2] = +1.0;
     // fourth
     octant_sign[3][0] = +1.0;
     octant_sign[3][1] = -1.0;
     octant_sign[3][2] = +1.0;
     // fifth
     octant_sign[4][0] = +1.0;
     octant_sign[4][1] = +1.0;
     octant_sign[4][2] = -1.0;
     // sixth
     octant_sign[5][0] = -1.0;
     octant_sign[5][1] = +1.0;
     octant_sign[5][2] = -1.0;
     // seventh
     octant_sign[6][0] = -1.0;
     octant_sign[6][1] = -1.0;
     octant_sign[6][2] = -1.0;
     // eighth
     octant_sign[7][0] = +1.0;
     octant_sign[7][1] = -1.0;
     octant_sign[7][2] = -1.0;
   }
template<int dim> void Forest::QuadratureBase< dim >::set_all_angles (double angular_weight) protected inherited
Todo:
document me
Definition at line 107 of file quadrature_base.cc.
Referenced by Forest::QuadratureChebyshevLegendre< dim >::QuadratureChebyshevLegendre(), Forest::QuadratureGaussChebyshev< dim >::QuadratureGaussChebyshev(), Forest::QuadratureLevelSymType1< dim >::QuadratureLevelSymType1(), and Forest::QuadratureLevelSymType2< dim >::QuadratureLevelSymType2().
   {
     for (unsigned int o = 0; o < n_octants; ++o)
     {
       for (unsigned int a = 0; a < n_angles_per_octant; ++a)
       {
         for (unsigned int d = 0; d < dim; ++d)
         {
           xx[get_index (o, a)][d] = octant_sign[o][d] * xx[a][d];
         }
       }
     }
     for (unsigned int a = 0; a < n_angles_per_octant; ++a)
     {
       ww[get_index (0, a)] = ww[a] * dimension_weight;
     }
     for (unsigned int o = 1; o < n_octants; ++o)
     {
       for (unsigned int a = 0; a < n_angles_per_octant; ++a)
       {
         ww[get_index (o, a)] = ww[a];
       }
     }
   }
template<int dim> void Forest::QuadratureBase< dim >::set_bc_map () protected inherited
j_ord = bc_map(f, i_ord), with
Todo:
document me
\(\Omega_{\text{out}} = \Omega_{\text{in}} - 2 n_f (\Omega_{\text{in}} \cdot n_f) \)
the normals are used in the order specified in http://www.dealii.org/developer/doxygen/deal.II/structGeometryInfo.html
"normals pointing in -x, x, -y, y, -z, z direction".
Todo:
Should this function be made independent of dealii? Think about it.
Definition at line 150 of file quadrature_base.cc.
Referenced by Forest::QuadratureChebyshevLegendre< dim >::QuadratureChebyshevLegendre(), Forest::QuadratureGaussChebyshev< dim >::QuadratureGaussChebyshev(), Forest::QuadratureGaussLegendre< dim >::QuadratureGaussLegendre(), Forest::QuadratureLevelSymType1< dim >::QuadratureLevelSymType1(), and Forest::QuadratureLevelSymType2< dim >::QuadratureLevelSymType2().
   {
     const unsigned int faces_per_cell = 2 * dim;
     in2out.resize (faces_per_cell, std::vector<unsigned int> (n_angles, -1));
     // initialize the normal vectors to all the faces
     std::vector<std::vector<double> > normals;
     normals.resize (faces_per_cell, std::vector<double> (dim, 0.));
     for (unsigned int f = 0; f < faces_per_cell; ++f)
     {
       if (dim == 1)
       {
         if (f % 2 == 0)
         {
           normals[f][0] = -1.;
         }
         else
         {
           normals[f][0] = +1.;
         }
       }
       else
       {
         if (f % 2 == 0)
         {
           normals[f][(int) f / dim] = -1.;
         }
         else
         {
           normals[f][(int) f / dim] = +1.;
         }
       }
     }
     const double EPS = 1.e-10;
     std::vector<double> omega_out (dim);
     for (unsigned int f = 0; f < faces_per_cell; ++f)
     {
       for (unsigned int dir_in = 0; dir_in < n_angles; ++dir_in)
       {
         /* We calculate the vector we should look for. */
         double Omega_dot_n = 0.;
         for (unsigned int i = 0; i < dim; ++i)
           Omega_dot_n += xx[dir_in][i] * normals[f][i];
         /* If f is an out-going boundary for i_ord we don't have to calculate
            which one is the incoming flux. */
         if (Omega_dot_n < 0 and std::abs (Omega_dot_n) > EPS)
         {
           /* Calculating the norm of the difference. */
           for (unsigned int i = 0; i < dim; ++i)
           {
             omega_out[i] = xx[dir_in][i] - 2 * normals[f][i] * Omega_dot_n;
           }
           for (unsigned int dir = 0; dir < n_angles; ++dir)
           {
             /* Calculating the norm of the difference */
             double diff_ij = 0;
             for (unsigned int i = 0; i < dim; ++i)
             {
               diff_ij += std::pow (omega_out[i] - xx[dir][i], 2);
             }
             /* If the norm is small enough, we have found the vector
                and stop the j_ord loop. */
             if (diff_ij < EPS)
             {
               in2out[f][dir_in] = dir;
               break;
             }
           }
         }
       }
     }
     bool verbose = false;
     if (verbose)
     {
       std::cout << std::endl << "printing inside set_bc_map" << std::endl;
       for (unsigned int f = 0; f < faces_per_cell; ++f)
       {
         std::cout << "normals[" << f << "] = ";
         for (unsigned int i = 0; i < dim; ++i)
         {
           std::cout << normals[f][i] << " ";
         }
         std::cout << std::endl;
       }
       for (unsigned int i_ord = 0; i_ord < n_angles; ++i_ord)
       {
         std::cout << "xx[" << i_ord << "] = ";
         for (unsigned int i = 0; i < dim; ++i)
         {
           std::cout << xx[i_ord][i] << " ";
         }
         std::cout << std::endl;
       }
       std::cout << "bc_map = \n";
       for (unsigned int f = 0; f < faces_per_cell; ++f)
       {
         std::cout << " face " << f << " = ";
         for (unsigned int i_ord = 0; i_ord < n_angles; ++i_ord)
         {
           std::cout << in2out[f][i_ord] << " ";
         }
         std::cout << std::endl;
       }
       std::cout << std::endl;
       std::cout << std::endl;
     }
   }
template<int dim> void Forest::QuadratureBase< dim >::set_in_from_out () protected inherited
j_ord = bc_map(f, i_ord), with
Todo:
document me
\(\Omega_{\text{in}} = \Omega_{\text{out}} - 2 n_f (\Omega_{\text{out}} \cdot n_f) \)
the normals are used in the order specified in http://www.dealii.org/developer/doxygen/deal.II/structGeometryInfo.html
"normals pointing in -x, x, -y, y, -z, z direction".
Todo:
Should this function be made independent of dealii? Think about it.
Definition at line 283 of file quadrature_base.cc.
Referenced by Forest::QuadratureChebyshevLegendre< dim >::QuadratureChebyshevLegendre(), Forest::QuadratureGaussChebyshev< dim >::QuadratureGaussChebyshev(), Forest::QuadratureGaussLegendre< dim >::QuadratureGaussLegendre(), Forest::QuadratureLevelSymType1< dim >::QuadratureLevelSymType1(), and Forest::QuadratureLevelSymType2< dim >::QuadratureLevelSymType2().
   {
     const unsigned int faces_per_cell = 2 * dim;
     out2in.resize (faces_per_cell, std::vector<unsigned int> (n_angles, -1));
     // initialize the normal vectors to all the faces
     std::vector<std::vector<double> > normals;
     normals.resize (faces_per_cell, std::vector<double> (dim, 0.));
     for (unsigned int f = 0; f < faces_per_cell; ++f)
     {
       if (dim == 1)
       {
         if (f % 2 == 0)
         {
           normals[f][0] = -1.;
         }
         else
         {
           normals[f][0] = +1.;
         }
       }
       else
       {
         if (f % 2 == 0)
         {
           normals[f][(int) f / dim] = -1.;
         }
         else
         {
           normals[f][(int) f / dim] = +1.;
         }
       }
     }
     const double EPS = 1.e-6;
     std::vector<double> omega_in (dim);
     for (unsigned int f = 0; f < faces_per_cell; ++f)
     {
       for (unsigned int dir_out = 0; dir_out < n_angles; ++dir_out)
       {
         // We calculate the vector we should look for.
         double Omega_dot_n = 0.;
         for (unsigned int i = 0; i < dim; ++i)
         {
           Omega_dot_n += xx[dir_out][i] * normals[f][i];
         }
         // if Omega_dot_n > 0 out_dir is outgoing flux at face f
         if (Omega_dot_n > 0 and std::abs (Omega_dot_n) > EPS)
         {
           for (unsigned int i = 0; i < dim; ++i)
           {
             omega_in[i] = xx[dir_out][i] - 2 * normals[f][i] * Omega_dot_n;
           }
           for (unsigned int dir = 0; dir < n_angles; ++dir)
           {
             // calculating the norm of the difference
             double diff_ij = 0;
             for (unsigned int i = 0; i < dim; ++i)
             {
               diff_ij += std::pow (omega_in[i] - xx[dir][i], 2);
             }
             // if the norm is small enough, we have found the vector
             // and stop the in_dir loop
             if (diff_ij < EPS)
             {
               out2in[f][dir_out] = dir;
               break;
             }
           }
         }
       }
     }
   }
template<int dim> void Forest::QuadratureBase< dim >::set_a_order (unsigned int a_order_) inline protected inherited
Todo:
document me
Definition at line 85 of file quadrature_base.h.
Referenced by Forest::QuadratureChebyshevLegendre< dim >::QuadratureChebyshevLegendre(), Forest::QuadratureGaussChebyshev< dim >::QuadratureGaussChebyshev(), Forest::QuadratureLevelSymType1< dim >::QuadratureLevelSymType1(), and Forest::QuadratureLevelSymType2< dim >::QuadratureLevelSymType2().
     {
       a_order = a_order_;
     }
template<int dim> void Forest::QuadratureBase< dim >::set_p_order (unsigned int p_order_) inline protected inherited
Todo:
document me
Definition at line 92 of file quadrature_base.h.
Referenced by Forest::QuadratureChebyshevLegendre< dim >::QuadratureChebyshevLegendre(), Forest::QuadratureGaussChebyshev< dim >::QuadratureGaussChebyshev(), Forest::QuadratureLevelSymType1< dim >::QuadratureLevelSymType1(), and Forest::QuadratureLevelSymType2< dim >::QuadratureLevelSymType2().
     {
       p_order = p_order_;
     }
template<int dim> void Forest::QuadratureBase< dim >::set_order (unsigned int order_) inline protected inherited
Definition at line 97 of file quadrature_base.h.
Referenced by Forest::QuadratureChebyshevLegendre< dim >::QuadratureChebyshevLegendre(), Forest::QuadratureGaussChebyshev< dim >::QuadratureGaussChebyshev(), Forest::QuadratureLevelSymType1< dim >::QuadratureLevelSymType1(), and Forest::QuadratureLevelSymType2< dim >::QuadratureLevelSymType2().
     {
       order = order_;
     }
template<int dim> void Forest::QuadratureBase< dim >::set_n_leg_moments (unsigned int order_) inline protected inherited
Todo:
document me
Definition at line 104 of file quadrature_base.h.
Referenced by Forest::QuadratureChebyshevLegendre< dim >::QuadratureChebyshevLegendre(), Forest::QuadratureGaussChebyshev< dim >::QuadratureGaussChebyshev(), Forest::QuadratureLevelSymType1< dim >::QuadratureLevelSymType1(), and Forest::QuadratureLevelSymType2< dim >::QuadratureLevelSymType2().
     {
       n_leg_moments = order_ / 2;
     }
template<int dim> unsigned int Forest::QuadratureBase< dim >::get_n_angles () const inline inherited
Todo:
document me
Definition at line 115 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::check_ordinates().
     {
       return n_angles;
     }
template<int dim> unsigned int Forest::QuadratureBase< dim >::get_n_octants () const inline inherited
Todo:
document me
Definition at line 122 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::set_n_angles().
     {
       return n_octants;
     }
template<int dim> unsigned int Forest::QuadratureBase< dim >::get_n_angles_per_octant () const inline inherited
Todo:
document me
Definition at line 129 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::set_n_angles().
     {
       return n_angles_per_octant;
     }
template<int dim> unsigned int Forest::QuadratureBase< dim >::get_a_order () const inline inherited
Todo:
document me
Definition at line 136 of file quadrature_base.h.
     {
       return a_order;
     }
template<int dim> unsigned int Forest::QuadratureBase< dim >::get_p_order () const inline inherited
Todo:
document me
Definition at line 143 of file quadrature_base.h.
     {
       return p_order;
     }
template<int dim> unsigned int Forest::QuadratureBase< dim >::get_order () const inline inherited
Todo:
document me
Definition at line 150 of file quadrature_base.h.
     {
       return order;
     }
template<int dim> unsigned int Forest::QuadratureBase< dim >::get_n_leg_moments () const inline inherited
Todo:
document me
Definition at line 157 of file quadrature_base.h.
     {
       return n_leg_moments;
     }
template<int dim> const std::vector<std::vector<double> >& Forest::QuadratureBase< dim >::get_q () const inline inherited
Return quadrature points \(q(:) \).
Definition at line 166 of file quadrature_base.h.
     {
       return xx;
     }
template<int dim> const std::vector<double>& Forest::QuadratureBase< dim >::get_q (unsigned int a) const inline inherited
Return quadrature point \(q \).
Parameters
a Angle position
Definition at line 176 of file quadrature_base.h.
     {
       return xx[a];
     }
template<int dim> double Forest::QuadratureBase< dim >::get_q (unsigned int a, unsigned int d) const inline inherited
Return quadrature point \(q(d) \).
Parameters
a Angle within octant
d which coordinate
Definition at line 187 of file quadrature_base.h.
     {
       return xx[a][d];
     }
template<int dim> const std::vector<double>& Forest::QuadratureBase< dim >::get_w () const inline inherited
Return the weights.
Definition at line 197 of file quadrature_base.h.
     {
       return ww;
     }
template<int dim> double Forest::QuadratureBase< dim >::get_w (unsigned int i) const inline inherited
Return the weight.
Parameters
i Angle within octant
Definition at line 207 of file quadrature_base.h.
     {
       return ww[i];
     }
template<int dim> unsigned int Forest::QuadratureBase< dim >::get_out_ind (unsigned int face_, unsigned int in_angle_ind_) const inline inherited
Returns the index of the outgoing direction associated with the incoming direction in_angle_ind at the face face.
Parameters
face_
in_angle_ind_
Returns
out_angle_ind_
Definition at line 221 of file quadrature_base.h.
     {
       return in2out[face_][in_angle_ind_];
     }
template<int dim> double Forest::QuadratureBase< dim >::get_octant_sign (unsigned int o, unsigned int coordinate) const inline inherited
Todo:
document me
Definition at line 229 of file quadrature_base.h.
     {
       return octant_sign[o][coordinate];
     }
template<int dim> unsigned int Forest::QuadratureBase< dim >::get_index (unsigned int o, unsigned int a) const inline inherited
Return cardinal angle index.
Parameters
o Octant index
a Angle within octant
Definition at line 241 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::set_all_angles().
     {
       return o * n_angles_per_octant + a;
     }
template<int dim> bool Forest::QuadratureBase< dim >::valid_index (unsigned int o, unsigned int a) const inline inherited
Are the indices valid?
Parameters
o Octant index
a Angle within octant
Definition at line 253 of file quadrature_base.h.
     {
       return (o < n_octants) and (a < n_angles_per_octant);
     }
template<int dim> void Forest::QuadratureBase< dim >::disp () const inherited
Displaying the ordinates and the weights in one dimension.
Todo:
document me
Definition at line 363 of file quadrature_base.cc.
Referenced by Forest::QuadratureBase< dim >::valid_index().
   {
     std::cout << "Quadrature <" << name << "> being used:" << std::endl;
     for (unsigned int i = 0; i < n_angles; ++i)
     {
       std::cout << "    angle " << std::setw (3) << i << ": " << "    ww[i] = "
                 << std::setw (8) << ww[i] << ", " << "    xx[i] = (";
       for (unsigned int d = 0; d < dim - 1; ++d)
       {
         std::cout << std::setw (9) << xx[i][d] << " , ";
       }
       std::cout << std::setw (9) << xx[i][dim - 1] << "); ";
       std::cout << std::endl;
     }
     std::cout << std::endl;
   }
template<int dim> void Forest::QuadratureBase< dim >::check_ordinates () const inherited
Todo:
document me
Referenced by Forest::QuadratureBase< dim >::valid_index().
template<> void Forest::QuadratureBase< 1 >::check_ordinates () const inherited
Definition at line 383 of file quadrature_base.cc.
   {
     // double tol = 1.e-8;
     // checking if the sum of all weights is equal to 2.0 up to a tolerance of tol
     double sum = 0.0;
     for (unsigned int i = 0; i < this->get_n_angles (); ++i)
     {
       sum += ww[i];
     }
     //Assert_msg(std::abs(sum-2.0) < tol,"Sum of all weights is different from 2.0");
   }
template<int dim> double Forest::QuadratureBase< dim >::memory_consumption () const inline inherited
Todo:
document me
Definition at line 271 of file quadrature_base.h.
     {
       double memory_consumption = 0;
       memory_consumption += sizeof(xx) + sizeof(ww) + sizeof(octant_sign)
                             + sizeof(in2out);
       return memory_consumption;
     }
Member Data Documentation
template<int dim> unsigned int Forest::QuadratureLevelSymType2< dim >::n_cosines private
Definition at line 53 of file quadrature_levelsymmetric_type2.h.
Referenced by Forest::QuadratureLevelSymType2< dim >::set_ordinates().
template<int dim> unsigned int Forest::QuadratureBase< dim >::a_order protected inherited
Definition at line 42 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::get_a_order().
template<int dim> unsigned int Forest::QuadratureBase< dim >::p_order protected inherited
Definition at line 43 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::get_p_order().
template<int dim> unsigned int Forest::QuadratureBase< dim >::order protected inherited
Definition at line 44 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::get_order(), Forest::QuadratureGaussChebyshev< dim >::get_weight_dist(), Forest::QuadratureLevelSymType2< dim >::get_weight_dist(), Forest::QuadratureLevelSymType1< dim >::get_weight_dist(), Forest::QuadratureChebyshevLegendre< dim >::QuadratureChebyshevLegendre(), Forest::QuadratureGaussChebyshev< dim >::QuadratureGaussChebyshev(), Forest::QuadratureGaussChebyshev< dim >::set_ordinates(), Forest::QuadratureLevelSymType2< dim >::set_ordinates(), and Forest::QuadratureLevelSymType1< dim >::set_ordinates().
template<int dim> unsigned int Forest::QuadratureBase< dim >::n_angles_per_octant protected inherited
Definition at line 46 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::get_n_angles_per_octant(), Forest::QuadratureBase< dim >::set_all_angles(), Forest::QuadratureGaussChebyshev< dim >::set_ordinates(), Forest::QuadratureLevelSymType2< dim >::set_ordinates(), and Forest::QuadratureLevelSymType1< dim >::set_ordinates().
template<int dim> std::string Forest::QuadratureBase< dim >::name protected inherited
Definition at line 47 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::disp().
template<int dim> unsigned int Forest::QuadratureBase< dim >::n_octants protected inherited
Definition at line 48 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::get_n_octants(), Forest::QuadratureBase< dim >::set_all_angles(), Forest::QuadratureBase< dim >::set_n_octants(), and Forest::QuadratureChebyshevLegendre< dim >::set_ordinates().
template<int dim> unsigned int Forest::QuadratureBase< dim >::n_angles protected inherited
Definition at line 49 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::disp(), Forest::QuadratureBase< dim >::get_n_angles(), Forest::QuadratureBase< dim >::QuadratureBase(), Forest::QuadratureBase< dim >::set_bc_map(), Forest::QuadratureBase< dim >::set_in_from_out(), Forest::QuadratureBase< dim >::set_n_angles(), and Forest::QuadratureGaussLegendre< dim >::set_ordinates().
template<int dim> unsigned int Forest::QuadratureBase< dim >::n_leg_moments protected inherited
Definition at line 50 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::get_n_leg_moments().
template<int dim> std::vector<std::vector<double> > Forest::QuadratureBase< dim >::octant_sign protected inherited
Definition at line 52 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::memory_consumption(), Forest::QuadratureBase< dim >::set_all_angles(), and Forest::QuadratureBase< dim >::set_octant_sign().
template<int dim> std::vector<std::vector<double> > Forest::QuadratureBase< dim >::xx protected inherited
Definition at line 54 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::disp(), Forest::QuadratureBase< dim >::get_q(), Forest::QuadratureBase< dim >::memory_consumption(), Forest::QuadratureBase< dim >::QuadratureBase(), Forest::QuadratureBase< dim >::set_all_angles(), Forest::QuadratureBase< dim >::set_bc_map(), Forest::QuadratureBase< dim >::set_in_from_out(), Forest::QuadratureGaussChebyshev< dim >::set_ordinates(), Forest::QuadratureLevelSymType2< dim >::set_ordinates(), Forest::QuadratureLevelSymType1< dim >::set_ordinates(), Forest::QuadratureChebyshevLegendre< dim >::set_ordinates(), and Forest::QuadratureGaussLegendre< dim >::set_ordinates().
template<int dim> std::vector<double> Forest::QuadratureBase< dim >::ww protected inherited
Definition at line 55 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::check_ordinates(), Forest::QuadratureBase< dim >::disp(), Forest::QuadratureBase< dim >::get_w(), Forest::QuadratureBase< dim >::QuadratureBase(), Forest::QuadratureBase< dim >::set_all_angles(), Forest::QuadratureGaussChebyshev< dim >::set_ordinates(), Forest::QuadratureLevelSymType2< dim >::set_ordinates(), Forest::QuadratureLevelSymType1< dim >::set_ordinates(), Forest::QuadratureChebyshevLegendre< dim >::set_ordinates(), and Forest::QuadratureGaussLegendre< dim >::set_ordinates().
template<int dim> std::vector<std::vector<unsigned int> > Forest::QuadratureBase< dim >::in2out protected inherited
Definition at line 57 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::set_bc_map().
template<int dim> std::vector<std::vector<unsigned int> > Forest::QuadratureBase< dim >::out2in inherited
Definition at line 111 of file quadrature_base.h.
Referenced by Forest::QuadratureBase< dim >::set_in_from_out().
The documentation for this class was generated from the following files:
/home/lns/Codes/forest-public/mylib/include/angle/quadrature_levelsymmetric_type2.h
/home/lns/Codes/forest-public/mylib/src/angle/quadrature_levelsymmetric_type2.cc