FOREST: dealii::DoFRenumbering Namespace Reference
dealii::DoFRenumbering Namespace Reference
Namespaces
boost
Functions
template<class DH >
void compute_downstream_cells (std::vector< typename DH::active_cell_iterator > &ordered_cells, std::vector< std::vector< bool > > &incoming_face, const DH &dof_handler, const Point< DH::space_dimension > &direction)
compute_downstream_cells
template<class DH >
void compute_downstream_new (std::vector< types::global_dof_index > &new_indices, std::vector< types::global_dof_index > &reverse, const DH &dof, const Point< DH::space_dimension > &direction)
compute_downstream_new
template void compute_downstream_cells< DoFHandler< 1 > > (std::vector< typename DoFHandler< 1 >::active_cell_iterator > &ordered_cells, std::vector< std::vector< bool > > &incoming_face, const DoFHandler< 1 > &dof_handler, const Point< DoFHandler< 1 >::space_dimension > &direction)
template void compute_downstream_cells< DoFHandler< 2 > > (std::vector< typename DoFHandler< 2 >::active_cell_iterator > &ordered_cells, std::vector< std::vector< bool > > &incoming_face, const DoFHandler< 2 > &dof_handler, const Point< DoFHandler< 2 >::space_dimension > &direction)
template void compute_downstream_cells< DoFHandler< 3 > > (std::vector< typename DoFHandler< 3 >::active_cell_iterator > &ordered_cells, std::vector< std::vector< bool > > &incoming_face, const DoFHandler< 3 > &dof_handler, const Point< DoFHandler< 3 >::space_dimension > &direction)
template void compute_downstream_new< DoFHandler< 1 > > (std::vector< types::global_dof_index > &new_indices, std::vector< types::global_dof_index > &reverse, const DoFHandler< 1 > &dof_handler, const Point< DoFHandler< 1 >::space_dimension > &direction)
template void compute_downstream_new< DoFHandler< 2 > > (std::vector< types::global_dof_index > &new_indices, std::vector< types::global_dof_index > &reverse, const DoFHandler< 2 > &dof_handler, const Point< DoFHandler< 2 >::space_dimension > &direction)
template void compute_downstream_new< DoFHandler< 3 > > (std::vector< types::global_dof_index > &new_indices, std::vector< types::global_dof_index > &reverse, const DoFHandler< 3 > &dof_handler, const Point< DoFHandler< 3 >::space_dimension > &direction)
Function Documentation
template<class DH > void dealii::DoFRenumbering::compute_downstream_cells (std::vector< typename DH::active_cell_iterator > & ordered_cells, std::vector< std::vector< bool > > & incoming_face, const DH & dof_handler, const Point< DH::space_dimension > & direction)
compute_downstream_cells
Definition at line 125 of file downstream_new.cc.
Referenced by compute_downstream_new(), Forest::TransOpMatrixFree< dim >::TransOpMatrixFree(), and Forest::TransOpMatrixFreePre< dim >::TransOpMatrixFreePre().
     {
       // we get the number of cells and resize the containers
 #if DEAL_II_VERSION_GTE(8,4,0)
       unsigned int n_cells = dof_handler.get_triangulation ().n_active_cells ();
 #else
       unsigned int n_cells = dof_handler.get_tria ().n_active_cells ();
 #endif
       ordered_cells.resize (n_cells);
       incoming_face.resize (n_cells,
           std::vector<bool>(GeometryInfo<DH::space_dimension>::faces_per_cell, false));
       // initialize and fill the boost graph for the connections
       boost::boosttypes::Graph graph (n_cells);
       boost::internal::downstream_graph (graph, incoming_face, dof_handler, direction);
       // Then we reorder the graph with a topologycal sort
       typedef std::vector<boost::boosttypes::Vertex> container;
       container c;
       ::boost::topological_sort (graph, std::back_inserter (c));
       // here we should invert the ordering to pass to ordered_cells
       std::vector<unsigned int> invert_perm (n_cells);
       container::reverse_iterator it = c.rbegin ();
       for (unsigned int i = 0; i < n_cells; ++i, ++it)
       {
         invert_perm[*it] = i;
       }
       // store the ordered cells
       typename DH::active_cell_iterator cell = dof_handler.begin_active ();
       for (unsigned int i = 0; i < ordered_cells.size (); ++i, ++cell)
       {
         ordered_cells[invert_perm[i]] = cell;
       }
     }
template<class DH > void dealii::DoFRenumbering::compute_downstream_new (std::vector< types::global_dof_index > & new_indices, std::vector< types::global_dof_index > & reverse, const DH & dof_handler, const Point< DH::space_dimension > & direction)
compute_downstream_new
Definition at line 168 of file downstream_new.cc.
Referenced by Forest::TransOpMatrixBuilt< dim >::setup_angular_dof_handler().
     {
       // we get the number of cells and initialize the containers
 #if DEAL_II_VERSION_GTE(8,4,0)
       unsigned int n_cells = dof_handler.get_triangulation ().n_active_cells ();
 #else
       unsigned int n_cells = dof_handler.get_tria ().n_active_cells ();
 #endif
       std::vector<typename DH::active_cell_iterator> ordered_cells (n_cells);
       std::vector<std::vector<bool> > dummy_incoming_face (n_cells,
           std::vector<bool>(GeometryInfo<DH::space_dimension>::faces_per_cell, false));
       // compute the ordered cells
       compute_downstream_cells (ordered_cells, dummy_incoming_face, dof_handler, direction);
       // this should be like this to move information from ordered cells
       // to new_indices and reverse, in order to be used with the sparse matrix
       compute_cell_wise (new_indices, reverse, dof_handler, ordered_cells);
     }
template void dealii::DoFRenumbering::compute_downstream_cells< DoFHandler< 1 > > (std::vector< typename DoFHandler< 1 >::active_cell_iterator > & ordered_cells, std::vector< std::vector< bool > > & incoming_face, const DoFHandler< 1 > & dof_handler, const Point< DoFHandler< 1 >::space_dimension > & direction)
template void dealii::DoFRenumbering::compute_downstream_cells< DoFHandler< 2 > > (std::vector< typename DoFHandler< 2 >::active_cell_iterator > & ordered_cells, std::vector< std::vector< bool > > & incoming_face, const DoFHandler< 2 > & dof_handler, const Point< DoFHandler< 2 >::space_dimension > & direction)
template void dealii::DoFRenumbering::compute_downstream_cells< DoFHandler< 3 > > (std::vector< typename DoFHandler< 3 >::active_cell_iterator > & ordered_cells, std::vector< std::vector< bool > > & incoming_face, const DoFHandler< 3 > & dof_handler, const Point< DoFHandler< 3 >::space_dimension > & direction)
template void dealii::DoFRenumbering::compute_downstream_new< DoFHandler< 1 > > (std::vector< types::global_dof_index > & new_indices, std::vector< types::global_dof_index > & reverse, const DoFHandler< 1 > & dof_handler, const Point< DoFHandler< 1 >::space_dimension > & direction)
template void dealii::DoFRenumbering::compute_downstream_new< DoFHandler< 2 > > (std::vector< types::global_dof_index > & new_indices, std::vector< types::global_dof_index > & reverse, const DoFHandler< 2 > & dof_handler, const Point< DoFHandler< 2 >::space_dimension > & direction)
template void dealii::DoFRenumbering::compute_downstream_new< DoFHandler< 3 > > (std::vector< types::global_dof_index > & new_indices, std::vector< types::global_dof_index > & reverse, const DoFHandler< 3 > & dof_handler, const Point< DoFHandler< 3 >::space_dimension > & direction)