FOREST: Forest Namespace Reference
Forest Namespace Reference
Classes related to algebra (matrix/vector)
Classes
class BoundaryValues
Boundary conditions for the system.
class BoundaryValuesFactory
Factory to create boundary values (w/o matrix)
class CmdOption
We use this class to parse the command line arguments.
class Core
Container for the data of the core.
class DiffFactory
Factory to create Diffusion operator (with/without matrix)
class DiffOp
Diffusion operator and sweep, base class.
class DiffOpMatrixBuilt
Diffusion operator and sweep, matrix-built version.
class DiffOpMatrixFree
Diffusion operator and sweep, matrix-free version.
class DirectionsToMoments
Directions to Moments class.
class EigenFissionDensity
Eigenvalue problem for fission density.
class EigenProb
Eigenvalue problem; base class.
class EigenProbFactory
Factory class creating EigenProbPtr.
class EigenSolver
Eigenvalue problem solver.
class EigenSolverSLEPC
class EigenStandard
Eigenvalue problem in standard form.
class EqDiffusion
Neutron diffusion equation.
class EqFactory
Factory to create equations (transport/diffusion, with/without matrix)
class EqPrec
Preconditioner structure to wrap the .prec() member of equation inside with a vmult use by deal.II.
class EqSolverWG
Class implementing the Solver.
class EqTransport
Neutron transport equation.
class Equation
Equation, base class.
class ExtractBV
Extracts boundary values for the system.
class FissionSource
Fission Source operator, base class.
class FissionSourceFactory
Factory to create fission source operators (w/o matrix)
class FissionSourceMatrixBuilt
Fission Source operator, matrix-built version.
class FissionSourceMatrixFree
Fission Source operator, matrix-free version.
class FissionSpectrum
Fission Spectrum operator \(\chi \).
class FissionSpectrumFactory
Factory to create fission spectrum operators (w/o matrix)
class FissionSpectrumMatrixBuilt
Fission Spectrum operator \(\chi \), matrix-built version.
class FissionSpectrumMatrixFree
Fission Spectrum operator \(\chi \), matrix-free version.
class ForestVector
A vector class used in Forest.
class HomData
HomData.
class Homogenization
Homogenization.
class Input
Classes related to data input.
class InputAlgebra
Class containing input information for the algebra.
class InputFESettings
Class containing input information for the Finite elements.
class InputFiles
Class containing the input and output files.
class InputGeom
Class containing input data to construct the geometry.
class InputMat
Class for the cross sections.
class InputOutput
Class containing output information for the problem.
class InputProblem
Class containing input information for the coarsening.
class InputSettings
Container for the settings of the problem.
class Lattice
Container for the data of an assembly.
class LUsolver
QZ solver for the local matrices.
class Manager
State vectors for the system.
class MatrixFreeIntegrator
Matrix Free integrator for the discontinuous Galerkin.
class MatrixIntegrator
Matrix integrator for the discontinuous Galerkin.
class MGPrec
class MomentIndexer
Indexes spherical harmonics moments.
class MomentsToDirections
Moments to directions class.
class Multigroup
class NeutronicModule
A Class related to neutron transport operators and solvers.
class Pin
Container for the data of a single pin.
class PostProcessing
PostProcessing.
class ProbGeom
class QuadratureBase
QuadratureBase.
class QuadratureChebyshevLegendre
QuadratureChebyshevLegendre.
class QuadratureFactory
Generate the quadratures and return the object.
class QuadratureGaussChebyshev
QuadratureGaussChebyshev.
class QuadratureGaussLegendre
QuadratureGaussLegendre.
class QuadratureLevelSymType1
QuadratureLevelSymType1.
class QuadratureLevelSymType2
QuadratureLevelSymType2.
class QZsolver
QZ solver for the local matrices.
class RealAssembly
class RealCore
this name is provisional. Something better can be better.
class RealPin
Contains the information to build the triangulation for a pin.
class ScatteringFactory
Factory to create Scattering Source operators (with/without matrix)
class ScatteringMatrixBuilt
Scattering Source, matrix-built version.
class ScatteringMatrixFree
Scattering Source, matrix-free version.
class ScatteringSource
Scattering Source, base class.
class SnVector
A vector class used in Forest.
class SolverEq
Class implementing the Solver.
class SphericalHarmonics
Spherical harmonics generation for anisotropic scattering.
class State
State vectors for the system.
class StatsMemory
StatsMemory.
class StatsTimer
StatsTimer.
class TransBc
Transport operator boundary contitions.
class TransFactory
Factory to create Transport operators (with/without matrix)
class TransOp
Transport operator and sweep, base class.
class TransOpMatrixBuilt
Transport operator and sweep, matrix-built version.
class TransOpMatrixFree
Transport operator and sweep, matrix-free version.
class TransOpMatrixFreePre
class XS_single
Structure containing the data of a single material.
struct xy_shape
Structure encoding the shape of the reactor.
Typedefs
template<int dim>
using EigenProbPtr = std::shared_ptr< EigenProb< dim > >
We create an alias to the shared_ptr with template aliasing.
template<int dim>
using EqPtr = std::shared_ptr< Equation< dim > >
We create an alias to the shared_ptr with template aliasing.
template<int dim>
using QuadraturePtr = std::shared_ptr< QuadratureBase< dim > >
We create an alias to the shared_ptr with template aliasing.
template<int dim>
using BoundaryValuesPtr = std::shared_ptr< BoundaryValues< dim > >
We create an alias to the shared_ptr with template aliasing.
template<int dim>
using DiffOpPtr = std::shared_ptr< DiffOp< dim > >
We create an alias to the shared_ptr with template aliasing.
template<int dim>
using FissionSourcePtr = std::shared_ptr< FissionSource< dim > >
We create an alias to the shared_ptr with template aliasing.
template<int dim>
using FissionSpectrumPtr = std::shared_ptr< FissionSpectrum< dim > >
We create an alias to the shared_ptr with template aliasing.
template<int dim>
using ScatteringSourcePtr = std::shared_ptr< ScatteringSource< dim > >
We create an alias to the shared_ptr with template aliasing.
template<int dim>
using TransOpPtr = std::shared_ptr< TransOp< dim > >
We create an alias to the shared_ptr with template aliasing.
Enumerations
enum PinType { PinType::BOX, PinType::PIN, PinType::PINNEW, PinType::PINBOX }
Type of pin.
enum LattType { LattType::GRID, LattType::PINMAP }
Type of lattice.
Functions
template<int dim>
PetscErrorCode shell_vmult (Mat shell_mat, Vec src, Vec dst)
Function defined that multiplies the shell matrix by a vector.
template PetscErrorCode shell_vmult< 1 > (Mat shell_mat, Vec src, Vec dst)
template PetscErrorCode shell_vmult< 2 > (Mat shell_mat, Vec src, Vec dst)
template PetscErrorCode shell_vmult< 3 > (Mat shell_mat, Vec src, Vec dst)
template<typename Number >
void parse_multiline_to_vector (std::ifstream &input_file, unsigned int nlines, std::vector< Number > &out, bool deprecate_first=true)
parsing lines from a file
template void parse_multiline_to_vector< unsigned char > (std::ifstream &input_file, unsigned int nlines, std::vector< unsigned char > &out, bool deprecate_first)
template void parse_multiline_to_vector< double > (std::ifstream &input_file, unsigned int nlines, std::vector< double > &out, bool deprecate_first)
template<typename Number >
void parse_shapeline_to_vector (std::ifstream &input_file, std::vector< unsigned int > &n_nodes, std::vector< xy_shape > &flat_shape, std::vector< Number > &out, bool deprecate_first=true)
parsing lines from a file
template void parse_shapeline_to_vector< unsigned char > (std::ifstream &input_file, std::vector< unsigned int > &n_nodes, std::vector< xy_shape > &flat_shape, std::vector< unsigned char > &out, bool deprecate_first)
template<typename Number >
void add_vec_to_file (const std::vector< Number > &vec, const std::string &filename, std::string &introduction="\n \n", unsigned int precision=8)
Print vec to a file filename with an introduction and precision.
template<typename Number >
dealii::Table< 1, Number > shape_to_table_1 (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials)
1D specialization when the shape is not provided (so it is assumed that the reactor fills the whole box)
template<typename Number >
dealii::Table< 2, Number > shape_to_table_2 (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials)
2D specialization when the shape is not provided (so it is assumed that the reactor fills the whole box)
template<typename Number >
dealii::Table< 3, Number > shape_to_table_3 (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials)
3D specialization when the shape is not provided (so it is assumed that the reactor fills the whole box)
template<>
dealii::Table< 1, unsigned char > shape_to_table< 1, unsigned char > (std::vector< unsigned int > &n_nodes, std::vector< unsigned char > &materials)
specialization
template<>
dealii::Table< 2, unsigned char > shape_to_table< 2, unsigned char > (std::vector< unsigned int > &n_nodes, std::vector< unsigned char > &materials)
specialization
template<>
dealii::Table< 3, unsigned char > shape_to_table< 3, unsigned char > (std::vector< unsigned int > &n_nodes, std::vector< unsigned char > &materials)
specialization
template<typename Number >
dealii::Table< 1, Number > shape_to_table_1 (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials, std::vector< xy_shape > &)
1D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
template<typename Number >
dealii::Table< 2, Number > shape_to_table_2 (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials, std::vector< xy_shape > &geom_shape)
2D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
template<typename Number >
dealii::Table< 3, Number > shape_to_table_3 (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials, std::vector< xy_shape > &geom_shape)
3D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
template<>
dealii::Table< 1, unsigned char > shape_to_table (std::vector< unsigned int > &n_nodes, std::vector< unsigned char > &materials, std::vector< xy_shape > &flat_shape)
This should NOT be used, only defined to specialization below:
template<>
dealii::Table< 2, unsigned char > shape_to_table (std::vector< unsigned int > &n_nodes, std::vector< unsigned char > &materials, std::vector< xy_shape > &flat_shape)
This should NOT be used, only defined to specialization below:
template<>
dealii::Table< 3, unsigned char > shape_to_table (std::vector< unsigned int > &n_nodes, std::vector< unsigned char > &materials, std::vector< xy_shape > &flat_shape)
This should NOT be used, only defined to specialization below:
template<typename Number >
void print_table_1 (dealii::Table< 1, Number > &table)
1D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
template<typename Number >
void print_table_2 (dealii::Table< 2, Number > &table)
2D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
template<typename Number >
void print_table_3 (dealii::Table< 3, Number > &table)
3D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
template<>
void print_table (dealii::Table< 1, unsigned char > &table)
This should NOT be used, only defined to specialization below:
template<>
void print_table (dealii::Table< 2, unsigned char > &table)
This should NOT be used, only defined to specialization below:
template<>
void print_table (dealii::Table< 3, unsigned char > &table)
This should NOT be used, only defined to specialization below:
template<int dim>
void generate_gauss_chebyshev (std::vector< double > &x, std::vector< double > &w, unsigned int m, bool normalize=false)
generate_gauss_chebyshevGenerate the weight of the Gauss-Chebyshev quadrature.
template<int dim>
void generate_gauss_legendre (std::vector< double > &x, std::vector< double > &w, unsigned int m, double x1=-1.0, double x2=1.0)
void split (const std::string &s, char delim, std::vector< std::string > &elems)
Split string into tokens.
std::vector< std::string > split (const std::string &s, char delim)
Split string into tokens.
bool file_exists (const std::string &filename)
Check if the file exist and can open it.
std::string get_path (const std::string &path_plus_file_plus_exts_)
This function look for the path of the folder where the file path_plus_file_plus_exts_ is stored.
std::string get_file_plus_ext (const std::string &path_plus_file_plus_ext_)
Get the name of the file in path_plus_file_plus_exts_ stripping the rest of the path.
std::string get_file_minus_ext (const std::string &path_plus_file_plus_ext_)
This function look for name of the file in the path_plus_file_plus_ext_ and strips the last extension (if any).
template<typename Number >
Number string_to_num (std::string str)
Convert a string to a number for some types.
template<>
unsigned char string_to_num< unsigned char > (std::string str)
Convert a string to a unsigned char.
template<>
unsigned int string_to_num< unsigned int > (std::string str)
Convert a string to a unsigned int.
template<>
int string_to_num< int > (std::string str)
Convert a string to a int.
template<>
double string_to_num< double > (std::string str)
Convert a string to a double.
template<typename Number >
std::string num_to_string (Number val)
Convert a number of different types to a string.
template<typename Number >
void string_to_vector (const std::string &in, std::vector< Number > &out)
template<typename Number >
void string_to_vector (const std::string &in, std::vector< std::vector< Number > > &out)
template<typename Number >
void vector_to_string (const std::vector< Number > &in, std::string &out, const std::string &indent=std::string(""), const unsigned int n_indent=0, const unsigned int precision=7)
template<typename Number >
void vector_to_string (const std::vector< std::vector< Number > > &in, std::string &out, const std::string &indent=std::string(""), const unsigned int n_indent=0, const unsigned int precision=7)
template<int dim>
std::vector< double > r_normal (unsigned int f)
template<int dim>
Table< dim, types::material_id > stdvector_to_table (std::vector< unsigned int > n_nodes, std::vector< std::vector< types::material_id > > materials)
Fill dealii Table<dim, number> with std::vector<std::vector<number> >
template<>
Table< 1, types::material_id > stdvector_to_table< 1 > (std::vector< unsigned int > n_nodes, std::vector< std::vector< types::material_id > > materials)
template<typename Number >
Table< 1, Number > shape_to_table_1 (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials)
1D specialization when the shape is not provided (so it is assumed that the reactor fills the whole box)
template<typename Number >
Table< 2, Number > shape_to_table_2 (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials)
2D specialization when the shape is not provided (so it is assumed that the reactor fills the whole box)
template<typename Number >
Table< 3, Number > shape_to_table_3 (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials)
3D specialization when the shape is not provided (so it is assumed that the reactor fills the whole box)
template<int dim, typename Number >
Table< dim, Number > shape_to_table (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials)
fill dealii Table<dim, number> with reactor filling whole box
template<typename Number >
Table< 1, Number > shape_to_table_1 (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials, std::vector< xy_shape > &flat_shape)
1D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
template<typename Number >
Table< 2, Number > shape_to_table_2 (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials, std::vector< xy_shape > &flat_shape)
2D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
template<typename Number >
Table< 3, Number > shape_to_table_3 (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials, std::vector< xy_shape > &flat_shape)
3D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
template<int dim, typename Number >
Table< dim, Number > shape_to_table (std::vector< unsigned int > &n_nodes, std::vector< Number > &materials, std::vector< xy_shape > &flat_shape)
fill dealii Table<dim, number> with reactor filling xy_shape
template<typename Number >
void print_table_1 (Table< 1, Number > &table)
Print content of dealii Table<1, number>
template<typename Number >
void print_table_2 (Table< 2, Number > &table)
Print content of dealii Table<1, number>
template<typename Number >
void print_table_3 (Table< 3, Number > &table)
Print content of dealii Table<1, number>
template<int dim, typename Number >
void print_table (Table< dim, Number > &table)
Print content of dealii Table<dim, number>
template<int dim>
Point< dim > vector_to_point (const std::vector< double > &v)
template<int dim>
Point< dim > new_point (const double v0=0.0, const double v1=0.0, const double v2=0.0)
We create a new Point<dim> object.
template<int dim>
Tensor< 1, dim > p_normal (unsigned int f)
template<int dim>
unsigned int normal2face (const Tensor< 1, dim > &normal)
Find the face for which the vector is an outgoing vector.
template<int dim>
unsigned int normal2face (const Point< dim > &normal)
void log_print_time (const std::string &msg, double value)
Print time statistics message.
void log_print_mem (const std::string &msg, double value)
Print memory consumption message.
bool log_table_keff_wgit (const unsigned int iter, const double keff, const double spg, const double err, const double tol, const unsigned int print_freq=1, const unsigned int indent_times=1)
Print statistics if required and return convergence status.
bool log_table_keff (const unsigned int iter, const double keff, const double err, const double tol, const unsigned int print_freq=1, const unsigned int indent_times=1)
Print statistics if required and return convergence status.
void log_print_text (const std::string &msg, unsigned int indent_times=0)
Print msg indenting indent_times.
void log_print_line (char sep= '-')
Print a line by repeating the character in sep.
void log_print_title (const std::string &end_msg, char sep= ' ')
Print title centered end_msg filling empty space with sep.
std::string start_forest (int argc, char **argv, const unsigned int output_level=1)
void finish_forest ()
Variables
const double eps6 = 1.e-6
const double eps10 = 1.e-10
const double pi = 3.14159265358979324
pi
const double two_pi = 6.28318530717958648
2*pi
const double inv_two_pi = 0.159154943091895336
1/2/pi
const double four_pi = 12.5663706143591730
4*pi
const double inv_four_pi = 0.0795774715459476678
1/4/pi
static const unsigned int line_length = 80
Line length used by default in all the printing.
static const unsigned int indent_length = 2
Indent length used by default in all the printing.
Detailed Description
Classes related to algebra (matrix/vector)
Classes related to post-processing and printing the solution.
Todo:
Have quadratures based on the "octant" and "angle within octant" for the moment, but also general quadratures without this restriction, so I have to develop extra interfaces and a flag for quadratures not defined by octant.
Typedef Documentation
template<int dim> using Forest::EigenProbPtr = typedef std::shared_ptr<EigenProb<dim> >
We create an alias to the shared_ptr with template aliasing.
Definition at line 23 of file eigen_prob_factory.h.
template<int dim> using Forest::EqPtr = typedef std::shared_ptr<Equation<dim> >
We create an alias to the shared_ptr with template aliasing.
Definition at line 19 of file eq_factory.h.
template<int dim> using Forest::QuadraturePtr = typedef std::shared_ptr<QuadratureBase<dim> >
We create an alias to the shared_ptr with template aliasing.
Definition at line 24 of file quadrature_factory.h.
template<int dim> using Forest::BoundaryValuesPtr = typedef std::shared_ptr<BoundaryValues<dim> >
We create an alias to the shared_ptr with template aliasing.
Definition at line 20 of file boundary_values_factory.h.
template<int dim> using Forest::DiffOpPtr = typedef std::shared_ptr<DiffOp<dim> >
We create an alias to the shared_ptr with template aliasing.
Definition at line 23 of file diff_factory.h.
template<int dim> using Forest::FissionSourcePtr = typedef std::shared_ptr<FissionSource<dim> >
We create an alias to the shared_ptr with template aliasing.
Definition at line 19 of file fission_source_factory.h.
template<int dim> using Forest::FissionSpectrumPtr = typedef std::shared_ptr<FissionSpectrum<dim> >
We create an alias to the shared_ptr with template aliasing.
Definition at line 19 of file fission_spectrum_factory.h.
template<int dim> using Forest::ScatteringSourcePtr = typedef std::shared_ptr<ScatteringSource<dim> >
We create an alias to the shared_ptr with template aliasing.
Definition at line 21 of file scattering_factory.h.
template<int dim> using Forest::TransOpPtr = typedef std::shared_ptr<TransOp<dim> >
We create an alias to the shared_ptr with template aliasing.
Definition at line 24 of file trans_factory.h.
Function Documentation
template<int dim> PetscErrorCode Forest::shell_vmult (Mat shell_mat, Vec src, Vec dst)
Function defined that multiplies the shell matrix by a vector.
Definition at line 206 of file eigen_solver_slepc.cc.
   {
     PetscErrorCode ierr;
     // The context of the shell matrix is a pointer to the EigenSolverSLEPC object
     // so we can access the data of the problem.
     void *ctx;
     ierr = MatShellGetContext (shell_mat, &ctx);
     CHKERRQ(ierr);
     EigenSolverSLEPC<dim> *EPSobject = (EigenSolverSLEPC<dim>*) ctx;
     /* Copy to SnVector */
     EPSobject->copy_to_sn_vector (src, EPSobject->sn_vector_tmp_src);
     /* Apply the operator y = A x. */
     EPSobject->m_eigen_prob->vmult (EPSobject->sn_vector_tmp_dst,
         EPSobject->sn_vector_tmp_src);
     /* Copy back to Petsc Vector */
     EPSobject->copy_to_petsc_vector (EPSobject->sn_vector_tmp_dst, dst);
     EPSobject->n_matvec_multiplications++;
     log_print_text (
         "SLEPc Multiplication: " + num_to_string (
             EPSobject->n_matvec_multiplications), 1);
     CHKERRQ(ierr);
     return 0;
   }
template PetscErrorCode Forest::shell_vmult< 1 > (Mat shell_mat, Vec src, Vec dst)
Referenced by shell_vmult().
template PetscErrorCode Forest::shell_vmult< 2 > (Mat shell_mat, Vec src, Vec dst)
Referenced by shell_vmult().
template PetscErrorCode Forest::shell_vmult< 3 > (Mat shell_mat, Vec src, Vec dst)
Referenced by shell_vmult().
template<typename Number > void Forest::parse_multiline_to_vector (std::ifstream & input_file, unsigned int nlines, std::vector< Number > & out, bool deprecate_first)
parsing lines from a file
Definition at line 18 of file forest_utils_base.cc.
   {
     std::string line;
     std::string bin;
     Number num;
     for (unsigned int j = 0; j < nlines; j++)
     {
       getline (input_file, line);
       std::istringstream iss (line);
       // Reading all the elements for a line (but sometimes the first one).
       bool first_element = true;
       while (iss >> bin)
       {
         if (deprecate_first and first_element)
         {
           first_element = false;
           if ((bin == "#") or (bin == "!") or (bin == "//") or (bin == ""))
           {
             /* If the line is one of previous, we move to the next line. */
             j--;
             continue;
           }
         }
         else
         {
           num = string_to_num<Number> (bin);
           out.push_back (num);
         }
       }
     }
   }
template void Forest::parse_multiline_to_vector< unsigned char > (std::ifstream & input_file, unsigned int nlines, std::vector< unsigned char > & out, bool deprecate_first)
Referenced by parse_multiline_to_vector().
template void Forest::parse_multiline_to_vector< double > (std::ifstream & input_file, unsigned int nlines, std::vector< double > & out, bool deprecate_first)
Referenced by parse_multiline_to_vector().
template<typename Number > void Forest::parse_shapeline_to_vector (std::ifstream & input_file, std::vector< unsigned int > & n_nodes, std::vector< xy_shape > & flat_shape, std::vector< Number > & out, bool deprecate_first)
parsing lines from a file
Definition at line 70 of file forest_utils_base.cc.
   {
     std::string line;
     std::string bin;
     xy_shape flat_shape_aux;
     Number num;
     out.clear ();
     for (unsigned int j = 0; j < n_nodes[1]; j++)
     {
       getline (input_file, line);
       std::istringstream iss (line);
       // Reading all the elements for a line (but sometimes the first one).
       unsigned int i = 0;
       bool first_element = true;
       while (iss >> bin)
       {
         if (deprecate_first and first_element)
         {
           first_element = false;
           if ((bin == "#") or (bin == "!") or (bin == "//") or (bin == ""))
           {
             // If the line found is a comment or empty line,
             // we move forward to the next line.
             j--;
             continue;
           }
         }
         else
         {
           num = string_to_num<Number> (bin);
           out.push_back (num);
           ++i;
         }
       }
       unsigned int temp = (n_nodes[0] - i) / 2;
       flat_shape_aux.x_begin.push_back (temp);
       flat_shape_aux.x_end.push_back (n_nodes[0] - temp);
     }
     // Verifying that the dimensions are the good ones
     assert(flat_shape_aux.x_begin.size () == n_nodes[1]);
     assert(flat_shape_aux.x_end.size () == n_nodes[1]);
     flat_shape.push_back (flat_shape_aux);
   }
template void Forest::parse_shapeline_to_vector< unsigned char > (std::ifstream & input_file, std::vector< unsigned int > & n_nodes, std::vector< xy_shape > & flat_shape, std::vector< unsigned char > & out, bool deprecate_first)
Referenced by parse_shapeline_to_vector().
template<typename Number > void Forest::add_vec_to_file (const std::vector< Number > & vec, const std::string & filename, std::string & introduction = "\n \n", unsigned int precision = 8)
Print vec to a file filename with an introduction and precision.
It starts to print at the end of the file, adding the vector to the previous content of the file.
Parameters
vec Name of the vector we want to print.
filename Name of the file where we want to print.
introduction The string we want to print before we print the vector values. By default it jump two lines.
precision The number of digits we want to print. By default it is set equal to 8.
Definition at line 135 of file forest_utils_base.cc.
   {
     std::ofstream out (filename.c_str (), std::ios::app);
     out.precision (precision);
     out << introduction;
     for (unsigned int i = 0; i < vec.size (); i++)
     {
       out << vec[i] << " \n";
     }
     out << "\n";
     out.close ();
   }
template<typename Number > dealii::Table<1, Number> Forest::shape_to_table_1 (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials)
1D specialization when the shape is not provided (so it is assumed that the reactor fills the whole box)
Definition at line 22 of file forest_utils_dealii.cc.
Referenced by shape_to_table().
   {
     // Defining the table and filling with (-1)
     dealii::Table<1, Number> existing_cells (n_nodes[0]);
     existing_cells.fill ((Number) (-1));
     // Filling the table with the values
     unsigned int mat = 0;
     for (unsigned int i = 0; i < n_nodes[0]; ++i)
     {
       existing_cells[i] = materials[mat];
       ++mat;
     }
     return existing_cells;
   }
template<typename Number > dealii::Table<2, Number> Forest::shape_to_table_2 (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials)
2D specialization when the shape is not provided (so it is assumed that the reactor fills the whole box)
Definition at line 46 of file forest_utils_dealii.cc.
Referenced by shape_to_table().
   {
     // Defining the table and filling with (-1)
     dealii::Table<2, Number> existing_cells (n_nodes[0], n_nodes[1]);
     existing_cells.fill ((Number) (-1));
     // Filling the table with the values
     unsigned int mat = 0;
     for (unsigned int j = 0; j < n_nodes[1]; ++j)
     {
       for (unsigned int i = 0; i < n_nodes[0]; ++i)
       {
         existing_cells[i][j] = materials[mat];
         ++mat;
       }
     }
     return existing_cells;
   }
template<typename Number > dealii::Table<3, Number> Forest::shape_to_table_3 (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials)
3D specialization when the shape is not provided (so it is assumed that the reactor fills the whole box)
Definition at line 73 of file forest_utils_dealii.cc.
Referenced by shape_to_table().
   {
     // Defining the table and filling with (-1)
     dealii::Table<3, Number> existing_cells (n_nodes[0], n_nodes[1],
         n_nodes[2]);
     existing_cells.fill ((Number) (-1));
     // Filling the table with the values
     unsigned int mat = 0;
     for (unsigned int k = 0; k < n_nodes[2]; ++k)
     {
       for (unsigned int j = 0; j < n_nodes[1]; ++j)
       {
         for (unsigned int i = 0; i < n_nodes[0]; ++i)
         {
           existing_cells[i][j][k] = materials[mat];
           ++mat;
         }
       }
     }
     return existing_cells;
   }
template<> dealii::Table<1, unsigned char> Forest::shape_to_table< 1, unsigned char > (std::vector< unsigned int > & n_nodes, std::vector< unsigned char > & materials)
specialization
Definition at line 104 of file forest_utils_dealii.cc.
   {
     return shape_to_table_1<unsigned char> (n_nodes, materials);
   }
template<> dealii::Table<2, unsigned char> Forest::shape_to_table< 2, unsigned char > (std::vector< unsigned int > & n_nodes, std::vector< unsigned char > & materials)
specialization
Definition at line 116 of file forest_utils_dealii.cc.
   {
     return shape_to_table_2<unsigned char> (n_nodes, materials);
   }
template<> dealii::Table<3, unsigned char> Forest::shape_to_table< 3, unsigned char > (std::vector< unsigned int > & n_nodes, std::vector< unsigned char > & materials)
specialization
Definition at line 128 of file forest_utils_dealii.cc.
   {
     return shape_to_table_3<unsigned char> (n_nodes, materials);
   }
template<typename Number > dealii::Table<1, Number> Forest::shape_to_table_1 (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials, std::vector< xy_shape > &)
1D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
Definition at line 142 of file forest_utils_dealii.cc.
   {
     // Defining the table and filling with (-1)
     dealii::Table<1, Number> existing_cells (n_nodes[0]);
     existing_cells.fill ((Number) (-1));
     // Filling the table with the values
     unsigned int mat = 0;
     for (unsigned int i = 0; i < n_nodes[0]; ++i)
     {
       existing_cells[i] = materials[mat];
       ++mat;
     }
     return existing_cells;
   }
template<typename Number > dealii::Table<2, Number> Forest::shape_to_table_2 (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials, std::vector< xy_shape > & geom_shape)
2D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
Definition at line 166 of file forest_utils_dealii.cc.
   {
     // Defining the table and filling with (-1)
     dealii::Table<2, Number> existing_cells (n_nodes[0], n_nodes[1]);
     existing_cells.fill ((Number) (-1));
     // Filling the table with the values
     unsigned int mat = 0;
     for (unsigned int j = 0; j < n_nodes[1]; ++j)
     {
       for (unsigned int i = geom_shape[0].x_begin[j];
           i < geom_shape[0].x_end[j]; ++i)
       {
         existing_cells[i][j] = materials[mat];
         ++mat;
       }
     }
     return existing_cells;
   }
template<typename Number > dealii::Table<3, Number> Forest::shape_to_table_3 (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials, std::vector< xy_shape > & geom_shape)
3D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
Definition at line 194 of file forest_utils_dealii.cc.
   {
     // Defining the table and filling with (-1)
     dealii::Table<3, Number> existing_cells (n_nodes[0], n_nodes[1],
         n_nodes[2]);
     existing_cells.fill ((Number) (-1));
     // Filling the table with the values
     unsigned int mat = 0;
     for (unsigned int k = 0; k < n_nodes[2]; ++k)
     {
       for (unsigned int j = 0; j < n_nodes[1]; ++j)
       {
         for (unsigned int i = geom_shape[k].x_begin[j];
             i < geom_shape[k].x_end[j]; ++i)
         {
           existing_cells[i][j][k] = materials[mat];
           ++mat;
         }
       }
     }
     return existing_cells;
   }
template<> dealii::Table<1, unsigned char> Forest::shape_to_table (std::vector< unsigned int > & n_nodes, std::vector< unsigned char > & materials, std::vector< xy_shape > & flat_shape)
This should NOT be used, only defined to specialization below:
Definition at line 227 of file forest_utils_dealii.cc.
   {
     return shape_to_table_1 (n_nodes, materials, flat_shape);
   }
template<> dealii::Table<2, unsigned char> Forest::shape_to_table (std::vector< unsigned int > & n_nodes, std::vector< unsigned char > & materials, std::vector< xy_shape > & flat_shape)
This should NOT be used, only defined to specialization below:
Definition at line 239 of file forest_utils_dealii.cc.
   {
     return shape_to_table_2 (n_nodes, materials, flat_shape);
   }
template<> dealii::Table<3, unsigned char> Forest::shape_to_table (std::vector< unsigned int > & n_nodes, std::vector< unsigned char > & materials, std::vector< xy_shape > & flat_shape)
This should NOT be used, only defined to specialization below:
Definition at line 251 of file forest_utils_dealii.cc.
   {
     return shape_to_table_3 (n_nodes, materials, flat_shape);
   }
template<typename Number > void Forest::print_table_1 (dealii::Table< 1, Number > & table)
1D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
Definition at line 268 of file forest_utils_dealii.cc.
Referenced by print_table().
   {
     std::cout << "printing table \n";
     for (unsigned int i = 0; i < table.size (0); ++i)
     {
       std::cout << static_cast<double> (table[i]) << " ";
     }
     std::cout << std::endl;
   }
template<typename Number > void Forest::print_table_2 (dealii::Table< 2, Number > & table)
2D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
Definition at line 284 of file forest_utils_dealii.cc.
Referenced by print_table().
   {
     std::cout << "printing table \n";
     for (unsigned int j = 0; j < table.size (1); ++j)
     {
       for (unsigned int i = 0; i < table.size (0); ++i)
       {
         std::cout << static_cast<double> (table[i][j]) << " ";
       }
       std::cout << std::endl;
     }
     std::cout << std::endl;
   }
template<typename Number > void Forest::print_table_3 (dealii::Table< 3, Number > & table)
3D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
Definition at line 304 of file forest_utils_dealii.cc.
Referenced by print_table().
   {
     std::cout << "printing table \n";
     for (unsigned int k = 0; k < table.size (2); ++k)
     {
       for (unsigned int j = 0; j < table.size (1); ++j)
       {
         for (unsigned int i = 0; i < table.size (0); ++i)
         {
           std::cout << static_cast<double> (table[i][j][k]) << " ";
         }
         std::cout << std::endl;
       }
       std::cout << std::endl << std::endl;
     }
     std::cout << std::endl;
   }
template<> void Forest::print_table (dealii::Table< 1, unsigned char > & table)
This should NOT be used, only defined to specialization below:
Definition at line 329 of file forest_utils_dealii.cc.
   {
     return print_table_1 (table);
   }
template<> void Forest::print_table (dealii::Table< 2, unsigned char > & table)
This should NOT be used, only defined to specialization below:
Definition at line 339 of file forest_utils_dealii.cc.
   {
     return print_table_2 (table);
   }
template<> void Forest::print_table (dealii::Table< 3, unsigned char > & table)
This should NOT be used, only defined to specialization below:
Definition at line 349 of file forest_utils_dealii.cc.
   {
     return print_table_3 (table);
   }
void Forest::split (const std::string & s, char delim, std::vector< std::string > & elems) inline
Split string into tokens.
Note that this solution does not skip empty tokens, so the following will find 4 items, one of which is empty:
std::vector<std::string> x;
split("one:two::three", ':', x);
Definition at line 33 of file forest_utils_base.h.
Referenced by split().
{
       std::stringstream ss;
       ss.str(s);
       std::string item;
       while (std::getline(ss, item, delim)) {
         elems.push_back(item);
       }
   }
std::vector<std::string> Forest::split (const std::string & s, char delim) inline
Split string into tokens.
Note that this solution does not skip empty tokens, so the following will find 4 items, one of which is empty:
std::vector<std::string> x = split("one:two::three", ':');
Definition at line 53 of file forest_utils_base.h.
Referenced by string_to_vector().
{
       std::vector<std::string> elems;
       split(s, delim, elems);
       return elems;
   }
bool Forest::file_exists (const std::string & filename) inline
Check if the file exist and can open it.
Parameters
filename Name of the file we want to open.
Return values
true if the file is open.
false otherwise.
Definition at line 69 of file forest_utils_base.h.
   {
     std::ifstream input_file (filename.c_str ());
     return input_file.is_open ();
   }
std::string Forest::get_path (const std::string & path_plus_file_plus_exts_) inline
This function look for the path of the folder where the file path_plus_file_plus_exts_ is stored.
It can be used as the working directory for the rest of the files. If path_plus_file_plus_ext_ is only the name of a file, then "." is returned as the working directory. For example, using it as follows
path = get_path("/this/is/the/path/file.ext1.ext2");
we obtain that path contains "/this/is/the/path/".
Parameters
path_plus_file_plus_exts_ The full path of the file that we use.
Return values
string The root for the directory.
Note
The character "/" works for Linux, but probably fails for Windows.
Definition at line 90 of file forest_utils_base.h.
   {
     std::size_t pos_ = path_plus_file_plus_exts_.find_last_of ("\\/");
     std::string path;
     if (pos_ == path_plus_file_plus_exts_.npos)
       path = std::string ("./");
     else
       path = path_plus_file_plus_exts_.substr (0, pos_) + "/";
     return path;
   }
std::string Forest::get_file_plus_ext (const std::string & path_plus_file_plus_ext_) inline
Get the name of the file in path_plus_file_plus_exts_ stripping the rest of the path.
For example, using it as follows
file_plus_ext = get_file_plus_ext("/this/is/the/path/file.ext1.ext2");
we obtain that file_plus_ext contains "file.ext1.ext2".
Parameters
path_plus_file_plus_ext_ The full path of the file that we use.
Return values
string The name of the input file without the root path.
Definition at line 113 of file forest_utils_base.h.
   {
     std::size_t pos_ = path_plus_file_plus_ext_.find_last_of ("\\/");
     std::string file_plus_ext;
     if (pos_ == path_plus_file_plus_ext_.npos)
     {
       file_plus_ext = path_plus_file_plus_ext_;
     }
     else
     {
       file_plus_ext = path_plus_file_plus_ext_.substr (pos_ + 1);
     }
     return file_plus_ext;
   }
std::string Forest::get_file_minus_ext (const std::string & path_plus_file_plus_ext_) inline
This function look for name of the file in the path_plus_file_plus_ext_ and strips the last extension (if any).
This function obtains a "problem-related name" that will be used later as a root-name to generate the output files obtained with this input. For example, using it as follows
file_minus_ext = get_file_minus_ext("/this/is/the/path/file.ext1.ext2");
we obtain that file_minus_ext contains "/this/is/the/path/file.ext1".
Parameters
path_plus_file_plus_ext_ The full name of the input file that we use
Return values
string The name of the input without the last extension.
Definition at line 145 of file forest_utils_base.h.
   {
     std::size_t pos_ = path_plus_file_plus_ext_.find_last_of (".");
     std::string file_minus_ext;
     if (pos_ == path_plus_file_plus_ext_.npos)
       file_minus_ext = path_plus_file_plus_ext_;
     else
       file_minus_ext = path_plus_file_plus_ext_.substr (0, pos_);
     return file_minus_ext;
   }
template<typename Number > Number Forest::string_to_num (std::string str)
Convert a string to a number for some types.
Parameters
str The string we want to convert to a number
Return values
val The string into a number
Note
The functions were not compiling. To fix it I put them as inline functions. Actually I think that they should be inline function because the specification of the function is so short and they are good candidate for inline functions.
Referenced by get_file_minus_ext().
template<> unsigned char Forest::string_to_num< unsigned char > (std::string str) inline
Convert a string to a unsigned char.
Parameters
str The string we want to convert to a number
Return values
val The string into a number
Definition at line 180 of file forest_utils_base.h.
   {
     return atoi (str.c_str ());
   }
template<> unsigned int Forest::string_to_num< unsigned int > (std::string str) inline
Convert a string to a unsigned int.
Parameters
str The string we want to convert to a number
Return values
val The string into a number
Definition at line 193 of file forest_utils_base.h.
Referenced by Forest::InputAlgebra::read_xml().
   {
     return atoi (str.c_str ());
   }
template<> int Forest::string_to_num< int > (std::string str) inline
Convert a string to a int.
Parameters
str The string we want to convert to a number
Return values
val The string into a number
Definition at line 206 of file forest_utils_base.h.
   {
     return atoi (str.c_str ());
   }
template<> double Forest::string_to_num< double > (std::string str) inline
Convert a string to a double.
Parameters
str The string we want to convert to a number
Return values
val The string into a number
Definition at line 219 of file forest_utils_base.h.
   {
     return atof (str.c_str ());
   }
template<typename Number > std::string Forest::num_to_string (Number val) inline
Convert a number of different types to a string.
The functions were not compiling. To fix it I put them as inline functions. Actually I think that they should be inline function because the specification of the function is so short and they are good candidate for inline functions.
Parameters
val The number we want to convert to a string
Return values
str The string we want to convert to a number
Definition at line 235 of file forest_utils_base.h.
Referenced by Forest::InputGeom::check_lattices(), Forest::ExtractBV< dim >::print_ass_bv(), Forest::HomData< dim >::print_homogenized_xs(), Forest::PostProcessing< dim >::print_vtk(), Forest::PostProcessing< dim >::print_xml_data(), shell_vmult(), and Forest::EigenSolver< dim >::slepc().
   {
     // std::to_string is a C++11 standard
     //return std::to_string(val);
     std::ostringstream ss;
     ss << val;
     return ss.str ();
   }
template<typename Number > void Forest::string_to_vector (const std::string & in, std::vector< Number > & out) inline
Todo:
document me
Definition at line 251 of file forest_utils_base.h.
Referenced by Forest::InputMat::load(), Forest::InputGeom::load_xml(), Forest::ExtractBV< dim >::read_ass_bv(), Forest::Core::set_bcs(), Forest::Core::set_components(), Forest::Lattice::set_components(), Forest::Core::set_length(), Forest::Lattice::set_length(), Forest::Core::set_n_nodes(), Forest::Lattice::set_n_nodes(), and string_to_vector().
   {
     std::string tmp = in;
     std::vector<std::string> strs;
     boost::trim (tmp);
     //split(in, ',',strs);
     boost::split (strs, tmp, boost::is_any_of (", "), boost::token_compress_on);
     for (unsigned int i = 0; i < strs.size (); ++i)
     {
       out.push_back (string_to_num<Number> (strs[i]));
     }
   }
template<typename Number > void Forest::string_to_vector (const std::string & in, std::vector< std::vector< Number > > & out) inline
Todo:
document me
Definition at line 269 of file forest_utils_base.h.
   {
     std::string tmp = in;
     boost::trim_if (tmp, boost::is_any_of ("\n "));
     boost::trim_right_if (tmp, boost::is_any_of (";"));
     std::vector<std::string> strs;
     //split(in, ';',strs);
     boost::split (strs, tmp, boost::is_any_of (";"), boost::token_compress_on);
     out.resize (strs.size ());
     for (unsigned int i = 0; i < strs.size (); ++i)
     {
       string_to_vector (strs[i], out[i]);
     }
   }
template<typename Number > void Forest::vector_to_string (const std::vector< Number > & in, std::string & out, const std::string & indent = std::string (""), const unsigned int n_indent = 0, const unsigned int precision = 7) inline
Todo:
document me
Definition at line 289 of file forest_utils_base.h.
Referenced by Forest::ExtractBV< dim >::print_ass_bv(), Forest::PostProcessing< dim >::print_ass_data(), Forest::HomData< dim >::print_homogenized_xs(), Forest::PostProcessing< dim >::print_pin_data(), Forest::InputMat::save(), Forest::InputGeom::show(), and vector_to_string().
   {
     out.clear ();
     // We should check that the vector is not empty
     Assert(in.size () != 0, dealii::ExcMessage("Empty vector!"));
     // We put the numbers inside the string
     std::stringstream ss;
     //ss << std::fixed;
     ss << std::scientific;
     ss.precision (precision);
     // ss.setf( std::ios::fixed, std::ios::floatfield);
     for (unsigned int i = 0; i < in.size (); ++i)
     {
       ss << std::setw (10) << in[i] << " ";
     }
     //std::copy(in.begin(), in.end(), std::ostream_iterator<Number>(ss, " "));
     for (unsigned int j = 0; j < n_indent; ++j)
       out += indent;
     out += ss.str ();
     out = out.substr (0, out.length () - 1);
   }
template<typename Number > void Forest::vector_to_string (const std::vector< std::vector< Number > > & in, std::string & out, const std::string & indent = std::string (""), const unsigned int n_indent = 0, const unsigned int precision = 7) inline
Todo:
document me
Definition at line 326 of file forest_utils_base.h.
   {
     out.clear ();
     //out += "\n";
     std::string bin;
     for (unsigned int i = 0; i < in.size (); ++i)
     {
       vector_to_string (in[i], bin, indent, n_indent,precision);
       //out += bin + ";\n";
       out += bin + ";"; //
     }
     for (unsigned int j = 0; j < n_indent - 1; ++j)
       out += indent;
   }
template<int dim> std::vector<double> Forest::r_normal (unsigned int f) inline
The notation is following the following convention (for dim == 3):
r_normal(0) = {-1,  0,  0}
r_normal(1) = { 1,  0,  0}
r_normal(2) = { 0, -1,  0}
r_normal(3) = { 0,  1,  0}
r_normal(4) = { 0,  0, -1}
r_normal(5) = { 0,  0,  1}
Parameters
f
Returns
Definition at line 445 of file forest_utils_base.h.
   {
     Assert(f < dim * 2, dealii::ExcMessage("Face out of bounds"));
     std::vector<double> r_normal (dim, 0.0);
     if (f % 2 == 0)
       r_normal[(int) f / 2] = -1.;
     else
       r_normal[(int) f / 2] = 1.;
     return r_normal;
   }
template<int dim> Table<dim, types::material_id> Forest::stdvector_to_table (std::vector< unsigned int > n_nodes, std::vector< std::vector< types::material_id > > materials)
Fill dealii Table<dim, number> with std::vector<std::vector<number> >
Todo:
generalize for more dimensions
template<> Table<1, types::material_id> Forest::stdvector_to_table< 1 > (std::vector< unsigned int > n_nodes, std::vector< std::vector< types::material_id > > materials)
template<typename Number > Table<1, Number> Forest::shape_to_table_1 (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials)
1D specialization when the shape is not provided (so it is assumed that the reactor fills the whole box)
Definition at line 22 of file forest_utils_dealii.cc.
Referenced by shape_to_table().
   {
     // Defining the table and filling with (-1)
     dealii::Table<1, Number> existing_cells (n_nodes[0]);
     existing_cells.fill ((Number) (-1));
     // Filling the table with the values
     unsigned int mat = 0;
     for (unsigned int i = 0; i < n_nodes[0]; ++i)
     {
       existing_cells[i] = materials[mat];
       ++mat;
     }
     return existing_cells;
   }
template<typename Number > Table<2, Number> Forest::shape_to_table_2 (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials)
2D specialization when the shape is not provided (so it is assumed that the reactor fills the whole box)
Definition at line 46 of file forest_utils_dealii.cc.
Referenced by shape_to_table().
   {
     // Defining the table and filling with (-1)
     dealii::Table<2, Number> existing_cells (n_nodes[0], n_nodes[1]);
     existing_cells.fill ((Number) (-1));
     // Filling the table with the values
     unsigned int mat = 0;
     for (unsigned int j = 0; j < n_nodes[1]; ++j)
     {
       for (unsigned int i = 0; i < n_nodes[0]; ++i)
       {
         existing_cells[i][j] = materials[mat];
         ++mat;
       }
     }
     return existing_cells;
   }
template<typename Number > Table<3, Number> Forest::shape_to_table_3 (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials)
3D specialization when the shape is not provided (so it is assumed that the reactor fills the whole box)
Definition at line 73 of file forest_utils_dealii.cc.
Referenced by shape_to_table().
   {
     // Defining the table and filling with (-1)
     dealii::Table<3, Number> existing_cells (n_nodes[0], n_nodes[1],
         n_nodes[2]);
     existing_cells.fill ((Number) (-1));
     // Filling the table with the values
     unsigned int mat = 0;
     for (unsigned int k = 0; k < n_nodes[2]; ++k)
     {
       for (unsigned int j = 0; j < n_nodes[1]; ++j)
       {
         for (unsigned int i = 0; i < n_nodes[0]; ++i)
         {
           existing_cells[i][j][k] = materials[mat];
           ++mat;
         }
       }
     }
     return existing_cells;
   }
template<int dim, typename Number > Table<dim, Number> Forest::shape_to_table (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials)
fill dealii Table<dim, number> with reactor filling whole box
template<typename Number > Table<1, Number> Forest::shape_to_table_1 (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials, std::vector< xy_shape > & flat_shape)
1D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
Definition at line 142 of file forest_utils_dealii.cc.
   {
     // Defining the table and filling with (-1)
     dealii::Table<1, Number> existing_cells (n_nodes[0]);
     existing_cells.fill ((Number) (-1));
     // Filling the table with the values
     unsigned int mat = 0;
     for (unsigned int i = 0; i < n_nodes[0]; ++i)
     {
       existing_cells[i] = materials[mat];
       ++mat;
     }
     return existing_cells;
   }
template<typename Number > Table<2, Number> Forest::shape_to_table_2 (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials, std::vector< xy_shape > & flat_shape)
2D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
Definition at line 166 of file forest_utils_dealii.cc.
   {
     // Defining the table and filling with (-1)
     dealii::Table<2, Number> existing_cells (n_nodes[0], n_nodes[1]);
     existing_cells.fill ((Number) (-1));
     // Filling the table with the values
     unsigned int mat = 0;
     for (unsigned int j = 0; j < n_nodes[1]; ++j)
     {
       for (unsigned int i = geom_shape[0].x_begin[j];
           i < geom_shape[0].x_end[j]; ++i)
       {
         existing_cells[i][j] = materials[mat];
         ++mat;
       }
     }
     return existing_cells;
   }
template<typename Number > Table<3, Number> Forest::shape_to_table_3 (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials, std::vector< xy_shape > & flat_shape)
3D specialization when the shape is provided (so it is assumed that the reactor does not fill the whole box)
Definition at line 194 of file forest_utils_dealii.cc.
   {
     // Defining the table and filling with (-1)
     dealii::Table<3, Number> existing_cells (n_nodes[0], n_nodes[1],
         n_nodes[2]);
     existing_cells.fill ((Number) (-1));
     // Filling the table with the values
     unsigned int mat = 0;
     for (unsigned int k = 0; k < n_nodes[2]; ++k)
     {
       for (unsigned int j = 0; j < n_nodes[1]; ++j)
       {
         for (unsigned int i = geom_shape[k].x_begin[j];
             i < geom_shape[k].x_end[j]; ++i)
         {
           existing_cells[i][j][k] = materials[mat];
           ++mat;
         }
       }
     }
     return existing_cells;
   }
template<int dim, typename Number > Table<dim, Number> Forest::shape_to_table (std::vector< unsigned int > & n_nodes, std::vector< Number > & materials, std::vector< xy_shape > & flat_shape)
fill dealii Table<dim, number> with reactor filling xy_shape
template<typename Number > void Forest::print_table_1 (Table< 1, Number > & table)
Print content of dealii Table<1, number>
template<typename Number > void Forest::print_table_2 (Table< 2, Number > & table)
Print content of dealii Table<1, number>
template<typename Number > void Forest::print_table_3 (Table< 3, Number > & table)
Print content of dealii Table<1, number>
template<int dim, typename Number > void Forest::print_table (Table< dim, Number > & table)
Print content of dealii Table<dim, number>
template<int dim> Point<dim> Forest::vector_to_point (const std::vector< double > & v) inline
Todo:
Document vector_to_point
Definition at line 146 of file forest_utils_dealii.h.
   {
     const Point<dim> beta =
         dim == 1 ? Point<dim> (v[0]) : dim == 2 ? Point<dim> (v[0], v[1]) :
         dim == 3 ? Point<dim> (v[0], v[1], v[2]) : Point<dim> ();
     return beta;
   }
template<int dim> Point<dim> Forest::new_point (const double v0 = 0.0, const double v1 = 0.0, const double v2 = 0.0) inline
We create a new Point<dim> object.
Depending on the template parameter dim we will use the corresponding number of input elements. In case the number of provided elements is small than the dimension the default will be to fill with a zero value.
Parameters
v0
v1
v2
Returns
Definition at line 167 of file forest_utils_dealii.h.
   {
     const Point<dim> beta = dim == 1 ? Point<dim> (v0) :
                             dim == 2 ? Point<dim> (v0, v1) :
                             dim == 3 ? Point<dim> (v0, v1, v2) : Point<dim> ();
     return beta;
   }
template<int dim> Tensor<1, dim> Forest::p_normal (unsigned int f) inline
The notation is following the following convention (for dim == 3):
* p_normal(0) = {-1,  0,  0}
* p_normal(1) = { 1,  0,  0}
* p_normal(2) = { 0, -1,  0}
* p_normal(3) = { 0,  1,  0}
* p_normal(4) = { 0,  0, -1}
* p_normal(5) = { 0,  0,  1}
*
Parameters
f
Returns
Definition at line 191 of file forest_utils_dealii.h.
Referenced by Forest::ExtractBV< dim >::calculate_current_ass(), and Forest::ExtractBV< dim >::calculate_current_pin().
   {
     return vector_to_point<dim> (r_normal<dim> (f));
   }
template<int dim> unsigned int Forest::normal2face (const Tensor< 1, dim > & normal)
Find the face for which the vector is an outgoing vector.
considering the numbering given by p_normal
* p_normal(0) = {-1,  0,  0}
* p_normal(1) = { 1,  0,  0}
* p_normal(2) = { 0, -1,  0}
* p_normal(3) = { 0,  1,  0}
* p_normal(4) = { 0,  0, -1}
* p_normal(5) = { 0,  0,  1}
*
we return the index f such that p_normal(f) == normal
Parameters
normal
Returns
face
Note
This is probably very inefficient, but for the moment does not matter because it is done in a post processing. Can be made faster if all the constants already exist, and the function is then a member of the class that uses it.
Definition at line 217 of file forest_utils_dealii.h.
Referenced by Forest::ExtractBV< dim >::set_ass_bc(), and Forest::ExtractBV< dim >::set_pin_bc().
   {
     /* We need this constant to define the range */
     const unsigned int faces_per_cell = 2*dim;
     /* Initialization of the face to be returned with an invalid value */
     unsigned int face = faces_per_cell;
     /* Tolerance to decide if the vectors are the same */
     const double tol = 1.e-10;
     /* Run over the faces and compare */
     for (unsigned int f = 0; f < faces_per_cell; ++f)
     {
       /* we check if the vectors are the same direction and orientation */
       if (std::abs (p_normal<dim> (f) * normal - 1.) < tol)
       {
         /* If they are aligned, we store the value and stop the for loop */
         face = f;
         continue;
       }
     }
     /* Verify that the value is inside the expected range */
     Assert(face < faces_per_cell, ExcMessage("face out of bounds"));
     /* Return the value */
     return face;
   }
template<int dim> unsigned int Forest::normal2face (const Point< dim > & normal)
Definition at line 244 of file forest_utils_dealii.h.
   {
     /* We need this constant to define the range */
     const unsigned int faces_per_cell = 2*dim;
     /* Initialization of the face to be returned with an invalid value */
     unsigned int face = faces_per_cell;
     /* Tolerance to decide if the vectors are the same */
     const double tol = 1.e-10;
     /* Run over the faces and compare */
     for (unsigned int f = 0; f < faces_per_cell; ++f)
     {
       /* we check if the vectors are the same direction and orientation */
       if (std::abs (p_normal<dim> (f) * normal - 1.) < tol)
       {
         /* If they are aligned, we store the value and stop the for loop */
         face = f;
         continue;
       }
     }
     /* Verify that the value is inside the expected range */
     Assert(face < faces_per_cell, ExcMessage("face out of bounds"));
     /* Return the value */
     return face;
   }
void Forest::log_print_time (const std::string & msg, double value) inline
Print time statistics message.
Definition at line 32 of file forest_utils_logstream.h.
Referenced by Forest::StatsTimer::print_detailed().
   {
     const std::string prefix = deallog.get_prefix ();
     const std::string label = "TIME  ";
     deallog.pop ();
     deallog.push (prefix + label);
     const std::string units = " sec.";
     const unsigned int time_length = 20;
     const unsigned int pref_length = prefix.size () + 2 + label.size ();
     deallog << std::setw (line_length - time_length - pref_length) << std::left
             << std::setfill ('.') << msg;
     deallog << std::setw (time_length - units.size ()) << std::right
             << std::setfill ('.') << std::scientific << value << units
             << std::flush << std::endl;
     deallog.pop ();
     deallog.push (prefix.substr (0, prefix.size () - 1));
   }
void Forest::log_print_mem (const std::string & msg, double value) inline
Print memory consumption message.
Definition at line 58 of file forest_utils_logstream.h.
Referenced by Forest::StatsMemory::print_detailed().
   {
     const std::string prefix = deallog.get_prefix ();
     const std::string label = "MEMORY";
     deallog.pop ();
     deallog.push (prefix + label);
     const std::string units = "  MB.";
     const double Byte_to_MB = 1. / 1.048576e+6;
     const std::string mem_msg = " memory consumption:";
     const unsigned int mem_length = 20;
     const unsigned int pref_length = prefix.size () + 2 + label.size ();
     deallog << std::setw (line_length - mem_length - pref_length) << std::left
             << std::setfill ('.') << msg + mem_msg;
     deallog << std::setw (mem_length - units.size ()) << std::right
             << std::setfill ('.') << std::scientific << value * Byte_to_MB
             << units << std::flush << std::endl;
     deallog.pop ();
     deallog.push (prefix.substr (0, prefix.size () - 1));
   }
bool Forest::log_table_keff_wgit (const unsigned int iter, const double keff, const double spg, const double err, const double tol, const unsigned int print_freq = 1, const unsigned int indent_times = 1) inline
Print statistics if required and return convergence status.
The expected output is as follows:
FOREST:TABLE::Iter.   0:   keff = 1.15459   spw =   21.0   err = 1.54e-01
FOREST:TABLE::Iter.   1:   keff = 1.16049   spw =   18.0   err = 5.10e-03
FOREST:TABLE::Iter.   2:   keff = 1.16184   spw =   15.0   err = 1.16e-03
FOREST:TABLE::Iter.   3:   keff = 1.16215   spw =   14.0   err = 2.60e-04
...
but it can be tuned by using some parameters.
Definition at line 98 of file forest_utils_logstream.h.
Referenced by Forest::EigenSolver< dim >::power_iteration().
   {
     /* Are we converged? */
     const bool converged = err <= tol;
     /* Do we want to say anything? */
     const bool verbose = iter % print_freq == 0;
     /* If we are converged, or we want to print, we continue. */
     if (converged or verbose)
     {
       /* Define some constants. */
       const unsigned int indent_length = 2;
       const unsigned int space_length = 3;
       const std::string prefix = deallog.get_prefix ();
       const std::string label = "TABLE";
       char sep = ' ';
       std::string indent (indent_length * indent_times, sep);
       std::string space (space_length, sep);
       /* Start the deallog. */
       deallog.pop ();
       deallog.push (prefix + label);
       /* Print the information. */
       deallog << indent;
       deallog << "Iter. " << std::setfill (sep) << std::setw (3) << iter << ":"
               << space;
       deallog << "keff = " << std::setfill (sep) << std::fixed
               << std::setprecision (5) << keff << space;
       deallog << "spg = " << std::setfill (sep) << std::fixed
               << std::setprecision (1) << std::setw (5) << spg << space;
       deallog << "err = " << std::setfill (sep) << std::scientific
               << std::setprecision (2) << err << std::flush << std::endl;
       /* Back to original deallog. */
       deallog.pop ();
       deallog.push (prefix.substr (0, prefix.size () - 1));
     }
     /* return the convergence state. */
     return converged;
   }
bool Forest::log_table_keff (const unsigned int iter, const double keff, const double err, const double tol, const unsigned int print_freq = 1, const unsigned int indent_times = 1) inline
Print statistics if required and return convergence status.
The expected output is as follows:
FOREST:TABLE::  Iter.   0:   keff = 1.15408   err = 1.54e-01
FOREST:TABLE::  Iter.   1:   keff = 1.16051   err = 5.56e-03
FOREST:TABLE::  Iter.   2:   keff = 1.16185   err = 1.15e-03
FOREST:TABLE::  Iter.   3:   keff = 1.16215   err = 2.55e-04
...
but it can be tuned by using some parameters.
Definition at line 156 of file forest_utils_logstream.h.
   {
     /* Are we converged? */
     const bool converged = err <= tol;
     /* Do we want to say anything? */
     const bool verbose = iter % print_freq == 0;
     /* If we are converged, or we want to print, we continue. */
     if (converged or verbose)
     {
       /* Define some constants. */
       const unsigned int indent_length = 2;
       const unsigned int space_length = 3;
       const std::string prefix = deallog.get_prefix ();
       const std::string label = "TABLE";
       char sep = ' ';
       std::string indent (indent_length * indent_times, sep);
       std::string space (space_length, sep);
       /* Start the deallog. */
       deallog.pop ();
       deallog.push (prefix + label);
       /* Print the information. */
       deallog << indent;
       deallog << "Iter. " << std::setfill (sep) << std::setw (3) << iter << ":"
               << space;
       deallog << "keff = " << std::setfill (sep) << std::fixed
               << std::setprecision (5) << keff << space;
       deallog << "err = " << std::setfill (sep) << std::scientific
               << std::setprecision (2) << err << std::flush << std::endl;
       /* Back to original deallog. */
       deallog.pop ();
       deallog.push (prefix.substr (0, prefix.size () - 1));
     }
     /* return the convergence state. */
     return converged;
   }
void Forest::log_print_text (const std::string & msg, unsigned int indent_times = 0) inline
Print msg indenting indent_times.
Parameters
msg
indent_times
Definition at line 204 of file forest_utils_logstream.h.
Referenced by Forest::EigenSolver< dim >::convergence_msg(), Forest::EigenSolver< dim >::EigenSolver(), Forest::PostProcessing< dim >::PostProcessing(), Forest::EigenSolver< dim >::power_iteration(), Forest::PostProcessing< dim >::print_vtk(), Forest::ProbGeom< dim >::ProbGeom(), shell_vmult(), Forest::EigenSolver< dim >::slepc(), Forest::EigenSolver< dim >::solve_eigenproblem(), and Forest::State< dim >::State().
   {
     std::string indent (indent_length * indent_times, ' ');
     const unsigned int pref_length = deallog.get_prefix ().size () + 1;
     deallog
         << indent
         << std::setw (line_length - pref_length - indent_length * indent_times)
         << std::left << std::setfill (' ') << msg << std::flush << std::endl;
   }
void Forest::log_print_line (char sep = '-') inline
Print a line by repeating the character in sep.
Parameters
sep = '-'
Definition at line 221 of file forest_utils_logstream.h.
Referenced by finish_forest(), Forest::EigenSolver< dim >::power_iteration(), Forest::StatsMemory::print_detailed(), Forest::StatsTimer::print_detailed(), Forest::EigenSolver< dim >::slepc(), and start_forest().
   {
     const unsigned int pref_length = deallog.get_prefix ().size () + 1;
     deallog << std::setw (line_length - pref_length) << std::right
             << std::setfill (sep) << sep << std::flush << std::endl;
   }
void Forest::log_print_title (const std::string & end_msg, char sep = ' ') inline
Print title centered end_msg filling empty space with sep.
Parameters
end_msg
sep = ' '
Definition at line 235 of file forest_utils_logstream.h.
Referenced by finish_forest(), Forest::StatsMemory::print_detailed(), Forest::StatsTimer::print_detailed(), and start_forest().
   {
     const unsigned int pref_length = deallog.get_prefix ().size () + 1;
     const unsigned int left_length = (line_length - pref_length
                                       - end_msg.size ())
                                      / 2;
     const unsigned int right_length = line_length - pref_length
                                       - end_msg.size () - left_length;
     deallog << std::string (left_length, sep) << end_msg
             << std::string (right_length, sep) << std::flush << std::endl;
   }
std::string Forest::start_forest (int argc, char ** argv, const unsigned int output_level = 1) inline
Definition at line 249 of file forest_utils_logstream.h.
Referenced by main().
   {
     // Parsing the arguments from the command line
     Forest::CmdOption parse_args;
     Assert(parse_args.exists (argv, argv + argc, "-f"),
         dealii::ExcMessage("Input not specified."));
     std::string input_file = parse_args.get (argv, argv + argc, "-f");
     static std::ofstream ostream_file (input_file + ".log");
     // Preparing the stream for the console output
     deallog.attach (ostream_file);
     deallog.pop ();
     deallog.push ("FOREST");
     deallog.test_mode (false);
     deallog.depth_console (output_level);
     deallog.depth_file (output_level);
     /* Print starting message*/
     log_print_line ('*');
     log_print_title ("FOREST:");
     log_print_title ("(F)ramework (O)riented to (RE)actor (S)imula(T)ions");
     log_print_line ('*');
     /* We return the input file for calling the Input class. */
     return input_file;
   }
void Forest::finish_forest () inline
Definition at line 280 of file forest_utils_logstream.h.
Referenced by main().
   {
     Forest::StatsTimer::instance ().print_detailed ();
     log_print_line ('*');
     log_print_title ("Calculation finished", '.');
     log_print_line ('*');
   }
Variable Documentation
const double Forest::eps6 = 1.e-6
Definition at line 11 of file constants.h.
Referenced by Forest::XS_single::normalize_chi().
const double Forest::eps10 = 1.e-10
Definition at line 12 of file constants.h.
const double Forest::pi = 3.14159265358979324
pi
Definition at line 14 of file constants.h.
Referenced by Forest::ProbGeom< dim >::area_correction_factor(), Forest::QuadratureGaussLegendre< dim >::gaulegxw(), generate_gauss_chebyshev(), generate_gauss_legendre(), and Forest::QuadratureChebyshevLegendre< dim >::set_ordinates().
const double Forest::two_pi = 6.28318530717958648
2*pi
Definition at line 16 of file constants.h.
const double Forest::inv_two_pi = 0.159154943091895336
1/2/pi
Definition at line 18 of file constants.h.
const double Forest::four_pi = 12.5663706143591730
4*pi
Definition at line 20 of file constants.h.
Referenced by Forest::SphericalHarmonics< dim >::get_Y_lm().
const double Forest::inv_four_pi = 0.0795774715459476678
1/4/pi
Definition at line 22 of file constants.h.
Referenced by Forest::QuadratureGaussChebyshev< dim >::get_dimension_weight(), and Forest::QuadratureChebyshevLegendre< dim >::get_dimension_weight().
const unsigned int Forest::line_length = 80 static
Line length used by default in all the printing.
Definition at line 24 of file forest_utils_logstream.h.
const unsigned int Forest::indent_length = 2 static
Indent length used by default in all the printing.
Definition at line 27 of file forest_utils_logstream.h.