FOREST: lapack Namespace Reference
lapack Namespace Reference
Functions
void dgemv_ (const char *TRANS, const int *M, const int *N, const double *alpha, const double *A, const int *LDA, double *X, const int *INCX, const double *beta, double *Y, const int *INCY)
void dgges_ (const char *jobvsl, const char *jobvsr, const char *sort, int(*delztg)(const double *, const double *, const double *), const int *n, double *a, const int *lda, double *b, const int *ldb, int *sdim, double *alphar, double *alphai, double *beta, double *vsl, const int *ldvsl, double *vsr, const int *ldvsr, double *work, const int *lwork, int *bwork, int *info)
void dlaqtr_ (const int *ltran, const int *lreal, const int *n, const double *t, const int *ldt, const double *b, const double *w, double *scale, double *x, double *work, int *info)
void dgetrf_ (int *dim1, int *dim2, double *a, int *lda, int *ipiv, int *info)
void dgetrs_ (char *TRANS, int *N, int *NRHS, double *A, int *LDA, int *IPIV, double *B, int *LDB, int *INFO)
int no_order_ (const double *, const double *, const double *)
Function Documentation
void lapack::dgemv_ (const char * TRANS, const int * M, const int * N, const double * alpha, const double * A, const int * LDA, double * X, const int * INCX, const double * beta, double * Y, const int * INCY)
Referenced by Forest::QZsolver::dgemv(), and Forest::QZsolver::dgemvT().
void lapack::dgges_ (const char * jobvsl, const char * jobvsr, const char * sort, int(*)(const double *, const double *, const double *) delztg, const int * n, double * a, const int * lda, double * b, const int * ldb, int * sdim, double * alphar, double * alphai, double * beta, double * vsl, const int * ldvsl, double * vsr, const int * ldvsr, double * work, const int * lwork, int * bwork, int * info)
Referenced by Forest::QZsolver::dgges().
void lapack::dlaqtr_ (const int * ltran, const int * lreal, const int * n, const double * t, const int * ldt, const double * b, const double * w, double * scale, double * x, double * work, int * info)
Referenced by Forest::QZsolver::dlaqtr().
void lapack::dgetrf_ (int * dim1, int * dim2, double * a, int * lda, int * ipiv, int * info)
Referenced by Forest::LUsolver::dgetrf().
void lapack::dgetrs_ (char * TRANS, int * N, int * NRHS, double * A, int * LDA, int * IPIV, double * B, int * LDB, int * INFO)
Referenced by Forest::LUsolver::dgetrs().
int lapack::no_order_ (const double * , const double * , const double *)
Definition at line 139 of file trans_op_mf_pre.cc.
Referenced by Forest::QZsolver::dgges().
   {
     return 0;
   }