FOREST: dealii::VectorTools Namespace Reference
dealii::VectorTools Namespace Reference
Functions
template<int dim, int spacedim, template< int, int > class DH, class Vector >
void interpolate_to_different_mesh (const InterGridMapSebas< DH< dim, spacedim > > &intergridmap, const Vector &u1, const ConstraintMatrix &constraints, Vector &u2)
template void interpolate_to_different_mesh (const InterGridMapSebas< DoFHandler< 1, 1 > > &, const Vector< double > &, const ConstraintMatrix &, Vector< double > &)
template void interpolate_to_different_mesh (const InterGridMapSebas< DoFHandler< 2, 2 > > &, const Vector< double > &, const ConstraintMatrix &, Vector< double > &)
template void interpolate_to_different_mesh (const InterGridMapSebas< DoFHandler< 3, 3 > > &, const Vector< double > &, const ConstraintMatrix &, Vector< double > &)
template<int dim, int spacedim, template< int, int > class DH, class VECTOR >
void interpolate_to_different_mesh (const InterGridMapSebas< DH< dim, spacedim > > &intergridmap, const VECTOR &u1, const ConstraintMatrix &constraints, VECTOR &u2)
interpolate_to_different_mesh
Function Documentation
template<int dim, int spacedim, template< int, int > class DH, class Vector > void dealii::VectorTools::interpolate_to_different_mesh (const InterGridMapSebas< DH< dim, spacedim > > & intergridmap, const Vector & u1, const ConstraintMatrix & constraints, Vector & u2)
Definition at line 271 of file path_to_intergridmap_dealii.cc.
Referenced by Forest::TransOpMatrixBuilt< dim >::project_angular_to_scalar_mesh(), and Forest::TransOpMatrixBuilt< dim >::project_scalar_to_angular_mesh().
     {
       const DH<dim, spacedim> &dof1 = intergridmap.get_source_grid ();
 #ifdef DEBUG
       const DH<dim, spacedim> &dof2 = intergridmap.get_destination_grid ();
 #endif
       Assert(u1.size()==dof1.n_dofs(),
           ExcDimensionMismatch(u1.size(), dof1.n_dofs()));
       Assert(u2.size()==dof2.n_dofs(),
           ExcDimensionMismatch(u2.size(),dof2.n_dofs()));
       Vector cache;
       // Looping over the finest common
       // mesh, this means that source and
       // destination cells have to be on the
       // same level and at least one has to
       // be active.
       //
       // Therefor, loop over all cells
       // (active and inactive) of the source
       // grid ..
       typename DH<dim, spacedim>::cell_iterator cell1 = dof1.begin ();
       const typename DH<dim, spacedim>::cell_iterator endc1 = dof1.end ();
       for (; cell1 != endc1; ++cell1)
       {
         const typename DH<dim, spacedim>::cell_iterator cell2 =
             intergridmap[cell1];
         // .. and skip if source and destination
         // cells are not on the same level ..
         if (cell1->level () != cell2->level ())
         {
           continue;
         }
         // .. or none of them is active.
         if (!cell1->active () && !cell2->active ())
         {
           continue;
         }
         Assert(cell1->get_fe().get_name() == cell2->get_fe().get_name(),
             ExcMessage ("Source and destination cells need to use the same finite element"));
         cache.reinit (cell1->get_fe ().dofs_per_cell);
         // Get and set the corresponding
         // dof_values by interpolation.
         cell1->get_interpolated_dof_values (u1, cache);
         cell2->set_dof_values_by_interpolation (cache, u2);
       }
       // Apply hanging node constraints.
       constraints.distribute (u2);
     }
template void dealii::VectorTools::interpolate_to_different_mesh (const InterGridMapSebas< DoFHandler< 1, 1 > > & , const Vector< double > & , const ConstraintMatrix & , Vector< double > &)
template void dealii::VectorTools::interpolate_to_different_mesh (const InterGridMapSebas< DoFHandler< 2, 2 > > & , const Vector< double > & , const ConstraintMatrix & , Vector< double > &)
template void dealii::VectorTools::interpolate_to_different_mesh (const InterGridMapSebas< DoFHandler< 3, 3 > > & , const Vector< double > & , const ConstraintMatrix & , Vector< double > &)
Referenced by interpolate_to_different_mesh().
template<int dim, int spacedim, template< int, int > class DH, class VECTOR > void dealii::VectorTools::interpolate_to_different_mesh (const InterGridMapSebas< DH< dim, spacedim > > & intergridmap, const VECTOR & u1, const ConstraintMatrix & constraints, VECTOR & u2)
interpolate_to_different_mesh
Todo:
document me